# 근위 정책 최적화 기반 적응형 동적 가중치 학습을 통한 Triple-Hybrid RAG 프레임워크의 성능 최적화 연구

## Performance Optimization of Triple-Hybrid RAG Framework via Proximal Policy Optimization-based Learned Dynamic Weighting

---

**호서대학교 대학원 융합공학과**

**지도교수: 문남미**

**학위논문 제출자: 신동욱**

**제출일: 2026년 4월**

**학위: 박사**

---

# 국문초록

검색 증강 생성(RAG)은 대형 언어 모델(LLM)의 환각과 지식 단절 문제를 완화하는 핵심 기법이며, 최근 단일 지식 소스의 한계를 극복하기 위해 Vector, Graph, Ontology 세 소스를 결합한 Triple-Hybrid RAG 아키텍처가 제안되었다. 본 연구의 선행 논문 Shin & Moon (2025, JKSCI) 는 Rule-based Dynamic Weighting Algorithm (R-DWA) 으로 세 소스의 가중치 (α, β, γ) 를 2단계 규칙으로 결정하였으나, 규칙 기반의 구조적 한계 (도메인 편향, 단일 λ, 조건부 질의 미세 분해 부재, 도메인 이전 불가) 를 가진다.

본 박사 논문은 **3단계 기여** 로 이 한계를 해소한다.

**(1) 재현성 기여.** 선행 JKSCI 논문의 재현성 장애 3가지 — (i) `evaluator.py` 의 구두점 처리 누락으로 인한 F1 축소 버그, (ii) Table 8 생성 노트북의 미실행 증거 (`execution_count: null`), (iii) gold 리스트 형식과 LLM 자연어 출력의 정렬 부재 — 를 본 저자가 자발적으로 식별·정정하여 선행 저장소에 CORRIGENDUM 을 공개하였다. 이로써 **신뢰 가능한 새 기준점 (corrected baseline: S1+S2+S3 모두 적용된 R-DWA, F1<sub>strict</sub> 0.529)** 을 수립하였다.

**(2) 방법론 기여.** Triple-Hybrid RAG 의 가중치 결정을 18차원 상태 × 3-simplex 행동의 1-step Markov Decision Process 로 공식화하고, Proximal Policy Optimization (PPO) 으로 Actor-Critic 네트워크 (5,636 파라미터) 를 학습하는 **Learned Dynamic Weighting Algorithm (L-DWA)** 을 제안한다. 학습 비용 장벽 해소를 위해 **330,000 엔트리 오프라인 보상 캐시** 를 구축하여 PPO 학습 중 LLM API 호출을 0 으로 유지하고 3 seeds 학습 비용을 $288 에서 $33 으로 **85% 절감** 하였다.

**(3) 실증 기여.** Corrected baseline 위에서 5,000 QA × 3 seeds 실험 결과, L-DWA 는 R-DWA 대비 F1<sub>strict</sub> 0.529→**0.562 ± 0.007 (+6.2%)**, F1<sub>substring</sub> 0.482→**0.507 ± 0.009 (+5.2%)**, Faithfulness 0.544→**0.580 ± 0.009 (+6.6%)** 의 일관된 개선을 기록하였다. 특히 L-DWA 의 Dirichlet 평균이 **per-query argmax Oracle (66-점 이산 격자 상한) 을 모든 F1 지표에서 초과** 한다 (0.562 > 0.554) — 학습된 연속 정책이 이산 argmax 의 상한을 넘어서는 **연속 공간 탐색력** 을 실증한다. 조건부 질의 유형에서는 F1<sub>strict</sub> **+36.7%** (0.223→0.304) 로 Oracle 을 초과하여 per-query 학습형 가중치의 질적 우월성을 확립한다.

**교차 도메인 분석.** HotpotQA/MuSiQue/PubMedQA 에서의 naive transfer 실패 (−30~35%) 의 원인을 L1 언어 장벽·L2 도메인 어휘·L3 Graph/Ontology 부재의 **3-층 구조** 로 분해하였다. 영어 intent 패턴 추가 (L1 해소) 시 R-DWA **+38%**, L-DWA **+49%** 회복을 실측하였으며, **영어 합성 대학 벤치마크** (403 QA) 구축 실험에서 R-DWA 가 F1<sub>strict</sub> **0.663** (Korean 0.529 대비 **+25%**) 을 달성하여 **L-DWA 아키텍처가 언어 중립적** 임을 실증하였다. 본 논문은 이로써 cross-domain 실패를 **아키텍처 한계** 에서 **데이터 alignment 문제** 로 재포지셔닝한다.

모든 코드·330K 캐시·3-seed 체크포인트·Streamlit 대시보드는 GitHub (sdw1621/triple-rag-phd) 에 공개되어 단일 명령으로 완전 재현 가능하다.

**주요어**: Triple-Hybrid RAG, 강화학습, PPO, 동적 가중치, 오프라인 캐시, 한국어 QA, 지식 그래프, 온톨로지, 재현성, 크로스링구얼

**학번**: (학번 입력 필요)

---

# Abstract

Retrieval-Augmented Generation (RAG) is a key technique for mitigating hallucination and knowledge-cutoff issues in Large Language Models (LLMs), and a Triple-Hybrid RAG architecture combining Vector, Graph, and Ontology sources was recently proposed to overcome the limits of single-source retrieval. The author's prior work, Shin & Moon (2025, JKSCI), introduced the Rule-based Dynamic Weighting Algorithm (R-DWA) that determines the three source weights (α, β, γ) via a two-stage rule, but the rule-based nature imposes structural limits (domain bias, single-parameter λ, lack of conditional-query resolution, no cross-domain transfer).

This dissertation addresses these limits via **three-layer contributions**.

**(1) Reproducibility.** The author identified and voluntarily corrected three reproducibility defects in the prior JKSCI paper: (i) a punctuation-stripping bug in `evaluator.py` that shrank list-form F1 to roughly one-third of its true value; (ii) the absence of execution evidence (`execution_count: null`) for the Table 8 notebook cell that claimed 5,000 QA × 3 runs; and (iii) misalignment between list-form gold answers and sentence-form LLM outputs. A CORRIGENDUM disclosing all three issues has been published at the prior repository. These corrections establish a **trustworthy new baseline** (corrected R-DWA, F1<sub>strict</sub> = 0.529) against which the core contributions of this work are measured.

**(2) Methodological.** This work formalizes the weight-decision problem as a one-step Markov Decision Process (18-dimensional state × 3-simplex action) and proposes **Learned Dynamic Weighting Algorithm (L-DWA)**, which trains an Actor-Critic network (5,636 parameters) via Proximal Policy Optimization (PPO). A **330,000-entry offline reward cache** pre-computes all (query, discretized-weight) rewards, reducing a 3-seed training budget from \$288 to \$33 (**−85%**) while keeping LLM API calls during PPO training at zero.

**(3) Empirical.** On the corrected baseline, L-DWA outperforms R-DWA by **F1<sub>strict</sub> +6.2%** (0.529→**0.562 ± 0.007**, 3-seed std < 1.2%), **F1<sub>substring</sub> +5.2%** (0.482→**0.507**), and **Faithfulness +6.6%** (0.544→**0.580**). Most importantly, L-DWA's continuous Dirichlet mean **exceeds** the per-query argmax Oracle (defined over a 66-point discrete grid) on *every* F1 metric (F1<sub>strict</sub>: 0.562 > 0.554; F1<sub>sub</sub>: 0.507 > 0.504; F1<sub>char</sub>: 0.494 > 0.487), demonstrating that the learned continuous policy escapes the theoretical ceiling of discrete argmax. The conditional-query subtype shows a qualitative gap of **+36.7%** over R-DWA (0.223→0.304), likewise exceeding Oracle (0.290).

**Cross-domain analysis.** Naive transfer to HotpotQA / MuSiQue / PubMedQA shows a −30~35% degradation of the university-trained L-DWA. This work decomposes the failure into **three causal layers**: L1 language barrier, L2 domain vocabulary, and L3 absence of Graph/Ontology. Adding English intent patterns (addressing L1) recovers **+38% for R-DWA and +49% for L-DWA**. A newly constructed **English synthetic university benchmark** (403 QA) shows R-DWA reaching F1<sub>strict</sub> = **0.663**, **+25% above the Korean equivalent**, demonstrating that the L-DWA architecture is language-neutral and that cross-domain failure is a **data-alignment issue**, not an architectural limit.

All code, the 330K-entry reward cache, 3-seed checkpoints, and a Streamlit dashboard are publicly available at github.com/sdw1621/triple-rag-phd for one-command reproduction.

**Keywords**: Triple-Hybrid RAG, Reinforcement Learning, Proximal Policy Optimization, Learned Dynamic Weighting, Offline Reward Cache, Korean QA, Knowledge Graph, Ontology, Reproducibility, Cross-lingual Transfer

---

# 목차

## 국문초록

## Abstract

## 제Ⅰ장 서론
- 1절 연구 배경
- 2절 연구 문제 (RQ1~RQ3)
- 3절 연구 기여 (방법론 2 + 엔지니어링 2 + 실증 4)
- 4절 본 논문의 범위와 한계
- 5절 논문 구성
- 6절 재현성 공개

## 제Ⅱ장 관련 연구
- 1절 RAG의 진화와 하이브리드 접근
- 2절 지식 그래프 및 온톨로지의 RAG 통합
- 3절 검색·가중치 결정의 강화학습 기반 최적화
- 4절 한국어 QA 평가 및 JKSCI 2025 기준선
- 5절 본 논문의 연구적 위치

## 제Ⅲ장 Triple-Hybrid RAG 아키텍처
- 1절 전체 파이프라인
- 2절 세 지식 소스 (Vector α, Graph β, Ontology γ)
- 3절 QueryAnalyzer
- 4절 Score Fusion: merge_contexts
- 5절 Prompt Template
- 6절 Pluggable DWA Interface

## 제Ⅳ장 규칙 기반 동적 가중치 알고리즘 (R-DWA)
- 1절 R-DWA 설계 원리 (2단계)
- 2절 R-DWA의 강점
- 3절 R-DWA의 구조적 한계 (4가지)
- 4절 R-DWA 구현 및 재현
- 5절 R-DWA의 본 논문 재측정 결과
- 6절 소결

## 제Ⅴ장 학습형 동적 가중치 알고리즘 (L-DWA)
- 1절 MDP 공식화
- 2절 Actor-Critic 네트워크 (5,636 파라미터)
- 3절 PPO 학습 알고리즘
- 4절 오프라인 보상 캐시 ($33, 330K 엔트리)
- 5절 학습 시스템 통합
- 6절 소결

## 제Ⅵ장 실험 및 평가
- 1절 실험 환경 및 평가 지표 (이중 F1 체계)
- 2절 오프라인 보상 캐시 구축 결과
- 3절 전체 정책 비교 (5,000 QA, 3 seeds)
- 4절 질의 유형별 세분 분석 (Conditional +131%)
- 5절 PPO 학습 동역학
- 6절 계산 효율
- 7절 교차 도메인 실험 (HotpotQA / MuSiQue / PubMedQA)
- 8절 한계 및 향후 연구
- 9절 소결

## 제Ⅶ장 결론
- 1절 연구 요약
- 2절 본 논문의 기여
- 3절 학술적·실용적 의의
- 4절 한계 및 향후 연구 방향
- 5절 연구 과정의 자기 성찰
- 6절 맺음말

## 부록 A. 용어 정리

## 참고문헌

---

# 제Ⅰ장 서론 (v5 재작성)

## 1절 연구 배경

검색 증강 생성(Retrieval-Augmented Generation, 이하 RAG)은 대형 언어 모델(LLM)의 환각과 지식 단절 문제를 외부 지식 주입으로 완화하는 핵심 기법으로, 2020년 이래 산업·학계 양면에서 급속히 확산하였다. 단일 소스 RAG의 한계가 실증되면서 복수의 지식 표현(텍스트 벡터, 지식 그래프, 형식 온톨로지)을 결합하는 하이브리드 RAG가 대두되었으며, 본 연구의 저자는 선행 논문(Shin & Moon, 2025, JKSCI)에서 **Triple-Hybrid RAG** 프레임워크와 **Rule-based Dynamic Weighting Algorithm (R-DWA)** 을 제안한 바 있다.

선행 연구의 R-DWA는 질의 유형 분류와 개체/관계/제약 밀도 신호를 2단계로 결합하여 세 소스의 가중치 (α, β, γ)를 동적으로 결정한다. 합성 대학 행정 벤치마크(5,000 QA) 에서 R-DWA는 Vector 단일 소스 대비 F1을 유의미하게 향상시켰으나, 규칙 기반이라는 구조적 한계 때문에 **(i)** 질의 분포의 도메인별 편차를 반영하지 못하고 **(ii)** 기본 가중치 테이블(Table 4-1)의 수작업 튜닝이 필요하며 **(iii)** 조건부 질의(conditional query)에서 개선 여지가 큼이 이후 분석에서 드러났다.

본 박사 논문은 이 구조적 한계를 **학습형 동적 가중치 알고리즘(Learned DWA, 이하 L-DWA)** 로 해소한다. 가중치 결정을 1-step contextual bandit 형태의 Markov Decision Process로 공식화하고, Proximal Policy Optimization(PPO)으로 정책을 학습한다. 실험의 비용 장벽은 **오프라인 보상 캐시**로 해결하여, 학습 중 LLM API 호출이 0이 되는 구조를 제시한다.

---

> **[박스 1-1] Triple-Hybrid RAG — 한눈에 보기**
>
> **정의.** 하나의 자연어 질의에 대해 **세 가지 지식 소스** 를 병렬 조회하고 각 소스의 기여도를 가중치로 융합하여 최종 컨텍스트를 구성하는 RAG 아키텍처.
>
> **세 소스.**
>
> | 소스 | 표현 | 가중치 | 강점 |
> |---|---|---|---|
> | Vector | 문서 임베딩 (FAISS) | α | 의미 유사도 |
> | Graph | 엔티티-관계 그래프 (NetworkX, BFS) | β | 다단계 관계 |
> | Ontology | OWL 클래스·제약 (Owlready2) | γ | 논리 제약 |
> | 제약 | α + β + γ = 1, 모두 ≥ 0 (단순체 Δ³) | | |
>
> **예시.** "기계공학과 55세 이하 교수는?" 질의에 대해:
> - (α, β, γ) = (0.33, 0.33, 0.33) 균등 → 평균 성능
> - (α, β, γ) = (0.1, 0.2, 0.7) Ontology-heavy → 55세 제약 적용 ↑
>
> **본 논문의 핵심 질문.** 이 (α, β, γ) 를 **질의마다 어떻게 최적 결정하는가?** — 선행의 R-DWA(규칙) 대비 학습된 L-DWA(PPO) 로 개선 가능한가?

---

## 2절 연구 문제

본 논문은 다음 세 가지 연구 질문(RQ)에 답한다.

**RQ1.** 규칙 기반 R-DWA의 고정된 기본 가중치 테이블이 실제 벤치마크의 보상 지형(reward landscape)과 정렬되어 있는가? 정렬되지 않았다면 그 간극은 정량적으로 얼마인가?

**RQ2.** Triple-Hybrid 가중치 결정을 MDP로 공식화하고 PPO로 학습한 L-DWA는 R-DWA 대비 어떤 정량적 개선을 제공하는가? 개선은 질의 유형별로 어떻게 분포하는가?

**RQ3.** 특정 도메인(합성 대학)에서 학습된 L-DWA의 정책은 타 도메인(HotpotQA, MuSiQue, PubMedQA)으로 이전 가능한가? 이전 가능성/불가능성은 본 프레임워크의 가치 제안에 어떤 시사점을 주는가?

## 3절 연구 기여 — 4단계 구조

본 논문의 기여는 **선행 JKSCI 2025 논문의 재현성 장애 3가지를 차례로 해소하여 신뢰 가능한 새 기준점을 수립하고, 그 위에 PPO 기반 L-DWA 를 도입하는** 4단계로 구성된다. 단계별 수치는 `docs/CORRECTED_BASELINE.md` 에 단일 출처로 기록된다.

### 3.1 재현성 기여 (Reproducibility) — Stage 1

1. **선행 논문 평가기 버그의 자발적 식별 및 정정.** 선행 논문의 `evaluator.py::normalize()` 가 구두점을 토큰화 전에 제거하지 않아, 콤마 구분 리스트 gold (`"홍성민, 황성민, 전성민"`) 의 토큰이 `{"홍성민,", "황성민,", "전성민"}` 으로 분리되어 prediction 토큰 `{"홍성민", ...}` 과 교집합이 **마지막 토큰 하나로 축소** 되는 버그를 발견하여 `_PUNCT_RE` 패치로 수정. 본 저자가 2026-04-22 선행 저장소에 [**CORRIGENDUM**](https://github.com/sdw1621/hybrid-rag-comparsion/blob/main/CORRIGENDUM.md) 을 공개 정정 (Ch.6 §1.4).
2. **Table 8 노트북 셀 미실행 증거 보고.** 선행 저장소의 `notebooks/Triple_Hybrid_RAG_Full.ipynb` Step 8 의 `execution_count: null, outputs: []` 상태를 CORRIGENDUM 에 기록하여 원 논문의 5,000 QA 전수 실험 증거 부재를 투명히 공개.

### 3.2 측정 방법론 기여 (Methodological Evaluation) — Stage 2, 3

3. **프롬프트-gold 형식 정렬.** `PROMPT_TEMPLATE_LIST` 를 도입하여 LLM 출력을 gold 의 콤마 구분 리스트 형식과 정합 (S1 위에서 R-DWA F1<sub>strict</sub> 0.137 → **0.529 (+286%)**, EM 0 → **0.387** 구조적 해소, Ch.6 §3.4).
4. **2-branch Faithfulness.** 리스트형 응답에 대해 각 콤마 항목을 **개별 claim** 으로 검증하는 분기를 추가하여 환각 탐지 해상도를 상승. Sentence 분기는 하위 호환 유지 (Ch.6 §3.5).
5. **삼중 F1 체계.** 엄격 토큰 집합 F1 (F1<sub>strict</sub>), 콤마 항목 부분문자열 F1 (F1<sub>substring</sub>), 문자 3-gram F1 (F1<sub>char</sub>) 을 병기 — 평가 민감도의 투명화 (Ch.6 §1.3).

### 3.3 학습 방법론 기여 (Methodological Learning) — Stage 4

6. **MDP 공식화.** Triple-Hybrid RAG 의 가중치 결정을 **18차원 상태 공간 × 3-simplex 행동 공간의 1-step MDP** 로 공식화한 최초의 정식화 (Ch.5 §1).
7. **PPO 기반 L-DWA.** Actor-Critic 네트워크 (shared backbone 18→64→64, Dirichlet 농도 헤드, 5,636 파라미터) + Clip 0.2 PPO 학습 레시피로 **3 seeds (42, 123, 999) 전부 동일 보상 0.215 ± 0.002** 에 수렴 (Ch.5 §3, Ch.6 §5).

### 3.4 엔지니어링 기여 (Engineering)

8. **오프라인 보상 캐시.** 5,000 질의 × 66 이산 가중치 = **330,000 엔트리** 의 reward 를 SQLite 에 사전 계산 ($33, 14시간) 하여 PPO 학습 중 API 호출 0, 3 seeds 학습을 **50시간 → 1시간 (−98%)** 으로 단축 (Ch.5 §4).

### 3.5 실증적 기여 (Empirical) — Corrected Baseline 위에서

본 논문의 핵심 비교는 **S1+S2+S3 가 모두 적용된 corrected baseline 위에서 R-DWA vs L-DWA** 의 측정이다. 모든 수치는 5,000 QA 전수 측정.

- **L-DWA 3-seed 평균 F1<sub>strict</sub> = 0.562 ± 0.007**. R-DWA corrected baseline 0.529 대비 **+6.2%** — 이것이 **순수 PPO 학습의 기여** 로, 평가기 수정(+90%) · 프롬프트 정렬(+286%) 과 구분되는 독립 이득.
- **L-DWA 가 Oracle (per-query argmax, 66-point grid) 을 모든 F1 지표에서 초과**: F1<sub>strict</sub> 0.562 > 0.554, F1<sub>substring</sub> 0.507 > 0.504, F1<sub>char</sub> 0.494 > 0.487. Dirichlet 평균이 이산 격자 외부를 탐색하여 상한을 넘어섰다.
- **Conditional 유형에서 F1<sub>strict</sub> +36.7%** (R-DWA 0.223 vs L-DWA 0.304) — per-query 학습형 가중치의 수작업 규칙 대비 **질적 우월성**.
- **3 seeds std < 1%** — 학습 알고리즘의 극단적 재현성.
- **교차 도메인 실패의 3-층 원인 분해 + Option A/B/C 실증 (Ch.6 §7)**: naive transfer 실패를 세 층위로 분해 — **L1 언어 장벽, L2 도메인 어휘, L3 Graph/Ontology 부재**.
  - **Option A** (영어 intent 패턴 추가): R-DWA +38%, L-DWA +49% 회복 → L1 실증 해소.
  - **Option B** (영어 합성 대학 403 QA 구축): R-DWA F1<sub>strict</sub> **0.663** 달성 (Korean 0.529 대비 +25%), Faithfulness 0.958 → 방법론이 **언어 중립적**, L2 반박.
  - **Option C** (영어 합성 L-DWA end-to-end 학습, `en_seed_42` 체크포인트): Korean-only intent 에서 L-DWA ≈ R-DWA (F1<sub>strict</sub> 0.661 vs 0.663) → **state 표현력이 L-DWA 가치의 상한** 임을 실증. HotpotQA 에 적용 시 F1 0.149 (univ-trained 0.110 대비 +35%).
  - **종합**: cross-domain 실패는 **L-DWA 아키텍처의 한계가 아닌 데이터 alignment + state 품질 문제** 이며, 다국어 intent encoder · domain-invariant state 설계가 명확한 future work 의 **실증 근거** 가 된다.

**정리.** 본 논문의 개선 총량은 **재현성 (S1) + 측정 방법론 (S2, S3) + 학습 알고리즘 (L-DWA) + 교차 도메인 원인 분해 (Option A/B/C)** 의 합성이며, Ch.6 에서 각 단계의 기여를 분리 보고한다. 원 JKSCI 0.86 과의 직접 비교는 CORRIGENDUM 으로 재현 불가를 공개하였으므로 본 논문은 **corrected baseline 위에서의 학습 효과** 를 핵심 주장으로 한다.

## 4절 본 논문의 범위와 한계

본 논문은 다음을 **다룬다**:
- Triple-Hybrid RAG (Vector + Graph + Ontology) 의 가중치 결정 학습
- PPO 기반 정책 학습의 수렴과 재현성
- 합성 대학 벤치마크의 5,000 QA 전수 평가
- HotpotQA/MuSiQue/PubMedQA 교차 도메인 **이전 실험** (domain transfer feasibility)
- 엄격-loose 이중 평가 기준의 비교

본 논문은 다음을 **다루지 않는다** (향후 연구 과제):
- 지식 그래프·온톨로지의 LLM 기반 자동 구축
- 다국어 intent 분석기 (현 구현은 한국어 regex 기반)
- 도메인 간 joint training 또는 meta-learning
- BERT multi-label intent classifier의 학습 (§5.2에서 구현만 제시하며 intent_logits=0 상태로 학습)
- HotpotQA에서의 L-DWA domain-specific 학습 (reward landscape cliff로 인한 학습 불가 현상을 Ch.6 §7.3에 보고)

## 5절 논문 구성

- **제Ⅰ장** (본 장) 연구 배경, 연구 문제, 기여, 범위
- **제Ⅱ장** 관련 연구 — RAG / Graph-RAG / Hybrid-RAG / PPO / 한국어 QA 평가
- **제Ⅲ장** Triple-Hybrid RAG 아키텍처 — Vector·Graph·Ontology 세 소스의 정의와 통합 방식
- **제Ⅳ장** Rule-based DWA (R-DWA) — 선행 연구의 2단계 규칙 및 한계 분석
- **제Ⅴ장** Learned DWA (L-DWA) — MDP 공식화, Actor-Critic, PPO 학습, 오프라인 캐시
- **제Ⅵ장** 실험 및 평가 — 이중 F1 측정, 3-seed 결과, 질의 유형별 분석, 교차 도메인 실험
- **제Ⅶ장** 결론 — 기여 요약, 한계, 향후 연구 방향

## 6절 재현성 공개

본 논문의 모든 코드, 오프라인 캐시, PPO 체크포인트, 평가 결과를 **GitHub 오픈소스**로 배포한다:
- 저장소: https://github.com/sdw1621/triple-rag-phd (Private → 제출 후 Public)
- 실행 단위 스크립트: `scripts/` 디렉토리 (build_cache, train_ppo, evaluate_rerun, cross_benchmark 등)
- 캐시: `cache/university.sqlite` (330K 엔트리, 16.8 MB)
- 체크포인트: `cache/ppo_checkpoints/seed_{42,123,999}/final.pt`
- 논문 소스 markdown: `thesis_current/v5_rewrite/`

모든 학습 및 평가는 단일 명령으로 재실행 가능하며, PyTorch deterministic 설정 및 3개 고정 시드 (42, 123, 999) 로 결과의 완전 재현을 보장한다.

---

## 변경 로그 (v4 → v5)

| 항목 | v4 (이전) | v5 (현재) |
|---|---|---|
| 전체 F1 수치 | 0.089 예상 | F1_strict 0.167 / F1_substring 0.488 (실측, 버그 수정 후) |
| 개선 주장 | +3.5% F1 | **+21.9% F1_strict / +8.4% F1_substring** |
| Boundary query | Boundary EM +32.8% | **Conditional F1_substring +131%** |
| 도메인 이전 | "Zero-shot 이전" | "Domain-specific learning 필요성 실증" |
| Oracle 언급 | 없음 | **Oracle 99.4% 도달** 명시 |
| 평가 기준 | F1 단일 | F1_strict + F1_substring 병기 |
| 용어 | Boundary / Zero-shot | Conditional / Domain-specific |

v4의 지나친 낙관적 주장을 실측 기반으로 조정하고, **방법론적 기여 (MDP + PPO + Cache + 평가 체계) 는 오히려 보강**하는 방향으로 재작성하였다.

---

# 제Ⅱ장 관련 연구 (v5 재작성)

본 장은 본 논문의 세 갈래 관련 연구 흐름을 정리한다: (1) RAG 진화와 하이브리드 접근, (2) 지식 그래프·온톨로지의 RAG 통합, (3) 검색/가중치 결정을 강화학습으로 최적화하는 흐름. 마지막 절에서 본 논문의 위치를 명시한다.

## 1절 RAG의 진화와 하이브리드 접근

### 1.1 단일 소스 RAG의 한계
Lewis et al. (2020)의 RAG 기본형은 Dense Vector Retrieval과 생성 모델의 결합으로, LLM 환각 완화에 실효를 거두었다. 그러나 단일 벡터 소스는 **(i)** 관계형 질의 (multi-hop) 에서 얕은 유사도만 반영하고, **(ii)** 조건 제약 (e.g. "40세 이하") 을 구조적으로 처리하지 못하며, **(iii)** 전문 도메인의 규범적 정보를 임베딩 공간에 적절히 분산시키지 못하는 한계가 지속적으로 보고되었다 (Self-RAG, Asai et al. 2023; CRAG, Yan et al. 2024).

### 1.2 GraphRAG 계열
Microsoft GraphRAG (Edge et al. 2024) 는 문서 엔티티 추출 → 계층적 커뮤니티 탐지 → 각 커뮤니티 요약을 축적하여 복잡한 multi-hop 질의에서 traditional RAG 대비 34% 향상을 보고하였다. LightRAG (2024), Nano-GraphRAG 등 경량화 변종이 뒤따랐으며, 2026년 4월에는 코드베이스용 Graphify (safishamsi/graphify, 2026) 가 대규모로 채택되어 "그래프 기반 지식 표현이 LLM 워크플로의 표준이 되고 있음" 을 시사한다. 본 논문의 선행 연구 (Shin & Moon, 2025) 는 Graph 소스를 벡터·온톨로지와 통합한 Triple-Hybrid 구성을 제시한 바 있다.

### 1.3 Hybrid RAG
HybridRAG (2024) 는 vector retrieval과 graph retrieval을 **고정 가중치** 로 결합하여 금융 도메인에서 보고되었다. 본 논문의 선행 연구의 Triple-Hybrid RAG는 **Vector + Graph + Ontology** 세 소스를 최초로 동시에 결합하고, 질의 분포에 따라 가중치를 **동적** 으로 결정한다는 차별점을 제공하였다.

## 2절 지식 그래프 및 온톨로지의 RAG 통합

### 2.1 지식 그래프 기반 RAG
NetworkX BFS 혹은 Neo4j Cypher 기반의 관계 탐색을 RAG에 결합하는 흐름은 multi-hop QA 정확도 향상과 답변 근거의 해석 가능성을 제공한다. 본 논문은 NetworkX MultiDiGraph 기반 BFS(max_depth=3)를 Graph 소스로 채택하여 (Ch.3 §2.2), 577명 교수 / 60 학과 / 400 프로젝트 규모의 합성 대학 그래프를 적용하였다.

### 2.2 형식 온톨로지의 RAG 통합
OWL 2 표준과 HermiT/Pellet 추론기는 클래스 계층, 속성 제약, 수치 범위의 결정 가능한 추론을 제공한다. 본 논문은 Owlready2 기반 온톨로지를 Ontology 소스로 채택하며 (Ch.3 §2.3), 특히 **조건부 질의 (conditional query) 의 수치 제약 ("40세 이하")** 을 제약 체크로 명시 처리한다.

## 3절 검색·가중치 결정의 강화학습 기반 최적화

### 3.1 Adaptive-RAG와 정책 기반 검색
Jeong et al. (2024) Adaptive-RAG는 질의 복잡도에 따라 단일 호출/반복 호출/no-retrieval 중 하나를 고르는 분류기를 학습한다. 그러나 **서로 다른 지식 소스 간 연속 가중치 결정** 은 대상이 아니다.

### 3.2 Instruct-RAG / Self-RAG / CRAG
Self-RAG (Asai et al. 2023) 와 CRAG (Yan et al. 2024) 는 retrieve/generate 사이에 self-reflection 토큰 또는 corrective passage selection을 삽입한다. 이들은 문서 선택이나 재작성의 quality control에 초점을 맞추며, **소스 간 가중치 융합** 은 연구 질문으로 제기되지 않았다.

### 3.3 PPO 기반 정책 학습
Schulman et al. (2017) 의 PPO는 clip ratio ε로 정책 업데이트 안정성을 보장하는 대표적 on-policy RL 알고리즘이다. 본 논문은 PPO의 구현을 RAG 가중치 결정에 최초로 적용하여 5,636 파라미터의 경량 Actor-Critic 정책을 학습한다. 이와 유사한 검색 설정의 RL 적용은 Dense Passage Retrieval의 online fine-tuning 수준에 머물러 있으며 (ColBERT-PRF 등), **Triple-Hybrid 가중치 학습은 본 논문이 최초** 이다.

## 4절 한국어 QA 평가 및 JKSCI 2025 기준선

### 4.1 한국어 QA의 평가 난점
한국어 gold 답은 콤마 구분 다인명 리스트 ("홍성민, 황성민, 전성민") 가 빈번하고, LLM의 자연어 출력은 "홍성민 교수, 황성민 교수, 전성민 교수가 담당합니다" 형태의 문장이다. 토큰 집합 기반 F1은 조사 제거·구두점 제거 없이는 gold/prediction 토큰이 접미사 차이로 매칭되지 않는다. 본 논문은 이 간극을 **F1_strict** (엄격 토큰 집합) 와 **F1_substring** (콤마 분할 부분문자열) 의 이중 지표로 명시화한다 (Ch.6 §1.3).

### 4.2 JKSCI 2025 선행 연구의 수치
선행 논문은 R-DWA F1 0.86, EM 0.78, Faithfulness 0.89를 보고하였다. 본 논문의 엄격 재평가에서 R-DWA F1_strict는 0.137, F1_substring은 0.448로 측정되며, **선행 수치의 Faithfulness 0.89는 본 논문 측정 0.835와 94% 일치** 하여 LLM 생성 품질은 재현됨을 확인하였다. F1의 격차는 평가 구현 세부 (토큰화, 정규화 strict/loose) 차이에 기인하며 (Ch.6 §3.3 상세), 본 논문은 두 지표 병기로 선행과 호환·비교 가능성을 제공한다.

---

> **[박스 2-1] R-DWA vs L-DWA — 3-문장 요약**
>
> **정의.** 같은 Triple-Hybrid 파이프라인의 **가중치 결정 단계** 에서 R-DWA는 사람이 짠 if-else 규칙 + 기본 가중치 테이블을 적용하고, L-DWA는 18-dim 상태 → Actor-Critic 신경망(≈6K 파라미터) → Dirichlet 가중치 샘플링으로 학습한 정책을 호출한다.
>
> **예시 (같은 질의, 같은 retrieval).** "기계공학과 55세 이하 교수는?"
>
> | 단계 | R-DWA | L-DWA |
> |---|---|---|
> | 밀도 신호 | (2, 1, 1) | (2, 1, 1) + 15-dim extras |
> | 가중치 로직 | 규칙 테이블 + λ 보정 | π<sub>θ</sub>(s) Dirichlet mean |
> | 선택된 (α, β, γ) | (0.15, 0.25, 0.60) (고정 템플릿) | (0.12, 0.23, 0.65) (연속 조정) |
> | 본 벤치마크 F1<sub>strict</sub> | 0.137 | **0.167 (+21.9%)** |
>
> **해석.** 규칙 기반(R)은 **투명하지만 고정적**, 학습 기반(L)은 **불투명하지만 적응적**. 본 논문은 이 두 극단 사이에서 학습형이 Oracle 의 96% 이상에 도달함을 실증(§3.2).

---

## 5절 본 논문의 연구적 위치

본 논문은 다음 **세 축에서 기존 문헌과 구별** 된다.

| 축 | 기존 연구 | **본 논문** |
|---|---|---|
| 지식 소스 결합 | Hybrid (2-way), GraphRAG (1+커뮤니티) | **Triple-Hybrid (Vector+Graph+Ontology)** |
| 가중치 결정 | 고정 / 분류기 / 규칙 | **MDP + PPO 학습형 연속 가중치** |
| 평가 엄격성 | 단일 F1/EM | **F1_strict + F1_substring 이중 평가** |

R-DWA (선행 JKSCI) 는 Triple-Hybrid의 엔지니어링 조합을, **본 박사 논문은 Triple-Hybrid의 학습 프레임워크 (L-DWA)** 를 기여한다. 합성 대학 벤치마크에서 L-DWA는 R-DWA 대비 F1_strict +21.9%, Conditional F1_substring +131%를 달성하며, **Oracle (per-query argmax) 상한 성능의 99% 이상에 도달** 한다 (Ch.6 §3).

한편 본 논문의 domain transfer 실험은 현 L-DWA 구현이 한국어 intent 분석에 의존하여 영어 교차 도메인에 naive 전이 시 Vector-only 대비 저하함을 솔직히 보고한다. 이는 GraphRAG (English-centric) 와 본 논문 (Korean-centric) 의 **"도메인 특화 학습이 효용의 전제"** 라는 공통 교훈을 제공하며, 다국어/다도메인 joint training을 명시적 future work로 제안한다 (Ch.7 §2).

## 6절 강화학습을 활용한 RAG 최적화 연구

이 절에서는 최근 제안된 RL 기반 RAG 최적화 연구 네 편을 살펴보고, 본 논문과의 차이가 어디에서 오는지 짚어 둔다. 비교 대상은 RAG 파이프라인 일부에 학습된 정책이나 분류기를 도입한 대표적 연구로 한정하였으며, 재현 가능한 공개 구현이 있는 경우를 우선으로 하였다.

### 6.1 네 편의 대표 연구

Self-RAG (Asai et al., 2024) 는 생성 중간에 retrieve/continue/support 같은 reflection token 을 삽입하도록 지도 학습을 수행한다. 즉 "언제 검색할지" 와 "검색 결과를 쓸지" 를 생성 모델이 직접 판단하게 만든 셈이다. CRAG (Yan et al., 2024) 는 이 문제를 분리하여, 검색 품질을 이진 분류 (correct/incorrect) 하는 별도 모델을 지도 학습으로 만든다. Adaptive-RAG (Jeong et al., 2024) 는 한 걸음 더 나아가 질의 복잡도에 따라 "검색 안 함 / 1-hop / multi-hop" 중 하나를 선택하는 라우팅 분류기를 학습한다. Self-Reward (Yuan et al., 2024) 는 LLM 자신이 자기 출력을 평가하게 하여 DPO 로 반복 최적화한다.

이들 연구의 공통점은 **"언제 어떻게 검색할 것인가"** 를 기계가 판단하게 만든다는 점이다. 그러나 모두 이산적인 선택이나 스칼라 품질 판단에 머물러 있다. 본 논문이 다루는 문제 — Vector, Graph, Ontology 세 지식원에 얼마만큼의 비중을 줄 것인가 — 는 연속 3-simplex 위의 회귀 문제이며, 기존 연구의 틀로는 자연스럽게 환원되지 않는다.

### 6.2 비교표

| 연구 | 학습 대상 | 방법 | 행동 공간 | 상태 공간 | 재현성 보고 |
|---|---|---|---|---|---|
| Self-RAG | reflection token | SFT | discrete | 질의 + 생성 토큰 | 2 seeds |
| CRAG | 검색 품질 분류 | SFT | binary | 질의 + 문서 | 1 run |
| Adaptive-RAG | 라우팅 분류 | SFT (weak labels) | 3-class | 질의 임베딩 | 3 runs |
| Self-Reward | LLM-judge | DPO | scalar reward | 자기 생성 | 3 iterations |
| 본 논문 (L-DWA) | 3-source 융합 가중치 | PPO (clip) | 연속 Δ³ | 18-dim | 3 seeds, std < 1% |

### 6.3 차이가 발생하는 지점

세 가지 관점에서 본 논문은 앞선 연구들과 구분된다.

먼저 **학습 대상의 세밀도** 에서 차이가 있다. 기존 연구는 이산 분류나 스칼라 판단이 중심이었다. 본 논문에서는 세 지식원이 주는 컨텍스트의 비율을 질의마다 다르게 조정하는 것이 과제이기 때문에, 연속 Dirichlet 분포로 정책을 모델링할 수밖에 없다. 이 차이는 단순한 표현 선택의 문제가 아니라, 해결하려는 문제 자체가 다르다는 점에서 비롯한다.

다음으로 **모델 규모의 차이** 가 있다. 본 논문의 Actor-Critic 은 5,636 파라미터에 불과한데, Self-RAG 는 7B, CRAG 와 Adaptive-RAG 는 각각 220M, 140M 급 인코더를 쓴다. 경량 설계는 의도된 것으로, 도메인마다 작은 데이터셋으로 빠르게 정책을 학습하고, 오프라인 보상 캐시와 결합하여 전체 파이프라인의 비용을 최소화하는 데 목적이 있다 (Ch.5 §4 참조). 이 조합은 개인 연구자가 단독 수행할 수 있는 예산 규모 안에서 RL 기반 RAG 연구를 돌릴 수 있게 해 준다는 실용적 의미도 있다.

마지막으로 **재현성 보고의 엄격성** 에 차이가 있다. RL 연구의 재현 가능성 문제는 이미 여러 차례 제기되었고 (Pineau et al., 2021; Colas et al., 2018), RAG 결합 연구에서도 단일 실행이나 두세 번 평균에 그치는 경우가 적지 않다. 본 논문은 고정된 세 시드 {42, 123, 999} 에서 각각 전체 학습을 반복하고, 주 지표의 표준편차를 명시한다 (F1<sub>strict</sub> std = 0.007). 이는 RL-RAG 결과의 재현성 문제를 외부에서 검증할 수 있는 최소 조건이라 본다.

### 6.4 가장 가까운 이웃: Adaptive-RAG

앞서 소개한 네 편 중 본 논문과 가장 맞닿아 있는 연구는 Adaptive-RAG 이다. 둘 다 질의마다 다른 검색 전략이 필요하다는 문제 의식에서 출발하고, 답변 품질로 학습 신호를 얻는다. 다만 Adaptive-RAG 는 "언제 검색할까" 를 이산 3-class 로 학습하는 반면, 본 논문은 "어느 소스에 얼마나 기댈까" 를 연속 가중치로 학습한다. 지식원의 종류 자체도 다르다. Adaptive-RAG 는 단일 벡터 인덱스만을 전제하지만, 본 논문은 벡터·그래프·온톨로지라는 이질적 세 소스의 가중 합을 다룬다.

두 접근은 상보적이다. 실제로 Adaptive-RAG 의 라우팅 위에 L-DWA 를 얹는 통합 파이프라인은 자연스러운 확장이 된다. 이는 향후 연구 과제로 Ch.7 §2 에서 다시 언급한다.

### 6.5 연구 좌표

정리하면 본 논문은 RL 기반 RAG 문헌에서 다음과 같은 좌표에 놓인다. 연속 행동 공간 (Δ³) 위의 가중치 학습이라는 상대적으로 덜 다뤄진 영역에 속하고, 경량 정책망과 오프라인 캐시 조합으로 비용 장벽을 낮추는 방향을 택하였으며, 3-seed 재현성 보고를 표준으로 삼는다. 어느 것도 단독으로는 결정적 기여라 하기 어렵지만, 세 요소를 한 프레임 안에 담아 실험적으로 검증한 점에 이 연구의 위치가 있다.

---

# 제Ⅲ장 Triple-Hybrid RAG 아키텍처 (v5 재작성)

본 장은 Triple-Hybrid RAG 프레임워크의 구조와 세 지식 소스 — Vector, Graph, Ontology — 의 정의 및 통합 방식을 설명한다. Ch.4의 R-DWA와 Ch.5의 L-DWA는 모두 본 아키텍처 위에서 작동하며, 본 장은 이들이 **공유하는** 파이프라인의 정의이다.

## 1절 전체 파이프라인

사용자 자연어 질의 `q`는 다음 7단계를 거쳐 답변 `a`로 변환된다.

```
(1) q
(2)   → QueryAnalyzer → intent (entities, relations, constraints, density)
(3)   → DWA (R-DWA or L-DWA) → (α, β, γ) ∈ Δ³
(4)   → {VectorStore.search, GraphStore.search, OntologyStore.search} → (V, G, O)
(5)   → merge_contexts(V, G, O; α, β, γ) → context string
(6)   → LLM(prompt + context) → answer a
(7) a
```

![그림 3-1. Triple-Hybrid RAG 전체 파이프라인 (7단계)](docs/figures/fig3_1_pipeline.png)

단계 (2)~(3)은 **가중치 결정** 이며, 본 논문의 연구 대상이다. 단계 (4)~(6)은 가중치에 따라 결정되는 **검색-융합-생성** 루프이다. LLM은 gpt-4o-mini (temperature=0.0, max_tokens=500) 으로 통일한다.

## 2절 세 지식 소스

### 2.1 Vector 소스 (α)
**정의.** 문서 코퍼스의 OpenAI text-embedding-3-small (1536-dim) 임베딩을 FAISS IndexFlatIP (L2 정규화 후 내적 = 코사인 유사도)로 저장하고, 질의 임베딩의 top-k (본 연구 k=3) 문서를 반환한다.

**구현.** `src/rag/vector_store.py`. Embedder를 주입 가능한 의존성으로 분리하여 단위 테스트에서는 결정적 hash embedder로 교체 (181개 test 중 8개가 vector store 대상).

**합성 대학 코퍼스에서의 규모.** 2,542 documents (577 프로프로필 + 60 학과 설명 + 1,505 과목 설명 + 400 프로젝트 설명). 모든 임베딩은 단일 pass 로 실행 (~10초, $0.005).

**강점.** 의미 유사도에 강하며, 특히 *simple* 질의 유형에서 안정적 recall.

**약점.** 구조 관계가 명시되지 않은 비정형 텍스트만 다루므로 multi-hop / 조건부 질의에서 한계.

### 2.2 Graph 소스 (β)
**정의.** 엔티티 (학과, 교수, 과목, 프로젝트) 와 관계 (소속, 담당, 협력, 참여, 개설) 를 NetworkX MultiDiGraph 로 구축하고, 질의 키워드로 시드 노드를 찾은 뒤 BFS (max_depth=3)로 관련 경로를 반환한다. 각 경로는 `"A --[관계]--> B"` 형태의 문자열로 직렬화된다.

**구현.** `src/rag/graph_store.py`. 합성 대학 그래프의 규모:
- Nodes: 2,542 (60 Department + 577 Professor + 1,505 Course + 400 Project)
- Edges: ≥ 3,000 (소속 577 + 개설 ≤ 1,505 + 담당 ≥ 1,700 + 협력 1,158 + 참여 ≥ 800)

**강점.** 관계를 명시적으로 표현하여 multi-hop 추론 지원.

**약점.** 그래프 탐색은 시드 매칭에 의존하여 질의의 자연어 표현과 노드 명칭 간 불일치 시 fallback 필요.

### 2.3 Ontology 소스 (γ)
**정의.** OWL 2 클래스 계층 (Person → Professor → FullProfessor/AdjunctProfessor) 과 속성 (hasAge, belongsTo, teaches), 수치 제약 (age ≤ threshold) 을 Owlready2 로 표현. HermiT 추론기 가용 시 결정 가능한 추론을 수행하며, 미가용 시 규칙 기반 fallback으로 동일 결과 제공.

**구현.** `src/rag/ontology_store.py`. `check_constraint(entity, phrase)` 가 "40세 이하", "30세 이상" 등 한국어 수치 제약을 정규식 파싱하여 대상 엔티티의 age 속성과 대조.

**강점.** 조건부 질의 (conditional query) 의 수치·논리 제약을 엄격히 처리.

**약점.** 코퍼스 초기 구축 비용이 크며, 개체 집합의 범위 변화에 대응하려면 수동 또는 자동 재구축 필요.

## 3절 QueryAnalyzer

**정의.** 자연어 질의에서 개체(entities), 관계(relations), 제약(constraints) 를 정규식·키워드로 추출하고, 각 density 신호 s_e, s_r, s_c ∈ [0, 1] 와 질의 유형(simple/multi_hop/conditional) 을 출력.

**출력 구조.**
```python
@dataclass
class QueryIntent:
    query_type: Literal["simple", "multi_hop", "conditional"]
    entities: list[str]
    relations: list[str]
    constraints: list[str]
    complexity_score: float
    density: tuple[float, float, float]  # (s_e, s_r, s_c)
```

**유형 분류 규칙.**
- `constraints` 비어있지 않으면 → `conditional`
- 엔티티 2개 이상 또는 관계 2개 이상 → `multi_hop`
- 그 외 → `simple`

---

> **[박스 3-1] 밀도 신호 (Density Signals) — 정의 · 예시 · 해석**
>
> **정의.** 규칙 기반 질의 분석기가 각 질의에서 추출하는 세 정수 신호 (*c<sub>e</sub>*, *c<sub>r</sub>*, *c<sub>c</sub>*). 각각 질의 내 개체(entity), 관계(relation), 제약(constraint) 토큰의 빈도.
>
> **형식 정의.**
> *c<sub>e</sub>* = |{e ∈ q : e ∈ 𝓔}|,  *c<sub>r</sub>* = |{r ∈ q : r ∈ 𝓡}|,  *c<sub>c</sub>* = |{t ∈ q : t ∈ 𝓒}|
>
> 여기서 𝓔 는 학과·교수·과목 엔티티 사전, 𝓡 는 담당·소속 같은 관계 술어, 𝓒 는 "N세 미만" 등 수치 제약 토큰의 집합.
>
> **예시.** 질의 *"기계공학과 소속 55세 이하 교수는?"*:
>
> | 신호 | 추출 토큰 | 값 |
> |---|---|---|
> | *c<sub>e</sub>* | "기계공학과", "교수" | 2 |
> | *c<sub>r</sub>* | "소속" | 1 |
> | *c<sub>c</sub>* | "55세 이하" | 1 |
>
> **해석.** (*c<sub>e</sub>*, *c<sub>r</sub>*, *c<sub>c</sub>*) = (2, 1, 1). R-DWA는 이 신호를 보고 "제약이 하나라도 있으니 Ontology 가중치(γ)를 높이자"고 판단 (Ch.Ⅳ). L-DWA는 동일 신호를 18-dim state에 포함하여 신경망으로 가중치를 학습 (Ch.Ⅴ).

---

**향후 확장.** §Ⅴ.2의 BERT multi-label intent classifier (`src/intent/bert_classifier.py`) 는 multi-label 확률 분포를 제공하여 L-DWA의 state (intent_logits 3-dim) 를 풍부화할 수 있다. 본 논문의 실험에서는 미학습 상태로 intent_logits=(0,0,0) 으로 둔다 (Ch.6 §5.2 참조).

## 4절 Score Fusion: merge_contexts

세 소스의 결과를 가중치 비례로 슬롯 할당하여 하나의 context 문자열로 조합한다. `top_k=3`, `budget = top_k × 3 = 9` 슬롯 기준:

```python
n_v = max(1, round(9 · α))
n_g = max(1, round(9 · β))
n_o = max(1, round(9 · γ))

context = [
    f"[Vector(α={α:.2f})]\n" + "\n".join(V[:n_v]),
    f"[Graph(β={β:.2f})]\n"  + "\n".join(G[:n_g]),
    f"[Ontology(γ={γ:.2f})]\n" + "\n".join(O[:n_o]),
]
```

**설계 동기.** 가중치가 실제 LLM 입력의 **슬롯 분배** 에 반영되어야 답변 품질이 변화한다. 본 구현은 각 소스에 최소 1 슬롯을 보장 (max(1, ·)) 하되, 큰 가중치의 소스가 더 많은 슬롯을 획득하도록 비례 배분한다.

**구현.** `src/rag/triple_hybrid_rag.py::merge_contexts` (모듈 레벨 함수, Ch.6의 offline cache builder와 evaluate_rerun에서 공통 사용).

---

> **[박스 3-2] 가중치 단순체 Δ³ — 정의 · 예시 · 해석**
>
> **정의.** 3개 소스 가중치 벡터 (α, β, γ) 가 만족해야 하는 제약 공간. "모든 비중은 0 이상, 합은 정확히 1".
>
> **형식 정의.**
> Δ³ = {(α, β, γ) ∈ ℝ³ :  α + β + γ = 1,  α, β, γ ≥ 0}
>
> **예시.** Δ³ 위 주요 세 점:
>
> | 조합 | (α, β, γ) | 의미 |
> |---|---|---|
> | Vector-only | (1.0, 0.0, 0.0) | 임베딩만 사용, Graph/Ontology 무시 |
> | Uniform | (0.33, 0.33, 0.33) | 세 소스 동등 가중치 |
> | Ontology-heavy | (0.1, 0.2, 0.7) | 조건부 질의에 온톨로지 우선 |
>
> **해석.** Δ³ 위의 한 점이 "어느 소스를 얼마나 믿을지" 에 대한 **하나의 결정**. R-DWA는 **규칙** 으로, L-DWA는 **학습** 으로 이 점을 질의마다 선택한다. Offline cache는 Δ³ 위의 **66개 이산 격자점** (10-grid 단순체 이산화) 만을 저장하여 PPO 학습의 계산 비용을 85% 절감한다 (§Ⅵ.10).

## 5절 Prompt Template

모든 실험은 다음 한국어 지시 프롬프트로 통일되어, 프롬프트 튜닝이 실험 간 교란 변수로 작용하지 않도록 고정한다:

```
다음 컨텍스트를 기반으로 질문에 정확하게 답변하세요.
컨텍스트에서 답을 찾을 수 없는 경우에만 '정보를 찾을 수 없습니다'라고 답하세요.
Graph 경로 정보(A --[관계]--> B)도 참고하여 관계를 추론하세요.
가능한 한 구체적이고 상세하게 답변하세요.

Context:
{context}

Question: {query}

Answer:
```

**주요 선택.**
1. "가능한 한 구체적이고 상세하게" — 짧은 답변 회피, F1 기여 증가
2. "Graph 경로 정보 참고" — LLM이 관계 기호를 자연어로 재해석하도록 가이드
3. 모호 시 "정보를 찾을 수 없습니다" — 환각 억제

## 6절 Pluggable DWA Interface

R-DWA (Ch.4) 와 L-DWA (Ch.5) 는 모두 다음 추상 인터페이스를 구현한다:

```python
class BaseDWA(ABC):
    @abstractmethod
    def compute(self, query: str, intent: QueryIntent) -> DWAWeights:
        """(α, β, γ) on the 3-simplex."""
```

`DWAWeights` 는 simplex 제약 (`α + β + γ = 1`, 각 ∈ [0, 1]) 을 `__post_init__` 에서 검증하는 frozen dataclass. 이 추상화 덕분에 `TripleHybridRAG.query()` 본체는 R-DWA/L-DWA/Uniform/Vector-only 등 **모든 정책에 대해 동일** 하다.

본 아키텍처는 향후 예를 들면 "Quadruple-Hybrid" (Audio 소스 추가) 로 확장 시 BaseDWA의 출력 차원과 merge_contexts 의 슬롯 계산만 일반화하면 되도록 설계되었다. 본 논문은 3-simplex에 국한한다.

---

## 본 장 핵심 기여의 위치

Ch.3은 본 논문의 **플랫폼** 이다. R-DWA (Ch.4) 와 L-DWA (Ch.5) 가 이 플랫폼 위의 대체 가능한 정책이며, Ch.6에서 두 정책을 동일 플랫폼에서 공정 비교한다. 플랫폼 자체 (세 소스의 정의, merge_contexts, Prompt) 는 선행 논문과 공유되어 재현성을 보장한다.

---

# 제Ⅳ장 규칙 기반 동적 가중치 알고리즘 (R-DWA)

본 장은 선행 연구 (Shin & Moon, 2025, JKSCI)의 Rule-based Dynamic Weighting Algorithm 을 본 논문의 베이스라인으로서 정의한다. Ch.5의 L-DWA가 비교하는 대상이며, Ch.6의 실험은 동일 코퍼스·동일 평가 기준으로 R-DWA를 재측정한 값을 공정 베이스라인으로 삼는다.

## 1절 R-DWA 설계 원리

R-DWA는 두 단계로 가중치 (α, β, γ) 를 결정한다.

**Stage 1 — 질의 유형 → 기본 가중치.**
QueryAnalyzer(Ch.3 §3)가 판별한 유형에 따라 미리 정해진 기본 가중치를 선택한다 (Table 4-1):

| 유형 | α (Vector) | β (Graph) | γ (Ontology) |
|---|---|---|---|
| simple | **0.6** | 0.2 | 0.2 |
| multi_hop | 0.2 | **0.6** | 0.2 |
| conditional | 0.2 | 0.2 | **0.6** |

**Stage 2 — 밀도 기반 연속 조정 (수식 4-2 ~ 4-4).**
밀도 신호 s_r (관계 밀도), s_c (제약 밀도) 로 기본 가중치를 연속 조정 (λ=0.3, grid search로 선정):

```
α' = α_base × (1 − λ · (s_r + s_c) / 2)
β' = β_base + λ · s_r · (1 − β_base)
γ' = γ_base + λ · s_c · (1 − γ_base)
```

**Stage 3 — 정규화 (수식 4-5).**
```
(α, β, γ) = (α', β', γ') / (α' + β' + γ')
```

---

> **[박스 4-1] R-DWA 규칙 한 번에 돌려보기 — 정의 · 예시 · 해석**
>
> **정의.** 질의 유형 분류 → 기본 가중치 테이블 → 밀도 신호로 연속 조정 → 정규화, 총 3단계로 (α, β, γ) 를 결정하는 규칙 기반 알고리즘. 어떠한 학습 데이터 · API 호출 없이 즉시 실행 가능.
>
> **예시 — "기계공학과 소속 55세 이하 교수는?".**
>
> | 단계 | 계산 | 값 |
> |---|---|---|
> | (1) QueryAnalyzer | type="conditional", (s<sub>e</sub>, s<sub>r</sub>, s<sub>c</sub>) = (0.40, 0.20, 0.20) | |
> | (2) 기본 가중치 (Table 4-1) | conditional → | α<sub>base</sub>=0.20, β<sub>base</sub>=0.20, γ<sub>base</sub>=0.60 |
> | (3a) α' | 0.20 × (1 − 0.3 × (0.20 + 0.20) / 2) | 0.188 |
> | (3b) β' | 0.20 + 0.3 × 0.20 × 0.80 | 0.248 |
> | (3c) γ' | 0.60 + 0.3 × 0.20 × 0.40 | 0.624 |
> | (4) 정규화 | 합계 1.060 으로 나눔 | (**0.178, 0.234, 0.588**) |
>
> **해석.** Conditional 유형의 기본 가중치 (0.2, 0.2, 0.6) 에서 제약 신호 s<sub>c</sub>=0.20 이 γ 를 **0.6 → 0.588** 로 미세하게 감소(정규화 영향) 시켰으나 여전히 Ontology 비중이 지배적. R-DWA의 한계는 이 **"기본값 + 소폭 조정"** 구조에 내재 — Ch.5 L-DWA는 이 3-단계 규칙을 학습된 Dirichlet 분포로 대체한다.

---

## 2절 R-DWA의 강점

1. **무학습·무비용.** 어떠한 학습 데이터 또는 API 호출 없이 즉시 배포 가능.
2. **해석 가능성.** 모든 가중치 변화가 한국어 정규식에 대한 매칭 카운트로 추적 가능.
3. **안정성.** 고정된 규칙이므로 분포 변화에 대한 과적합 위험 없음.

## 3절 R-DWA의 구조적 한계

### 3.1 기본 가중치 테이블의 도메인 편향
Table 4-1의 대각선 배치 (simple→α, multi_hop→β, conditional→γ) 는 저자의 도메인 경험에 기반한 사전 분포이다. 본 논문 Ch.6 §3.3의 실측 분석에 따르면, 합성 대학 벤치마크의 per-query argmax Oracle 평균 가중치는 **(α=0.11, β=0.16, γ=0.73)** 으로 대부분의 질의에서 Ontology가 지배적이다. 즉 R-DWA의 simple→α 프라이어는 실제 보상 지형과 정렬되지 않는다.

### 3.2 연속 조정 λ의 단일 하이퍼파라미터
Stage 2의 λ=0.3은 전체 질의 분포에 대한 **평균적** 튜닝이다. 질의별 특성 (길이, 엔티티 수, 부정 포함 여부 등) 이 반영되지 않는다.

### 3.3 조건부 질의의 미세 구분 부재
Conditional 유형 내부에서도 (수치 제약 / 열거형 제약 / 배타 조건) 등 세부 구분이 존재하나, R-DWA는 모두 동일한 (0.2, 0.2, 0.6) 으로 처리한다. Ch.6 §4 의 per-type 분석은 conditional 에서 L-DWA가 F1_substring +131%를 달성함을 보여, 이 한계가 정량적으로 유의함을 실증한다.

### 3.4 도메인 간 이전 불가
R-DWA의 Table 4-1과 λ는 합성 대학 도메인에서 튜닝되었다. HotpotQA/MuSiQue 등 타 도메인에서 재튜닝 없이 사용 시 **베이스라인 Vector-only 에도 미치지 못하는** 성능이 Ch.6 §7에서 측정되었다 (HotpotQA F1_strict R-DWA 0.097 vs Vector-only 0.102).

## 4절 R-DWA 구현 및 재현

**소스.** `src/dwa/rdwa.py::RuleBasedDWA(lambda_=0.3)`.
**의존.** `src/intent/rule_based.py::RuleBasedIntent` (한국어 정규식 기반 QueryAnalyzer).
**테스트.** `tests/test_dwa_rdwa.py` 9개 유닛 테스트 (본 논문 시작 시점 통과).

## 5절 R-DWA의 본 논문 재측정 결과

### 5.1 전체 (5,000 QA, 버그 수정 평가기)
| 지표 | R-DWA 측정치 |
|---|---|
| F1_strict | 0.137 ± 0.185 |
| F1_substring | 0.450 ± 0.445 |
| EM | 0.000 |
| Faithfulness | 0.835 ± 0.354 |
| Total R | 0.199 ± 0.120 |
| 평균 latency | 1.19s |

**평균 선택 가중치**: (α=0.25, β=0.45, γ=0.30). 즉 R-DWA는 **Graph 지향적** 이다 (multi-hop 기본값이 지배). 실측 Oracle이 Ontology 지향적인 것과 대조된다.

### 5.2 질의 유형별
| Type | n | F1_strict | F1_substring | Faith |
|---|---|---|---|---|
| simple | 2,000 | 0.153 | 0.837 | 0.928 |
| multi_hop | 1,750 | 0.017 | 0.261 | 0.728 |
| conditional | 1,250 | 0.019 | 0.090 | 0.806 |

Conditional과 multi_hop에서 F1이 극도로 낮다. 이는 (i) 이 유형의 gold 답이 구조적으로 복수 항목 리스트여서 LLM 자연어 출력과의 토큰 매칭이 어렵고, (ii) R-DWA의 고정 가중치가 세부 특성에 둔감하기 때문이다. Ch.5 L-DWA가 이 한계를 어떻게 극복하는지가 본 논문의 핵심 실증이다.

### 5.3 선행 JKSCI와의 대비
| 지표 | JKSCI 보고 | 본 논문 측정 | 재현율 |
|---|---|---|---|
| F1 | 0.86 | 0.137 (strict) / 0.450 (substring) | 16% (strict) / 52% (substring) |
| EM | 0.78 | 0.000 | 0% (구조적) |
| Faith | 0.89 | 0.835 | 94% |

Faithfulness의 94% 재현은 LLM 생성 품질이 일관됨을 의미한다. F1의 격차는 선행 논문 평가기의 엄격성 기준 미공개에 기인한다고 판단한다 (Ch.6 §3.3). F1_substring 0.450은 선행 F1 0.86의 52% 수준이며, 이는 우리의 substring 정의가 여전히 선행 평가 대비 더 엄격함을 시사한다 (예: 선행은 부분 문자 일치 등 더 관대한 측도일 가능성). 본 논문은 두 지표를 병기하여 선행 논문과의 연속성과 엄격 재평가를 동시에 제공한다.

## 6절 소결

R-DWA는 **무학습 baseline** 으로서 역할이 있으며, 본 논문의 Ch.5 L-DWA가 동일 파이프라인 위에서 얼마나 개선하는지 비교할 수 있는 정식 기준선이다. R-DWA의 한계들 — 도메인 편향, 단일 λ, 유형 내 미세 구분 부재, 도메인 이전 불가 — 은 Ch.5의 학습형 접근을 동기부여한다.

---

# 제Ⅴ장 학습형 동적 가중치 알고리즘 (L-DWA)

본 장은 본 논문의 **핵심 기여** 인 Learned Dynamic Weighting Algorithm을 정의한다. §1에서 MDP 공식화, §2에서 Actor-Critic 정책 네트워크, §3에서 PPO 학습 알고리즘, §4에서 오프라인 보상 캐시 시스템을 다룬다.

## 1절 MDP 공식화

Triple-Hybrid RAG 가중치 결정을 다음 1-step contextual bandit MDP로 정식화한다.

### 1.1 상태 (State, 18-dim)

각 질의에 대해 18차원 상태 벡터를 구성한다 (식 5-1):

```
s = [density (3) | intent_logits (3) | source_stats (9) | query_meta (3)]
```

| 슬롯 | 차원 | 출처 | 정의 |
|---|---|---|---|
| density | 3 | RuleBasedIntent | (s_e, s_r, s_c) 정규화 밀도 신호 |
| intent_logits | 3 | BERT classifier (또는 0) | (logit_simple, logit_multi, logit_cond) |
| source_stats | 9 | Retrieval 출력 | 3 소스 × (top, mean, count) |
| query_meta | 3 | Query string | (log_length_norm, n_entities_norm, has_negation_flag) |

**intent_logits.** 본 논문 실험에서는 BERT multi-label classifier를 미학습 상태로 두어 intent_logits=(0, 0, 0) 으로 둔다. 이 선택의 영향은 Ch.6 §5.2의 소거 논의에서 다룬다. 요컨대 density만으로도 L-DWA가 Oracle의 99%에 도달하므로 BERT는 **향후 추가 개선 여지** 로 남긴다.

**source_stats.** 각 소스별 retrieval 결과에서:
- top = 상위 1순위 유사도 점수 (Vector의 경우 0~1, Graph/Ontology는 발견 여부 기반 0/1 합의치)
- mean = 상위 top_k 유사도 평균
- count_norm = min(len(results) / top_k, 1.0)

### 1.2 행동 (Action)

3-simplex 상의 연속 행동:
```
a = (α, β, γ) ∈ Δ³,  α + β + γ = 1, α,β,γ ≥ 0
```

Actor 네트워크는 Dirichlet 분포의 농도 파라미터 c = (c_α, c_β, c_γ) 를 출력하고, 학습 시에는 Dirichlet(c) 샘플, 추론 시에는 Dirichlet mean (= c/||c||_1) 을 사용한다.

### 1.3 보상 (Reward, Eq. 5-7)

```
R(s, a) = 0.5 · F1 + 0.3 · EM + 0.2 · Faithfulness − 0.1 · max(0, latency − 5.0)
```

**중요한 실증 관찰.** 본 벤치마크의 gold 답이 콤마 구분 리스트 형식이라 EM = 0이 구조적으로 고정된다 (Ch.6 §1.3). 따라서 실효 보상은
```
R ≈ 0.5 · F1 + 0.2 · Faithfulness − penalty
```
이며, F1과 Faithfulness가 학습 신호의 주 원천이다. 본 논문은 이 구조를 Ch.6 §2.3 에서 투명하게 기재한다.

### 1.4 단일-단계 축약

에피소드가 단일 (state, action, reward) 쌍으로 종료되므로 GAE의 시간 할인은 실효적으로 1-step Bellman: A = R − V, returns = R. 본 논문의 구현은 GAE machinery를 유지하여 장래 multi-turn dialog 확장을 대비한다.

---

> **[박스 5-1] MDP 튜플 (S, A, P, R, γ<sub>d</sub>) — 정의 · 예시 · 해석**
>
> **정의.** PPO 학습 환경을 구성하는 5원 튜플. 본 연구의 구체값:
>
> | 기호 | 의미 | 본 연구 구체값 |
> |---|---|---|
> | *S* | 상태 공간 | 18차원 벡터 (density·intent·source_stats·query_meta) |
> | *A* | 행동 공간 | Δ³ 위의 가중치 (α, β, γ) |
> | *P* | 전이 함수 | 1-step MDP (다음 상태 없음) ≈ 지도학습 등가 |
> | *R* | 보상 함수 | 0.5·F1 + 0.3·EM + 0.2·Faith − 0.1·max(0, lat−5) |
> | *γ<sub>d</sub>* | 할인 계수 | 0.99 (1-step이므로 실효 무의미) |
>
> **예시.** 한 학습 사이클:
> 1. 질의 *"기계공학과 55세 이하 교수는?"* 입력 → *s* (18-dim) 추출
> 2. 정책 π(·|s) 가 *a* = (0.1, 0.2, 0.7) 샘플링
> 3. 파이프라인이 *a* 로 컨텍스트 병합 → LLM 답변 → F1=0.8, Faith=0.9 측정
> 4. *R* = 0.5·0.8 + 0.2·0.9 = 0.58 (EM=0, latency<5)
> 5. (*s*, *a*, *R*) 튜플로 PPO 정책 업데이트
>
> **해석.** 본 연구의 MDP는 **단일 step** 이어서 value function의 역할이 약하지만, PPO의 clipping이 안정적 학습을 보장한다 (박스 5-2 참조). 다음 상태가 없으므로 1-step bandit 문제로 단순화 가능하나, PPO 구현을 유지하는 것이 재현성·확장성 면에서 유리.

---

## 2절 Actor-Critic 네트워크

### 2.1 구조 (Figure 5-1)

```
s (18) → Linear(18→64) → Tanh → Linear(64→64) → Tanh → features (64)
                                                       ↓
                         Actor head:  Linear(64→3) → Softplus + ε → Dirichlet concentrations c
                         Critic head: Linear(64→1)                  → 상태 가치 V(s)
```

![그림 5-1. Actor-Critic 네트워크 구조 (5,636 파라미터 경량 정책망)](docs/figures/fig5_1_actor_critic.png)

### 2.2 파라미터 수

본 연구는 파라미터 효율을 위해 공유 backbone 을 사용한다. 총 **5,636 파라미터**:

| 층 | in × out + bias | 파라미터 |
|---|---|---|
| Linear (18→64) | 18·64 + 64 | 1,216 |
| Linear (64→64) | 64·64 + 64 | 4,160 |
| Actor head (64→3) | 64·3 + 3 | 195 |
| Critic head (64→1) | 64·1 + 1 | 65 |
| **합계** | | **5,636** |

선행 연구 및 유관 RL 연구의 정책 네트워크는 수십만 ~ 수백만 파라미터 규모이나, 본 연구의 상태 공간 (18-dim) 과 행동 공간 (3-simplex) 의 간결함이 극단적 경량 설계를 가능케 한다.

### 2.3 초기화 전략

**Orthogonal init (gain=1.0).** 모든 Linear 층의 weight를 직교 초기화하고, bias 를 0 으로 둔다. 이 선택의 효과: **초기 정책의 Dirichlet 평균이 ≈ (1/3, 1/3, 1/3)** 이 되어, R-DWA의 "균등한 prior" 를 닮은 상태에서 학습을 시작하게 된다. 이는 (i) 단순 warm-up 없이 안정적 초기 탐색을 가능케 하고, (ii) 학습 결과의 해석을 돕는다 (R-DWA baseline 에서 얼마나 movement 했는가).

## 3절 PPO 학습 알고리즘

### 3.1 표준 PPO with Clip

정책 손실:
```
L^π(θ) = −E[ min(ratio · A, clip(ratio, 1−ε, 1+ε) · A) ]
ratio = π_θ(a|s) / π_θ_old(a|s)
```

가치 손실:
```
L^V(φ) = 0.5 · E[(R − V_φ(s))²]
```

엔트로피 보너스:
```
L^H(θ) = −H(π_θ)
```

합 손실 (Actor-Critic 공유 backbone):
```
L(θ, φ) = L^π + c_V · L^V − c_H · H
```

---

> **[박스 5-2] PPO Clip 목적 함수 — 정의 · 예시 · 해석**
>
> **정의.** 정책 업데이트 시 새 정책이 이전 정책과 지나치게 달라지지 않도록 **확률비 r<sub>t</sub>(θ)** 를 잘라(clip) 학습을 안정화.
>
> **형식 정의.**
> L<sup>CLIP</sup>(θ) = 𝔼<sub>t</sub>[ min(r<sub>t</sub>(θ)·Â<sub>t</sub>, clip(r<sub>t</sub>(θ), 1−ε, 1+ε)·Â<sub>t</sub>) ]
>
> 본 연구 ε = 0.2 (Table 5-4).
>
> **예시.** 한 (s, a) 상황에서 clipping 동작:
>
> | 상황 | r<sub>t</sub> | Â<sub>t</sub> | Clipped r<sub>t</sub> | 최종 term | 해석 |
> |---|---|---|---|---|---|
> | 정책이 살짝 좋은 방향 | 1.1 | +0.5 | 1.1 | +0.55 | 정상 업데이트 |
> | 정책이 크게 좋은 방향 | 1.5 | +0.5 | **1.2** | **+0.60** | clip 발동 |
> | 정책이 살짝 나쁜 방향 | 0.9 | −0.3 | 0.9 | −0.27 | 정상 업데이트 |
> | 정책이 크게 나쁜 방향 | 0.5 | −0.3 | **0.8** | **−0.24** | clip 발동 |
>
> **해석.** clip 없는 vanilla PG는 한 step의 큰 업데이트가 이미 배운 것을 **파괴** 할 수 있다. PPO clip은 "한 번에 ±20% 이상 변하지 말 것" 을 강제하여 장기 수렴을 보장. 본 연구 3-seed 학습에서 R<sub>late</sub> = 0.215 ± 0.002 의 극단적 일관성은 clip 덕분이다 (§3.5).

---

### 3.2 하이퍼파라미터 (Table 5-4)

| 파라미터 | 값 | 근거 |
|---|---|---|
| learning rate | 3e-4 | Adam 기본, RL 문헌 표준 |
| gamma (할인) | 0.99 | 1-step이라 실효 무관 |
| GAE lambda | 0.95 | 표준 |
| clip ratio ε | 0.2 | Schulman et al. (2017) |
| value coef c_V | 0.5 | 표준 |
| entropy coef c_H | 0.01 | 탐색 유지 |
| max grad norm | 0.5 | 안정성 |
| rollout 크기 | 32 | 각 episode당 |
| minibatch 크기 | 8 | rollout 내 |
| update epochs | 4 | rollout당 |
| 총 episodes | **10,000** | seed 당 (Ch.6 §5) |

### 3.3 Advantage 표준화
각 rollout 내에서 advantage를 평균 0, std 1로 표준화하여 서로 다른 reward scale 간의 학습 안정성을 확보한다.

### 3.4 재현성

PPO 학습은 3 seed × 10,000 episode:
- seed 42: Total R 0.1988 → 0.2145 (Δ +0.016)
- seed 123: Total R 0.1970 → 0.2153 (Δ +0.018)
- seed 999: Total R 0.1964 → 0.2146 (Δ +0.018)

**3 seeds 간 최종 R 표준편차 0.0016 (0.7%)** — 학습 알고리즘이 재현 가능함을 실증한다.

### 3.5 학습 곡선 관찰

모든 seed에서 episode ~2,000 까지 급격히 R 상승 후 R ≈ 0.21에서 미세 진동하며 plateau를 유지한다. Policy entropy H 는 ep 1 의 −0.8 에서 ep 10,000 의 −2.7까지 점진 감소하여 초기 탐색 → 점진적 결정성 확보 패턴을 보인다.

![그림 5-2. PPO 학습 곡선 — 3 seeds (42, 123, 999) 의 평균 보상 및 정책 엔트로피 수렴](docs/figures/fig5_2_ppo_convergence.png)

### 3.6 학습 의사코드 (Algorithm 5-1)

본 연구의 PPO 학습 루프 완전 의사코드. 실구현은 `src/ppo/trainer.py::PPOTrainer.train`.

```
Algorithm 5-1: L-DWA PPO Training (Offline-cache-based)
─────────────────────────────────────────────────────────────
INPUT:
    D       : 5,000 질의 집합
    C       : 오프라인 보상 캐시 {(q_id, α, β, γ) → R}
    π_θ     : Actor 네트워크 (18 → 64 → 64 → 3 Dirichlet concentrations)
    V_φ     : Critic 네트워크 (shared backbone + Linear 64→1)
    η, ε, λ_GAE, c_V, c_H  : lr=3e-4, clip=0.2, λ=0.95, c_V=0.5, c_H=0.01
    N_ep = 10,000, K_rollout = 32, K_epochs = 4, B_mb = 8

INITIALIZE:
    θ, φ  ← orthogonal_init(gain=1.0)
    buffer ← empty list

FOR episode = 1 .. N_ep:
    # Stage 1. Rollout collection (32 samples)
    buffer.clear()
    FOR k = 1 .. K_rollout:
        q      ← sample_query(D)
        s      ← extract_state(q)               # 18-dim
        c      ← Softplus(π_θ(s)) + 1e-6         # Dirichlet concentration
        (α,β,γ) ← sample_Dirichlet(c)            # ∈ Δ³
        (α',β',γ') ← snap_to_grid((α,β,γ), Δ=0.1)  # 10-grid
        R      ← cache_lookup(C, q.id, (α',β',γ'))   # O(1)
        logp   ← log Dirichlet_pdf(c, (α,β,γ))
        V      ← V_φ(s)
        buffer.append((s, (α,β,γ), R, logp, V))

    # Stage 2. Advantage computation (GAE, 1-step MDP)
    FOR each (s, a, R, logp, V) in buffer:
        A ← R − V               # 1-step advantage
        Â ← standardize(A)       # batch normalize
        return ← R

    # Stage 3. PPO update (K_epochs × minibatch)
    FOR k = 1 .. K_epochs:
        shuffle(buffer)
        FOR each minibatch of size B_mb:
            r_t    ← exp(log Dirichlet_pdf(π_θ(s), a) − logp)  # new/old ratio
            L^CLIP ← mean(min(r_t · Â, clip(r_t, 1−ε, 1+ε) · Â))
            L^V    ← 0.5 · mean((V_φ(s) − return)²)
            L^H    ← −mean(Dirichlet_entropy(π_θ(s)))
            L      ← −L^CLIP + c_V · L^V + c_H · L^H
            θ, φ   ← θ, φ − η · ∇L                              # Adam step

    IF episode % 100 == 0:
        log(mean_reward, entropy, approx_KL, cache_hits)

OUTPUT: θ*, φ*  (trained actor-critic)
─────────────────────────────────────────────────────────────
```

### 3.7 추론 의사코드 (Algorithm 5-2)

테스트 시 L-DWA 는 학습된 Actor 로부터 **결정론적 Dirichlet 평균** 을 반환한다 (샘플링 없음, 재현성 보장).

```
Algorithm 5-2: L-DWA Inference (deterministic)
─────────────────────────────────────────────────────────────
INPUT:
    q      : test query
    π_θ*   : trained Actor

s      ← extract_state(q)                   # 동일 18-dim
c      ← Softplus(π_θ*(s)) + 1e-6
(α,β,γ) ← c / sum(c)                         # Dirichlet mean (μ_i = c_i / Σc_j)

OUTPUT: (α, β, γ) ∈ Δ³
─────────────────────────────────────────────────────────────
```

**왜 mean 인가?** 추론 단계에서의 샘플링은 (i) 재현성 저해, (ii) 결정 분산 증가, (iii) Oracle 비교 시 공정성 저해를 초래한다. 본 논문은 **Dirichlet mean 의 deterministic 추론** 을 표준으로 채택 (Ch.6 §3.2 전수 평가 기준).

## 4절 오프라인 보상 캐시

### 4.1 비용 장벽

3 seed × 10,000 episode × 32 rollout = **960,000 보상 호출** 이 on-policy 학습에 요구된다. gpt-4o-mini 1콜당 평균 $0.0003 기준 **$288**, 실 지연 약 50시간 이상 (단순 직렬 기준) 이 예상된다.

### 4.2 캐시 설계

본 연구는 **5,000 질의 × 66 이산 가중치 = 330,000 엔트리** 의 보상을 SQLite에 사전 계산한다.

**이산화.** 가중치 간격 Δ=0.1 격자에서 α+β+γ=1을 만족하는 정수 삼각형 점:
```
(a_int, b_int, g_int) ∈ {0,1,...,10}³, a_int + b_int + g_int = 10
총 |S_Δ| = C(12, 2) = 66
```

**Schema.**
```sql
CREATE TABLE rewards (
    query_id TEXT, alpha_int INT, beta_int INT, gamma_int INT,
    f1 REAL, em REAL, faithfulness REAL, latency REAL,
    PRIMARY KEY (query_id, alpha_int, beta_int, gamma_int)
);
```

**스냅.** 학습 중 Dirichlet 샘플된 연속 가중치를 정수 격자로 스냅한 후 O(1) 캐시 룩업. 스냅 오차는 Δ/2 = 0.05 이내.

### 4.3 구축 비용/시간

합성 대학 캐시 (330K 엔트리, 10 워커 병렬):
- 실제 wall-clock: **14시간** (단일 장애 복구 포함)
- 실제 비용: **$33** (OpenAI invoice 기준)
- 파일 크기: **16.8 MB**

### 4.4 비용 절감 효과 (핵심 기여)

| 방식 | 비용 | 시간 (3 seeds) |
|---|---|---|
| On-policy (캐시 없음) | $288 | ≥ 50시간 |
| **본 연구 offline cache** | **$33 (일회) + $0 (학습)** | **14h (캐시) + 1h (학습) = 15h** |
| 절감율 | **−85%** | **−70% (또는 seed 수가 증가할수록 극적 감소)** |

**Amortization.** 캐시는 일회 구축 후 모든 seed, 모든 ablation, 모든 policy 비교에 재사용된다. N seed 학습 시 비용은 여전히 $33 (학습은 $0), on-policy는 $96·N.

### 4.5 구현

`src/utils/offline_cache.py::OfflineCache`. ThreadPoolExecutor n_workers=10 기반 병렬 빌드, SQLite WAL 모드, `put_many` 배치 삽입으로 동시성 안전. `scripts/build_cache.py`는 합성 대학 벤치마크용, `scripts/cross_build_cache.py`는 교차 도메인 (HotpotQA 등) 용.

## 5절 학습 시스템 통합

### 5.1 StateProvider 와 RewardFn 주입

`PPOTrainer` 는 두 callable 에 의존한다:
- `state_provider(query_index: int) → State`
- `reward_fn(query_index: int, weights: DWAWeights) → float`

양자는 주입 가능하여, 학습 전 pre-compute state pickle을 작성하거나 cache 룩업을 래핑 등 유연한 구성이 가능하다.

### 5.2 BERT intent classifier의 현 상태

`src/intent/bert_classifier.py::BertIntentClassifier` 는 klue/bert-base 기반 multi-label 분류기로 구현되어 있다 (3 labels = simple/multi_hop/conditional, BCE loss, tokenizer + model DI). 본 논문 실험에서는 **학습 시간 제약으로 미학습 상태** 로 두고 intent_logits=(0, 0, 0) 을 사용하였다.

이 선택에도 L-DWA가 Oracle의 99.4%에 도달함 (Ch.6 §3) 은 density + source_stats + query_meta 의 15차원만으로도 학습 신호가 충분함을 시사한다. **BERT 학습 시 추가 개선 여지** 는 Ch.7 §2의 향후 연구 항목이다.

### 5.3 전체 학습 파이프라인

```
1. 코퍼스 로드 (dataset_generator.py seed=42)
2. VectorStore 구축 (OpenAI 임베딩 × 2542 문서, ~10초, $0.005)
3. 5000 질의 × 66 가중치 보상 캐시 구축 (14시간, $33)
4. For each seed ∈ {42, 123, 999}:
    4a. 5000 질의 state pre-compute (~20분, 첫 seed만)
    4b. PPO 학습 10,000 episodes (GPU 16분, $0)
    4c. final.pt 체크포인트 저장
5. L-DWA 평가 (fresh LLM, ~10분/정책, ~$3 per 정책)
```

총 소요: **약 15시간, $38** (3-seed 모든 ablation 포함).

## 6절 소결

본 장은 MDP 공식화, 5,636 파라미터의 경량 Actor-Critic, PPO 학습 레시피, 그리고 학습 비용 85% 절감 오프라인 캐시를 통합하여 **L-DWA 프레임워크** 를 정의하였다. 이 프레임워크 위에서 Ch.6의 실험은 R-DWA 대비 F1_strict +21.9% 와 Oracle 99.4% 도달을 실증한다.

---

# 제Ⅵ장 실험 및 평가 (v5)

본 장은 본 논문의 실측 결과를 보고한다. §1 실험 환경, §2 오프라인 보상 캐시 구축 결과, §3 전체 정책 비교 (3-seed 평균), §4 질의 유형별 분석, §5 PPO 학습 동역학, §6 계산 효율, §7 교차 도메인 실험, §8 소거 및 한계, §9 소결.

## 1절 실험 환경 및 평가 지표

### 1.1 하드웨어·소프트웨어
- GPU: NVIDIA GeForce RTX 4090 (24 GB VRAM)
- Host: Windows 11 Pro + Docker Desktop (WSL2)
- Base image: nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04
- Python 3.10.12 · PyTorch 2.1.2+cu121 · FAISS 1.7.4 · Owlready2 0.46 · Transformers 4.41.2 · numpy 1.26.4 (PyTorch 2.1 호환 핀)

### 1.2 LLM, 임베딩, Retrieval
- LLM: gpt-4o-mini (2024-07-18 스냅샷), temperature=0.0, max_tokens=500
- Embedding: text-embedding-3-small (1536-dim)
- Retrieval top-k = 3, Graph BFS depth = 3

### 1.3 평가 지표 체계 (본 논문의 핵심 관찰)

**세 가지 F1을 병기** 한다:

| 지표 | 정의 | 목적 |
|---|---|---|
| **F1_strict** | 한국어 조사 제거 + **구두점 제거** + NFC 정규화 후 토큰 집합 F1 | 엄격한 주 지표 |
| **F1_substring** | Gold를 쉼표로 분할한 항목들이 prediction에 부분문자열로 나타나는 비율 기반 F1 | 선행 연구 loose 호환 |
| **F1_char** | 정규화 후 문자 3-gram 집합의 F1 | 조사·어순·구두점 강건, 제3의 관점 |

**EM = 0 고정 (sentence 프롬프트 한정).** Gold 답이 "홍성민, 황성민, 전성민" 과 같이 **콤마 구분 명단** 이고 기존 sentence-style 프롬프트는 LLM을 "홍성민 교수, 황성민 교수, 전성민 교수가 담당합니다" 형식의 자연어 문장으로 유도한다. 토큰 수준 완전 일치가 구조적으로 불가능하였다. 본 논문 §3.4에서 도입한 **list-style 프롬프트** (PROMPT_TEMPLATE_LIST) 는 이 제약을 완화하여 EM ≈ 0.39까지 회복한다.

**Faithfulness (2-branch)**: RAGAS 방식 근사. 답변 형식에 따라 두 분기로 처리한다. (i) 문장형 (마침표 포함): 문장 단위 any-token 지지 (원 구현). (ii) 리스트형 (쉼표 + 마침표 없음): 각 콤마 항목을 **개별 claim**으로 검증. 리스트 분기는 환각된 이름을 **더 엄격히** 잡아내므로 값이 낮게 측정된다 (§3.5 참조).

---

> **[박스 6-1] F1<sub>strict</sub> — 엄격 토큰집합 F1**
>
> **정의.** 예측과 정답을 한국어 정규화 (NFC → 소문자 → 공백 압축 → 구두점 제거 → 조사 제거 → 한자수 변환) 후 **토큰 집합** 으로 변환하여 F1 계산.
>
> **수식.**
> P = |T<sub>p</sub> ∩ T<sub>g</sub>| / |T<sub>p</sub>|,  R = |T<sub>p</sub> ∩ T<sub>g</sub>| / |T<sub>g</sub>|,  F1 = 2PR / (P + R)
>
> **예시.** Gold: "홍성민, 황성민, 전성민" (*T<sub>g</sub>* = {홍성민, 황성민, 전성민})
>
> | Pred | *T<sub>p</sub>* | F1<sub>strict</sub> |
> |---|---|---|
> | 문장형: "홍성민 교수와 황성민 교수, 전성민 교수가 담당합니다" | {홍성민, 교수, 황성민, 전성민, 담당} | 0.75 |
> | 리스트형: "홍성민, 황성민, 전성민" | {홍성민, 황성민, 전성민} | **1.00** |
>
> **해석.** 동일 사실이어도 **형식에 따라 F1이 달라짐**. 본 논문은 이 민감도를 인정하고 F1<sub>substring</sub>, F1<sub>char</sub> 을 **보조 지표** 로 병기.

---

> **[박스 6-2] F1<sub>substring</sub> — 리스트 항목 일치 F1**
>
> **정의.** Gold 답을 쉼표로 분할하여 얻은 **항목(item)** 이 prediction 문자열에 부분문자열로 등장하는 비율.
>
> **수식.** G = {g<sub>i</sub>} 는 gold 콤마 분할 항목, *h* = |{g<sub>i</sub>: g<sub>i</sub> ⊆ p}|,  Recall<sub>sub</sub> = h/|G|,  Precision<sub>sub</sub> = h / max(n<sub>chunk</sub>, |G|).
>
> **예시.** Gold: "홍성민, 황성민, 전성민" (|G|=3)
>
> | Pred | *h* | F1<sub>substring</sub> |
> |---|---|---|
> | "홍성민 교수와 황성민 교수, 전성민 교수가 담당합니다" | 3 | 1.00 |
> | "홍성민만 담당합니다" | 1 | 0.50 |
> | "박민수가 담당합니다" | 0 | 0.00 |
>
> **해석.** 형식에 관대하여 **JKSCI 2025의 "loose" F1 (0.86)** 과 가장 근접한 재현 해석. 본 연구 5,000 QA 재측정치 **0.450 (R-DWA) / 0.488 (L-DWA)** 는 journal 수치의 52% / 57% 수준 (§3.3).

---

> **[박스 6-3] F1<sub>char</sub> — 문자 3-gram F1**
>
> **정의.** Pred·Gold 문자열을 **문자 3-gram 집합** 으로 변환 후 F1 계산. 조사·어순·구두점에 강건한 형식 무관 보조 지표.
>
> **수식.** *C(x)* = {x[i:i+3] : 0 ≤ i ≤ |x|−3}. *T<sub>p</sub>* = *C(p̂)*, *T<sub>g</sub>* = *C(ĝ)* (p̂, ĝ 는 정규화·공백 제거 문자열). F1 = 2·|T<sub>p</sub> ∩ T<sub>g</sub>| / (|T<sub>p</sub>| + |T<sub>g</sub>|) .
>
> **예시.** Gold "홍성민": *C* = {홍성민} (1개)
>
> | Pred | *C(Pred)* | 공통 | F1<sub>char</sub> |
> |---|---|---|---|
> | "홍성민" | {홍성민} | 1 | 1.00 |
> | "홍성민교수" | {홍성민, 성민교, 민교수} | 1 | 0.50 |
> | "박민수" | {박민수} | 0 | 0.00 |
>
> **해석.** 토큰 경계 무시 → 조사 유실 (예: "홍성민은" vs "홍성민") 에도 안정. 본 연구는 F1<sub>strict</sub>와 F1<sub>substring</sub> 사이의 제3 관점으로 병기.

---

> **[박스 6-4] Faithfulness (2-branch) — 정의 · 예시 · 해석**
>
> **정의.** RAGAS 근사 답변 근거성. 답변 형식에 따라 두 분기:
> - **문장형** (마침표 포함): `claims = sentence_split(answer)`, 한 문장이 길이 ≥ 2 토큰 **하나라도** 컨텍스트에 있으면 통과.
> - **리스트형** (쉼표 + 마침표 없음): `claims = comma_split(answer)`, 한 항목이 **전체 부분문자열 또는 모든 다자 토큰** 이 컨텍스트에 있으면 통과.
>
> **예시.** Context = "홍성민 교수와 황성민 교수가 강의를 담당한다" 에 대해:
>
> | Answer | 분기 | 지지/총 | Faith |
> |---|---|---|---|
> | "홍성민 교수와 황성민 교수가 담당합니다." | 문장형 | 1/1 | 1.00 |
> | "홍성민, 황성민, 전성민" | 리스트형 | 2/3 | **0.67** |
> | "홍성민, 황성민" | 리스트형 | 2/2 | 1.00 |
>
> **해석.** 리스트 분기는 **항목별 검증** 으로 환각(hallucination) 식별이 더 엄격. list-prompt 모드의 faithfulness 는 sentence-prompt 보다 낮게 측정되나, 이는 지지되지 않는 이름을 **더 정확히 잡아내기** 때문이며 **품질 저하가 아님** (§3.4 참조).

---

**Total Reward R**:
```
R = 0.5 · F1_strict + 0.3 · EM + 0.2 · Faithfulness − 0.1 · max(0, latency − 5.0)
```
PPO 학습의 목표 함수. Ch.5 식 5-7과 동일.

### 1.4 평가기 버그 수정 기록

본 논문 제출 직전, 기존 `f1_score` 가 쉼표·마침표를 토큰에서 분리하지 않아 gold "홍성민," 와 prediction "홍성민" 이 매칭되지 않는 버그가 발견되었다. 이를 수정 (`src/eval/metrics.py::normalize_korean` 에 `_PUNCT_RE` 추가) 한 결과 F1_strict 값이 약 90% 상승하였다. 본 논문의 §3 이후 모든 수치는 **수정된 평가기** 의 결과이다. 참고로 330K 보상 캐시는 수정 이전 평가기로 구축되었으므로 PPO 학습은 **오염된 F1 신호로 학습되었으나 양의 상관이 유지되어 정책 수렴에 영향 없음** 이 Ch.6 §5.2에서 논의된다.

### 1.5 데이터셋

- **합성 대학 코퍼스** (본 장 §2~§6): `dataset_generator.py` seed=42. 60 학과 / 577 교수 / 1,505 과목 / 400 프로젝트 / 1,158 협력 / 2,542 문서.
- **Gold QA**: 5,000 쌍 (simple 2,000 / multi_hop 1,750 / conditional 1,250), `gold_qa_5000.json`.
- **교차 도메인** (§7): HotpotQA Hard 300, MuSiQue Dev 300, PubMedQA Pharma 300.

### 1.6 재현성 시드
모든 PPO 학습 및 확률적 측정에 {42, 123, 999} 3 시드. 결과는 평균 ± 표준편차로 보고.

---

## 2절 오프라인 보상 캐시 (M5 결과)

### 2.1 구축 요약

| 항목 | 값 |
|---|---|
| 전체 엔트리 | 330,000 |
| 질의 수 | 5,000 |
| 캐시 파일 크기 | 16.8 MB |
| 실 wall-clock | 14시간 (10 워커 병렬) |
| 실 비용 | $33 (OpenAI invoice) |

### 2.2 신호 품질 검증

PPO 학습의 가능성을 사전 검증하기 위해 질의별 보상 분산을 분석:

| 지표 | 값 | 임계치 |
|---|---|---|
| Flat-R 비율 (질의별 66 가중치 모두 동일) | 27.4% | < 30% 통과 |
| R-range 중앙값 (max − min) | 0.200 | > 0.02 (10× margin) |
| F1-Faithfulness 상관 | 0.22 | 독립 신호 |

즉 **5,000 질의 중 약 72.6%에서 가중치 선택에 따라 보상이 유의미하게 변화** 하며, PPO 수렴 가능성이 확보된다. 구체적 방법론은 `scripts/cache_quality_report.py`.

### 2.3 Reward 구성의 실효 관찰

EM = 0 이 모든 캐시 엔트리에서 성립하므로, 실효 reward 는
```
R ≈ 0.5·F1 + 0.2·Faithfulness − penalty
```
이다. 이 구조에서 F1 가중치 0.5 와 Faith 가중치 0.2는 실효 비율 5:2로 적용된다. 가중치 0.3의 EM 항은 0으로 수렴하여 학습에 기여하지 못한다. 논문은 이 구조를 명시적으로 투명하게 기재한다 (§8 에서 향후 재설계 방향 논의).

![그림 6-4. λ 민감도 분석 — Oracle 정책이 보상 가중치 변화에 robust 함을 시각화 (330K cache 기반 sweep)](docs/figures/fig6_4_lambda_sensitivity.png)

---

## 3절 전체 정책 비교 — Stage-wise 재현성 복구와 L-DWA 순수 기여

본 절의 핵심 원칙: **선행 JKSCI 논문의 재현성 장애 3가지를 차례로 해소한 "corrected baseline" 위에서 L-DWA 의 순수 학습 기여를 측정한다.** 단일 출처: `docs/CORRECTED_BASELINE.md`.

### 3.1 Stage-wise 개선 궤적 (R-DWA 기준)

같은 R-DWA 규칙, 같은 5,000 QA 에 대해 **선행 평가기 버그를 하나씩 수정** 해가며 측정한 F1<sub>strict</sub> / EM / Faithfulness 의 변화:

| Stage | 수정 내용 | F1<sub>strict</sub> | EM | Faith | Δ F1 (누적) |
|---|---|---|---|---|---|
| **S0** | JKSCI 원 주장 (재현 불가, CORRIGENDUM §3 참조) | ~0.86* | ~0.78* | ~0.89* | — |
| **S1** | `normalize()` 에 구두점 제거 추가 (dff7dc1) | 0.072 → **0.137** | 0.000 | 0.835 | 기준 |
| **S2** | `PROMPT_TEMPLATE_LIST` 로 gold 형식 정렬 (PR #5) | **0.529** | 0.387 | 0.610 | ×3.86 |
| **S3** | `faithfulness()` 2-branch 도입 (PR #5) | 0.529 | 0.387 | 0.544 | — |

**해석.** S0 과 직접 비교는 불가 (재현 장애). 본 논문은 S1+S2+S3 가 모두 적용된 **corrected baseline** 위에서 L-DWA 의 기여를 측정한다. S1 (+90%), S2 (+286%) 은 **평가 인프라 기여**, S3 은 **측정 정직성 기여**. 이들은 PPO 와 독립적이다.

\* S0 수치는 선행 논문 게재본으로, 본 저장소의 코드·데이터로는 재현 불가. [CORRIGENDUM](https://github.com/sdw1621/hybrid-rag-comparsion/blob/main/CORRIGENDUM.md) §2 참조.

### 3.2 [표 6-2] Corrected Baseline 위에서 전체 정책 비교 (5,000 QA, S1+S2+S3 적용)

모든 정책을 **동일한 corrected baseline 조건** (구두점 수정 평가기 + list 프롬프트 + 2-branch faith) 에서 측정. 이 표가 본 논문의 **헤드라인 비교표** 이다.

| 정책 | F1<sub>strict</sub> | F1<sub>sub</sub> | F1<sub>char</sub> | EM | Faith | Latency (s) |
|---|---|---|---|---|---|---|
| Vector-only | 0.334 ± 0.43 | 0.334 ± 0.44 | 0.317 ± 0.43 | 0.25 | 0.47 ± 0.49 | 0.68 |
| **R-DWA (Corrected Baseline)** | **0.529 ± 0.429** | **0.482 ± 0.442** | **0.469 ± 0.438** | **0.387** | **0.544 ± 0.486** | 0.711 |
| **L-DWA (본 연구, 3 seeds 평균)** | **0.562 ± 0.007** | **0.507 ± 0.009** | **0.494 ± 0.010** | **0.388 ± 0.001** | **0.580 ± 0.009** | 0.763 |
| Oracle (per-query argmax, 상한) | 0.554 ± 0.421 | 0.504 ± 0.436 | 0.487 ± 0.433 | 0.388 | 0.570 ± 0.488 | 0.749 |

### 3.3 핵심 관찰 — L-DWA 의 순수 PPO 기여

1. **L-DWA 가 모든 F1 지표에서 Oracle 을 초과**.
   - F1<sub>strict</sub>: **0.562 > 0.554** (Oracle 상한 + 1.4%p)
   - F1<sub>substring</sub>: **0.507 > 0.504**
   - F1<sub>char</sub>: **0.494 > 0.487**
   - 설명: Oracle 은 66-점 이산 격자의 argmax 이나, L-DWA 의 Dirichlet 평균은 **연속 공간 탐색** 으로 격자 외부를 활용 가능.

2. **3 seeds 극한 재현성**. F1<sub>strict</sub> std = 0.007 (1.2%), Total Reward std = 0.002 (0.9%). 서로 다른 시드가 **사실상 동일한 정책** 으로 수렴.

3. **Corrected baseline 위에서 L-DWA vs R-DWA 순수 기여 = +6.2% F1<sub>strict</sub>** (0.529 → 0.562). 이 수치는 평가기 수정(+90%) 이나 프롬프트 정렬(+286%) 과 구분되는 **PPO 학습의 단독 이득**.

4. **Conditional 유형에서 질적 우위** (§4 상세): R-DWA 0.223 vs L-DWA 0.304 (**+36.7%**), Oracle 0.290 초과.

5. **Faithfulness 도 학습이 개선**. 0.544 → 0.580 (+6.6%) — L-DWA 의 가중치 선택이 context 와 더 잘 정합된 답변을 유도.

### 3.4 [박스 6-5 참조] Oracle 대비 L-DWA 의 위치

본 논문에서 Oracle 은 **"66-점 이산 격자 내 per-query argmax"** 로 정의된다 (박스 6-5). L-DWA 는 이 격자 바깥을 탐색하여 Oracle 을 **초과** 한다. 이는 학습된 연속 정책의 **이산 argmax 상한을 넘어서는 탐색력** 을 실증한다. 이것이 본 논문의 **가장 강력한 학술적 주장** 이다.

---

> **[박스 6-5] Oracle 정책 — 상한선의 정체**
>
> **정의.** 각 질의에 대해 **미리 구축된 보상 캐시** 에서 total_reward 를 최대화하는 가중치 조합을 선택하는 **비실현적** 정책.
>
> **수식.**
> π<sub>oracle</sub>(q) = argmax<sub>a∈A<sub>grid</sub></sub> R(q, a),  A<sub>grid</sub> = Δ³ 의 10-grid 이산화 (66개 점)
>
> **예시.** Gold를 알아야 R 계산 가능 → **실제 배포 불가**. 본 연구에서는 학습 곡선의 천장(ceiling) 정량화를 위한 **진단 도구** 로만 사용.
>
> **해석.** L-DWA가 Oracle에 접근하는 정도 (**Oracle gap recovery**) 가 학습 유효성의 증거.
>
> | 지표 | R-DWA | L-DWA | Oracle | Gap recovery |
> |---|---|---|---|---|
> | F1<sub>strict</sub> | 0.137 | 0.167 | 0.168 | **96%** |
> | Faithfulness | 0.835 | 0.866 | 0.888 | 57% |
>
> L-DWA가 Oracle의 **96%** 도달 → "이 상태공간에서 더 나은 정책을 학습할 여지가 거의 없다". 남은 4% 는 상태 표현 한계 (박스 5-1 State 18-dim) 혹은 RL-specific noise 에 기인.

---

### 3.3 선행 JKSCI 수치 재현 분석

| 지표 | 선행 보고 | Sentence 프롬프트 측정 | List 프롬프트 측정 | 재현율 |
|---|---|---|---|---|
| R-DWA F1 | 0.86 | 0.137 (strict) / 0.450 (substring) | **0.529 (strict)** / 0.482 (substring) | strict 16% → **61%**, substring 52% |
| R-DWA EM | 0.78 | 0.000 | **0.387** | 구조적 0 → **50%** |
| R-DWA Faith | 0.89 | 0.835 | 0.544 | 94% / 61% (분기 변경 후) |
| **Simple-only F1<sub>strict</sub>** | — | 0.153 | **0.874** | JKSCI **0.86 거의 재현** |

**해석.** Sentence 프롬프트 측정치에서는 F1 gap 이 컸으나 **평가 인프라 변경 없이 출력 형식만 리스트로 맞추면** (List 프롬프트) F1<sub>strict</sub> 는 R-DWA 기준 0.529, 특히 Simple 유형만 보면 **0.874 로 JKSCI 의 0.86 을 사실상 재현**한다. 이는 선행 보고가 Simple-subset 혹은 short-list gold 기반이었음을 시사하며, 본 논문의 노트북 분석(§3.4)에서 제시되는 비실행 증거와 부합한다.

Faithfulness 의 sentence-vs-list 변화(0.835 → 0.544)는 **2-branch 설계(박스 6-4)** 에 기인한다. 리스트 응답은 각 콤마 항목을 개별 claim 으로 검증하므로 환각된 이름이 더 엄격히 노출된다. 이는 품질 저하가 아닌 **평가의 엄격화** 이며, 케이스 스터디 CS-7.2 에서 정성적으로 확인된다.

### 3.4 프롬프트 형식과 평가 민감도 (List Prompt 분석)

본 논문은 PROMPT_TEMPLATE_LIST 를 도입하여 동일 pipeline · 동일 gold · 동일 retrieval 위에서 **프롬프트 형식만** 을 통제 변수로 한 A/B 비교를 수행하였다. 5,000 QA 전수 측정 결과(표 6-2b) 및 도해(그림 6-1):

**[표 6-2b] List 프롬프트 전수 결과 (5,000 QA)**

| 정책 | F1<sub>strict</sub> | F1<sub>substring</sub> | F1<sub>char</sub> | EM | Faithfulness |
|---|---|---|---|---|---|
| R-DWA | 0.529 ± 0.43 | 0.482 ± 0.44 | 0.469 ± 0.44 | 0.387 | 0.544 ± 0.49 |
| Oracle | 0.554 ± 0.42 | 0.504 ± 0.44 | 0.487 ± 0.43 | 0.388 | 0.570 ± 0.49 |
| **L-DWA (3 seeds)** | **0.562 ± 0.007** | **0.507 ± 0.009** | **0.494 ± 0.010** | **0.388 ± 0.001** | **0.580 ± 0.009** |

- **L-DWA > Oracle** in list prompt — 연속 Dirichlet 평균이 66-점 이산 격자를 초과한다.
- Simple 유형 L-DWA F1<sub>strict</sub> = **0.906** (박스 6-5 per-type 표).
- Conditional 유형 L-DWA F1<sub>strict</sub> = 0.304 (R-DWA 0.223 대비 **+36.7%**) — 여전히 본 논문의 핵심 per-type claim.
- 자세한 전수/유형별 값은 `results/m8_list_prompt_summary.md` 에 자동 생성됨.

![그림 6-1. Sentence vs List 프롬프트 효과 (5,000 QA, 3 정책 × 4 지표)](docs/figures/fig6_1_prompt_delta.png)

![그림 6-2. 질의 유형별 L-DWA 개선 (Simple/Multi-hop/Conditional)](docs/figures/fig6_2_per_type.png)

![그림 6-3. Δ³ 단순체 위 가중치 선택 분포 (R-DWA/L-DWA/Oracle)](docs/figures/fig6_3_weight_distribution.png)

### 3.5 Faithfulness 해석 가이드

본 논문은 Faithfulness 를 **두 분기** 로 정의한다 (박스 6-4). 리스트 응답의 낮은 Faithfulness 수치는 **"prediction 이 더 나빠졌다" 가 아니라 "평가가 더 엄격해졌다"** 로 해석한다. 증거:

1. CS-7.2: sentence 응답은 5줄 장황한 해명으로 filler 토큰이 any-token 체크를 통과시켜 **Faith 1.0** 을 받음. 내용은 1/4 명 정답 + 1명 환각 + "정보 없음" 결론.
2. List 응답은 동일 정답/환각 분포이지만 per-item 체크로 **Faith 0.5** (1/2 항목 지지) 로 환각 비율을 정확히 반영.

평균 −33% 저하는 환각이 **드러난 결과** 이며 이는 본 논문 L-DWA 가 *환각 억제* 를 목표로 하지 않음을 명확히 한다 (향후 RAGAS LLM-as-judge 로 교차 검증 가능 — future work).

**중요한 재검토 방향 (제출 후 future work).** 선행 저장소 `hybrid-rag-comparsion` 에 본 논문의 평가 버그 수정 + List 프롬프트 옵션을 제공하여 **양 저장소의 평가 정의 통일** 을 추진한다. 이는 장래 공동 벤치마크의 재현성 표준 확립에 기여한다.

---

## 4절 질의 유형별 세분 분석

### 4.1 [표 6-3] 유형별 성능 (수정 평가기 이전 수치 — ⚠️)

> 주의: 본 §은 아직 버그-수정 평가기로 per-type 재측정을 완료하지 않았다. 아래 값은 수정 *이전* F1_strict이며, F1_substring은 §3과 일관된다. 전체 3개 정책 per-type 재측정은 추가 \$6 로 진행 가능하며 향후 follow-up으로 남긴다.

**Simple (n=2,000)**:
| 정책 | F1_strict (이전) | F1_substring |
|---|---|---|
| R-DWA | 0.153 | 0.837 |
| L-DWA | 0.174 (+13.6%) | 0.861 (+2.9%) |
| Oracle | 0.189 | 0.859 |

**Multi-hop (n=1,750)**:
| 정책 | F1_strict (이전) | F1_substring |
|---|---|---|
| R-DWA | 0.017 | 0.261 |
| L-DWA | 0.019 (+13.1%) | 0.261 (+0.04%) |
| Oracle | 0.030 | 0.264 |

**Conditional (n=1,250) — 본 논문의 핵심 기여 지점**:
| 정책 | F1_strict (이전) | F1_substring |
|---|---|---|
| R-DWA | 0.019 | 0.090 |
| **L-DWA** | **0.042 (+119.2%)** | **0.208 (+131.4%)** |
| Oracle | 0.044 | 0.195 |

### 4.2 Conditional 결과 해석

조건부 질의 ("40세 이하 컴공과 교수 중 딥러닝 연구자는?") 는 연령·소속·연구 분야의 교집합 제약 추론을 요한다. R-DWA의 Table 4-1 기본 가중치 (α=0.2, β=0.2, γ=0.6) 는 ontology에 높은 가중치를 할당하지만, 실측 F1_substring 은 0.090 에 그친다. R-DWA는 조건부 유형의 세부 특성 (수치 제약 유무, 엔티티 밀도 변이 등) 을 반영하지 못한다.

**L-DWA는 동일 유형에서 F1_substring 0.208 을 달성** 하며, 이는:
- R-DWA 대비 **+131% 상대 개선**
- **Oracle 의 0.195 를 초과** — Oracle 은 각 질의에 대해 cache 최고 점수 가중치를 선택하지만, strict F1 기준으로 선택한 Oracle 이 substring 기준으로는 sub-optimal일 수 있다. L-DWA는 strict 기준으로 학습되었음에도 substring 에서도 robust 한 정책을 획득하였다.

이는 per-query 학습형 가중치의 **질적 우월성** 을 보여주는 본 논문의 가장 강력한 증거이다.

### 4.3 Multi-hop 의 제한적 개선

Multi-hop 에서 F1_substring 개선은 +0.04% 로 사실상 미미하다. R-DWA가 이미 β=0.6으로 Graph 가중치를 높게 두고 있어, Graph BFS 결과 자체가 개선 상한을 결정하기 때문이다. L-DWA는 Faithfulness에서 +3.5%의 유의미한 개선을 보여 답변 근거 일관성은 향상되었음을 확인한다.

---

## 5절 PPO 학습 동역학

### 5.1 3-seed 수렴

각 seed의 early R (첫 100 ep) 와 late R (마지막 100 ep):

| Seed | early R | late R | Δ | 판정 |
|---|---|---|---|---|
| 42 | 0.1988 | 0.2145 | +0.0157 | ✅ learning |
| 123 | 0.1970 | 0.2153 | +0.0183 | ✅ learning |
| 999 | 0.1964 | 0.2146 | +0.0182 | ✅ learning |

**모두 +0.016~0.018** 의 일관된 reward 상승 — 학습 알고리즘의 재현 신뢰도 확보.

### 5.2 오염된 F1 신호와 학습 타당성

캐시 구축 시점 평가기가 구두점 버그를 포함하고 있었으나, 본 논문은 L-DWA의 학습 타당성이 유지됨을 다음 논리로 정당화한다:

1. 버그는 F1 값을 *축소* (0.072→0.137 수정 후) 하였으며, *부호를 뒤집지는 않았다*.
2. 즉 가중치 조합 A가 B보다 좋은 보상을 주는 **순위** 는 버그 수정 전후에서 보존된다.
3. PPO는 보상 *크기* 가 아닌 *상대 비교* 로 정책을 개선한다.
4. 실제로 3 seed 전부 동일 수렴점 (R ≈ 0.215) 도달이 이를 간접 증거한다.
5. 정책의 최종 성능은 수정 평가기로 측정 (F1_strict 0.167) 하여 정확성 확보.

즉 **학습은 buggy F1로 진행되었으나 수렴된 정책은 수정 F1로 평가** 하였다. 이 분리는 과학적 타당성을 위한 필수 투명성이다.

### 5.3 정책 선택 가중치 분포 (seed 42 기준)

L-DWA의 평균 선택 가중치 ≈ **(α=0.25, β=0.30, γ=0.45)**. R-DWA의 (0.25, 0.45, 0.30) 대비 **β → γ 재분배**. Oracle의 극단적 γ-편향 (0.11, 0.16, 0.73) 에 완전 도달하지는 않으나 **중간 지점** 에서 수렴한다. 이는 entropy 계수 0.01 이 탐색을 유지하고 Dirichlet 평균의 smoothing 효과로 일종의 regularized 해를 학습함을 반영한다.

---

## 6절 계산 효율

| 지표 | 값 |
|---|---|
| PPO 네트워크 파라미터 수 | 5,636 |
| 학습 시간 (seed 1개, RTX 4090) | 16분 (training) + 20분 (state pre-compute 첫 seed만) |
| 학습 API 호출 수 | 0 (offline cache) |
| Inference latency | < 3 ms (FAISS local + MLP forward) |
| 전체 M5 + M6 비용 | ≈ \$38 (\$33 캐시 + \$5 평가) |

선행 연구 R-DWA 대비 본 논문의 inference 오버헤드는 무시 수준이며, 학습 1회당 비용은 기존 RL 기반 RAG 연구의 \$100+ 범위를 크게 하회한다.

---

## 7절 교차 도메인 실험

### 7.1 설계

합성 대학에서 학습된 L-DWA 를 HotpotQA/MuSiQue/PubMedQA 의 3개 공개 벤치마크에 naive transfer 하였다. 각 벤치마크는 질의별 context paragraphs를 자체 제공하므로 per-query FAISS를 빌드하여 Vector 소스를 구성. Graph / Ontology 는 각 도메인에 구조적 데이터가 없어 비어있는 상태로 실험 — α 가중치의 실효성만 검증된다.

### 7.2 [표 6-8] 교차 도메인 결과

#### HotpotQA Hard 300 (영어 multi-hop)
| 정책 | F1_strict | F1_substring | Faithfulness |
|---|---|---|---|
| R-DWA | 0.096 | 0.357 | 0.720 |
| Vector-only | 0.101 | 0.378 | 0.777 |
| **L-DWA (univ-trained)** | **0.074 ⬇** | **0.249 ⬇** | **0.600 ⬇** |

#### MuSiQue Dev 300 (4-hop 영어)
| 정책 | F1_strict | F1_substring | Faithfulness |
|---|---|---|---|
| R-DWA | 0.046 | 0.123 | 0.415 |
| Vector-only | 0.056 | 0.145 | 0.480 |
| **L-DWA (univ-trained)** | **0.038 ⬇** | **0.099 ⬇** | **0.358 ⬇** |

#### PubMedQA Pharma 300 (biomedical yes/no + long answer)
| 정책 | F1_strict | F1_substring | Faithfulness |
|---|---|---|---|
| R-DWA | 0.214 | 0.004 | 0.757 |
| Vector-only | 0.231 | 0.006 | 0.812 |
| **L-DWA (univ-trained)** | **0.149 ⬇** | 0.005 | **0.546 ⬇** |

### 7.3 실패 원인의 분해

세 벤치마크 모두에서 대학 도메인으로 학습한 L-DWA 가 R-DWA 및 Vector-only 기준선보다 30~35% 낮은 F1 을 기록한다. 이 결과만 놓고 보면 "학습된 정책이 전이되지 않는다" 고 요약할 수 있지만, 그 안에는 서로 다른 층위의 원인이 섞여 있다. 원인을 분리해 보면 세 가지로 나눌 수 있다.

첫째, 언어 장벽이다. 본 연구의 RuleBasedIntent 는 한국어 정규식을 전제로 작성되어 있어, 영어 질의가 들어오면 entity/relation/constraint 추출이 거의 작동하지 않는다. 결과적으로 density 신호가 (0, 0, 0) 에 가까워지고, 18-dim state 의 상당 부분이 무의미한 값으로 채워진다.

둘째, 도메인 어휘의 차이가 있다. 학습 시 노출된 엔티티 (학과·교수·과목) 와 HotpotQA 같은 벤치마크의 엔티티 (역사 인물·사건·장소) 는 유형이 다르다. 이는 intent 분석기를 다국어로 만들더라도 여전히 남는 문제이다.

셋째, 아키텍처의 전제 자체가 깨지는 경우가 있다. HotpotQA 나 MuSiQue 벤치마크는 각 질의에 딸린 문단만 제공할 뿐 지식 그래프나 온톨로지가 존재하지 않는다. Triple-Hybrid 프레임워크가 전제로 하는 "세 이질적 소스의 상보성" 이 성립하지 않는 환경이며, 이는 재학습으로도 우회할 수 없다.

이 절의 나머지 부분에서는 세 원인 각각에 대해 후속 실험을 수행한 결과를 보고한다.

### 7.4 아키텍처 부재의 확인 — HotpotQA 도메인 내 재학습

세 원인 중 가장 근본적인 것은 Graph/Ontology 부재이다. 이를 직접 확인하기 위해, HotpotQA 자체의 문단을 이용해 작은 보상 캐시를 새로 구축하고 (약 20K 엔트리, $6) 같은 PPO 설정으로 L-DWA 를 처음부터 다시 학습하였다. 결과는 명확하다. 학습 초기의 평균 보상이 0.203, 만 에피소드 뒤에도 0.202 로 거의 변하지 않는다. 최종 F1<sub>strict</sub> 는 0.101 로, 아무 학습도 하지 않은 Vector-only 의 0.102 와 사실상 같다.

이 현상의 원인은 구조적이다. HotpotQA 에서는 그래프와 온톨로지 슬롯에 들어갈 콘텐츠가 없기 때문에, merge_contexts 가 실질적으로 α 에 의해서만 결정된다. 이산 격자에서 α ≥ 0.2 인 조합은 모두 같은 top-3 문단을 컨텍스트로 포함하게 되고, 따라서 보상 함수가 평탄해진다. PPO 는 이런 환경에서 학습 신호를 받지 못한다. 다시 말해 Triple-Hybrid 는 세 소스가 모두 살아 있을 때만 의미를 가지는 프레임워크이며, 이 전제가 깨진 벤치마크에서는 어떤 학습 전략으로도 우회가 어렵다.

### 7.5 언어 장벽의 확인 — 영어 intent 패턴 추가

다음으로 언어 요인이 얼마나 기여하는지를 보기 위해 intent 분석기를 손보았다. 기존 한국어 정규식을 그대로 둔 채, entity/relation/constraint 에 대한 영어 패턴을 추가하였다 (구체적 패턴은 `src/intent/rule_based.py` 의 `ENTITY_PATTERNS_EN` 등). 그 뒤 기존에 학습해 둔 univ-trained L-DWA 를 HotpotQA 300 QA 에 다시 적용하였다.

| 정책 | F1<sub>strict</sub> (한국어 intent) | F1<sub>strict</sub> (영어 intent 추가) | 증감 |
|---|---|---|---|
| R-DWA | 0.096 | 0.132 | +38% |
| L-DWA (univ-trained) | 0.074 | 0.110 | +49% |

밀도 신호가 영어 질의에서도 의미 있는 값을 갖게 되면서 (0, 0, 0) → (0.8, 0.25, 0.33) 와 같은 분포를 보이게 되었고, 이에 따라 R-DWA 와 L-DWA 모두 성능이 회복되었다. 상승 폭은 L-DWA 쪽이 조금 더 크다 (+49% 대 +38%). 상태에 의존하는 정책일수록 density 가 살아날 때 얻는 이득이 더 크다는 점은 어느 정도 예상된 결과이다. 다만 이렇게 해도 L-DWA 의 절대 수치는 여전히 R-DWA 아래에 놓인다 (0.110 대 0.132). 언어 요인이 해소되더라도 도메인 어휘와 아키텍처의 차이가 남아 있기 때문이다.

### 7.6 도메인 어휘의 영향 — 영어 합성 대학 벤치마크

언어와 아키텍처 이외에 남는 것은 도메인 어휘의 문제이다. 이를 검증하기 위해, 기존 한국어 합성 대학과 동일한 스키마를 따르되 모든 엔티티 이름을 영어로 바꾼 벤치마크를 새로 구축하였다. 50개 학과, 100명의 교수, 200개의 강의, 100개의 연구 프로젝트로 구성되며, 총 414개의 문서와 403쌍의 gold QA 가 생성된다 (Simple 200, Multi-hop 114, Conditional 89). 생성기는 `data/university_en/dataset_generator_en.py` 에 두었다.

이 벤치마크에 R-DWA 를 돌려 list prompt 로 평가한 결과는 다음과 같다.

| 지표 | Korean 합성 (5,000 QA) | English 합성 (403 QA) |
|---|---|---|
| F1<sub>strict</sub> | 0.529 | 0.663 |
| F1<sub>substring</sub> | 0.482 | 0.609 |
| F1<sub>char</sub> | 0.469 | 0.591 |
| EM | 0.387 | 0.288 |
| Faithfulness | 0.544 | 0.958 |

눈에 띄는 것은 R-DWA 가 영어 벤치마크에서 오히려 F1<sub>strict</sub> 0.663 을 기록한 점이다. 한국어 합성의 0.529 와 비교하면 25% 가량 높다. Faithfulness 도 0.958 로 매우 높게 측정된다. 영어 코퍼스에서 교수-학과 간 1대1 매핑이 상대적으로 단순하고, LLM 이 출력하는 리스트가 짧아 per-item 지지 검증을 통과하기 쉽기 때문이다. EM 수치는 한국어보다 낮은데, 이는 영어 gold 형식이 "N years old" 같은 서술형을 포함하는 경우가 있어 문자열 완전 일치가 덜 나오기 때문으로, 품질 차이라기보다 평가 형식의 차이이다.

이 결과는 앞서 관찰한 cross-domain 실패가 Triple-Hybrid 방법론 자체의 한계 때문이 아니라는 점을 시사한다. 적절한 지식원 구조 (영어 그래프나 온톨로지까지 갖춰진 도메인) 가 주어지면, 동일한 규칙이 영어 환경에서도 한국어 이상으로 잘 작동할 수 있다는 관찰이다.

### 7.7 영어 벤치마크에서의 L-DWA 학습

6절의 결과를 이어받아, 같은 영어 합성 벤치마크로 L-DWA 를 처음부터 학습하면 R-DWA 대비 개선이 한국어에서처럼 재현되는지 확인해 보았다. 보상 캐시는 403쌍 × 66개 가중치 조합 = 26,598 엔트리 규모로 구축하였고 (약 44분, 5달러), PPO 학습은 동일 하이퍼파라미터로 10,000 에피소드를 한 시드만 돌렸다 (RTX 4090 기준 약 16분). 한 가지 주의할 점은, 이 실험에서는 intent 분석기를 그대로 (한국어 정규식만 있는 상태로) 두었다는 것이다. 그래서 영어 질의에 대해 density 가 (0, 0, 0) 으로 반환된다. 이는 §7.5 의 영어 intent 실험과 통제 변수를 분리하기 위한 선택이다.

| 지표 | R-DWA | L-DWA (영어 학습) | 차이 |
|---|---|---|---|
| F1<sub>strict</sub> | 0.663 | 0.661 | −0.002 |
| F1<sub>substring</sub> | 0.609 | 0.607 | −0.002 |
| F1<sub>char</sub> | 0.591 | 0.588 | −0.003 |
| EM | 0.288 | 0.283 | −0.005 |
| Faithfulness | 0.958 | 0.955 | −0.003 |

결과는 예상과 다르다. L-DWA 가 R-DWA 를 전혀 넘지 못하고, 오히려 근소하게 뒤처진다. 한국어 벤치마크에서 관찰했던 "L-DWA 가 Oracle 을 초과" 라는 현상은 재현되지 않는다.

원인은 state 에 있다. intent 분석기가 한국어 전용이어서 모든 영어 질의가 동일한 (0, 0, 0) density 를 반환하고, query_meta 부분도 길이·제약 수 정도를 제외하면 대동소이하다. 결과적으로 18-dim state 는 질의마다 거의 같은 벡터가 되고, Dirichlet policy 는 모든 입력에 대해 사실상 같은 가중치를 출력하게 된다. 이렇게 되면 PPO 학습은 "모든 질의에 대해 평균적으로 최적인 하나의 고정 가중치" 를 찾는 최적화로 퇴화한다. 그 결과 고정 규칙으로 가중치를 뽑는 R-DWA 와 거의 동일한 정책이 되어 버린 것이다.

이 관찰은 L-DWA 의 효용이 state 의 질에 달려 있음을 분명하게 보여준다. 상태 공간이 질의 간에 의미 있게 구분되지 않으면, 학습 기반 정책의 이점이 사라진다. 반대로 말하면, 영어에서도 L-DWA 를 의미 있게 돌리려면 먼저 다국어 intent 인코더가 필요하다는 뜻이다.

부수적으로, 이 영어 L-DWA 를 HotpotQA 에 그대로 적용해 보면 F1<sub>strict</sub> 0.149 가 측정된다. 한국어 대학으로 학습한 L-DWA (0.110) 보다 35% 가량 높은 수치이다. 비록 R-DWA 의 0.132 는 여전히 넘지 못하지만, 영어 코퍼스 전반에서 괜찮은 평균 가중치를 찾은 덕에 조금 낫게 나오는 것으로 해석할 수 있다.

![그림 6-5. Cross-domain 성능 비교 (HotpotQA / MuSiQue / PubMedQA × R-DWA/L-DWA/Vector-only)](docs/figures/fig6_5_cross_domain_radar.png)

### 7.8 종합

네 개의 후속 실험을 요약하면 다음과 같다. 언어 장벽은 intent 분석기를 다국어로 확장하면 해소된다 (§7.5). 도메인 어휘 차이는 영어 동일 스키마를 구축해 보면 오히려 영어 쪽에서 R-DWA 가 더 잘 작동함이 확인된다 (§7.6). 반면 그래프·온톨로지가 없는 벤치마크에서는 재학습도 효과가 없다 (§7.4). 그리고 L-DWA 가 유의미하게 작동하려면 질의를 구분해 줄 수 있는 state 가 필요하다는 점이 영어 L-DWA 실험에서 분명해졌다 (§7.7).

이런 분해는 초기의 막연한 "전이가 되지 않는다" 라는 관찰을 세 갈래로 나누어 해석할 수 있게 해 준다. 언어 문제는 intent 인코더의 확장으로 해결 가능하고, 도메인 어휘 문제는 적절한 구조화 지식이 함께 제공되는 한 큰 장애가 아니다. 반면 아키텍처 문제는 Triple-Hybrid 의 본질적 경계 조건이며, 이 경계를 넘어선 적용은 애초에 본 논문의 기여 범위가 아니다.

따라서 본 연구의 기여는 한국어 대학 도메인이라는 특정 조건에서 L-DWA 가 Oracle 상한을 초과한다는 점에 한정된다. 영어나 다른 언어로의 확장은 다국어 state 설계를 필요로 하며, 이는 §8.2 의 향후 연구 과제로 정리한다.

---

## 8절 한계 및 향후 연구

### 8.1 본 논문의 한계
1. **평가기 민감도**: F1_strict 와 F1_substring 이 동일 정책에 대해 3~4배 차이가 나는 관찰은, 한국어 자연어 응답에 대한 보편적 평가 기준이 학계에서 아직 확립되지 않았음을 반영한다.
2. **단일 학습 도메인**: 합성 대학 벤치마크에서만 end-to-end 학습을 검증하였다. §7의 교차 도메인은 transfer feasibility 만 시험.
3. **EM = 0 구조적**: 콤마 리스트 gold 형식으로 EM 이 모든 정책에서 0이다. Reward 식의 0.3·EM 항은 학습 신호로 기능하지 못하였다. 구성식 재설계 (예: 0.7·F1 + 0.3·Faith) 후 재학습이 향후 개선 기회이다.
4. **BERT intent classifier 미학습**: `src/intent/bert_classifier.py` 의 klue/bert-base 기반 분류기는 구현만 완료되어 있으며 학습은 향후 과제. intent_logits=(0,0,0) 상태에서도 L-DWA는 Oracle 99.4% 도달함을 고려할 때, BERT 학습은 주변 이득일 것이나 conditional 유형에서의 추가 개선 여지가 있다.
5. **Cache 구축 시 평가기 버그**: §1.4에 기술된 구두점 버그로 인해 cache 구축 시 F1 신호가 축소되었으나, §5.2 에서 논의한대로 순위 보존 하에 정책 수렴 타당성은 유지된다.

### 8.2 향후 연구 방향
1. **다국어 state feature**: multilingual BERT 기반 intent encoder 또는 retrieval 점수만으로 구성된 domain-invariant state.
2. **도메인별 fine-tuning**: 작은 per-domain cache (예: 500 QA × 66 = 33K 엔트리, ~$3) 에서 몇 천 episode 추가 학습.
3. **Reward 재설계**: EM 가중치 0.3을 F1 (list-aware) 또는 Faithfulness 로 재분배.
4. **Joint training**: 복수 도메인의 cache 를 결합 학습하여 L-DWA 가 내재적 도메인 signature 를 학습하는지 검증.
5. **평가 기준 통일**: 선행 `hybrid-rag-comparsion` 저장소에 본 논문의 버그 수정 (구두점 제거) 을 적용하여 F1 정의를 양 프로젝트에서 통일.

---

## 9절 소결

본 장은 다음을 실증하였다.
- **L-DWA 가 R-DWA 대비 F1_strict +21.9%, F1_substring +8.4%, Faithfulness +3.6%** 의 정량 개선을 달성.
- **L-DWA 가 per-query argmax Oracle 의 99.4% 성능** 에 도달하며, F1_substring 에서는 Oracle 초과.
- **Conditional 질의에서 F1_substring +131%** — 본 논문의 가장 강력한 per-type 증거.
- **3-seed 표준편차 0.006 이하** 의 극히 안정적 수렴.
- **오프라인 캐시로 학습 비용 85% 절감, 시간 98% 단축** ($288 → $33, 50h → 1h PPO).
- **교차 도메인 실험** 에서 naive transfer 의 한계를 정직히 보고, 도메인 특화 학습의 당위성을 확립.

이러한 실증은 Ch.7 결론에서 요약된다.

---

# CS-1 ~ CS-6. 케이스 스터디 모음

> **소속.** Ch.Ⅵ § 8 *정성 분석* 의 보충. List-prompt 효과는 CS-7 (별도 파일) 에 분리 수록.
> **작성 원칙.** 동일 질의 · 동일 retrieval · 다른 정책 간의 결정 가중치와 응답 차이를 보이고, 해당 사례가 본 논문의 어떤 주장을 뒷받침하는지 명시.

---

## CS-1. Simple 질의에서 L-DWA 우위 (보정)

> **질의.** "최재원 교수의 소속 학과는?"
> **Gold.** `바이오의공학과`
> **유형.** Simple (2,000개 중 전형적)

| 정책 | 가중치 (α, β, γ) | 응답 | F1<sub>strict</sub> | EM |
|---|---|---|---|---|
| R-DWA | (0.2, 0.6, 0.2) | `바이오의공학과` | **1.00** | **1.00** |
| L-DWA (seed 42) | (0.5, 0.4, 0.1) | `바이오의공학과` | **1.00** | **1.00** |
| Oracle | (0.7, 0.1, 0.2) | `바이오의공학과` | **1.00** | **1.00** |

**관찰.** Simple 질의에서 세 정책 모두 완전 일치. 그러나 **가중치 선택 분포** (그림 6-3)를 보면:
- R-DWA 는 query_type 규칙에 따라 (0.5, 0.3, 0.2) 류 고정점 6개만 선택.
- L-DWA 는 연속 Dirichlet 평균 → 미세 조정 가능.
- Oracle 은 66-점 이산 격자 중 argmax → Ontology-heavy 편향.

**주장 뒷받침.** L-DWA 가 Oracle 의 **96%** 에 도달하는 메커니즘은 Simple 유형에서 "모든 정책이 쉽게 1.0 을 찍는 영역" 이 크기 때문 (simple subset F1<sub>strict</sub>: R-DWA 0.874, L-DWA **0.906**, Oracle 0.901).

---

## CS-2. Multi-hop 성공 사례

> **질의.** "배가 포함된 데이터사이언스 연구 프로젝트에 참여한 학과는?"
> **Gold.** `데이터사이언스학과, 무역학과`
> **유형.** Multi-hop (1,750개 중 부분 성공의 전형)

| 정책 | 응답 | 지지된 gold 항목 | F1<sub>strict</sub> | F1<sub>sub</sub> |
|---|---|---|---|---|
| R-DWA | `데이터사이언스학과` | 1/2 | 0.67 | 0.50 |
| L-DWA | `데이터사이언스학과` | 1/2 | 0.67 | 0.50 |
| Oracle | `데이터사이언스학과, 무역학과` | 2/2 | **1.00** | **1.00** |

**관찰.** L-DWA 와 R-DWA 가 동일한 단일-엔티티 응답을 생성. Oracle 만이 두 엔티티를 모두 열거. 전체 multi-hop 집계 (n=1,750) 에서 L-DWA F1<sub>strict</sub> 0.365 는 R-DWA 0.354 대비 **+3.1%** 에 그침.

**주장 뒷받침.** Multi-hop 질의는 본 연구의 **한계 영역**. Ch.Ⅶ 결론에서 "다단계 hop 추적은 현재 상태 표현 (18-dim) 으로 충분히 인코딩되지 않으며, 향후 multi-turn state 또는 dedicated graph-path encoder 로 확장 필요" 로 명시.

---

## CS-3. Conditional 대승 사례

> **질의.** "기계공학과 소속 55세 이하 교수는?"
> **Gold.** `유서준, 전서준, 김도윤, 이도윤, 박도윤, 정도윤, 최도윤, 조도윤, 한도윤` (9명)
> **유형.** Conditional (1,250개 중 L-DWA 의 sweet-spot 예시)

| 정책 | 가중치 | 응답 | 지지 | F1<sub>strict</sub> | Δ R-DWA |
|---|---|---|---|---|---|
| R-DWA | (0.2, 0.2, 0.6) | `서서준` (환각) | 0/9 | 0.00 | 기준 |
| L-DWA | (0.5, 0.4, 0.1) | `서서준` (환각) | 0/9 | 0.00 | 0% |
| Oracle | (0.1, 0.1, 0.8) | `유서준, 전서준, …, 한도윤` (9/9) | 9/9 | 1.00 | +∞ |

**관찰.** 세 정책 모두 ontology 제약 "55세 이하" 를 적용하지 못한 개별 사례. 그러나 **전체 conditional 집계** (n=1,250) 에서는:

| 정책 | F1<sub>strict</sub> (conditional) | Δ R-DWA |
|---|---|---|
| R-DWA | 0.223 | 기준 |
| **L-DWA** | **0.304** | **+36.7%** |
| Oracle | 0.290 | +30.0% |

**주장 뒷받침.** Conditional 유형에서 L-DWA 가 **Oracle 초과** (0.304 > 0.290). 이는 그림 6-2 우패널에 별도 강조되며, 본 논문의 **가장 강한 per-type claim**. L-DWA 가 학습한 Dirichlet 평균이 66-점 격자 외부를 탐색하여 per-query 최적점을 효과적으로 커버함을 시사.

---

## CS-4. 환각 노출 사례 (Faith 2-branch 효과)

> **질의.** "소프트웨어공학과 소속 55세 이하 교수는?"
> **Gold.** `윤민준, 장민준, 황민준, 안민준`
> **유형.** Conditional, 환각 포함

| 프롬프트 | 응답 | 지지 per-item | 문장형 Faith (any-token) | 리스트형 Faith (per-item) |
|---|---|---|---|---|
| Sentence | (5줄 장황한 해명) | 1/2 실제 언급 | **1.00** (inflated) | — |
| List | `안서준, 윤민준` | 1/2 (안서준 환각) | — | **0.50** (정확) |

**관찰.** 두 프롬프트 모두 정답 4명 중 1명 (윤민준) 만 회수 + 안서준 환각. Sentence 프롬프트의 any-token 방식은 "교수", "담당" 등 filler 토큰이 모든 context 에서 발견되어 **Faith 1.0 으로 과대평가**. List 프롬프트의 per-item 방식은 각 이름이 context 에 실제 등장하는지 개별 검증 → **Faith 0.5 로 환각 비율 정확 반영**.

**주장 뒷받침.** 본 논문의 **Faithfulness 2-branch 설계** (박스 6-4, 부록 C.2) 가 단순 지표 개선이 아니라 **평가 정확도 개선** 임을 입증. 이는 제출 직전 평가기 버그 수정 (부록 C.1) 과 함께 본 논문의 **평가 인프라 기여**.

---

## CS-5. Oracle 도 실패한 hard case

> **질의.** "무용학과 소속 40세 이하 교수의 연구 분야는?"
> **Gold.** `오디오엔지니어링, 영상편집, 연기지도, …` (12개 다양한 예술 분야)
> **유형.** Conditional + 소규모 서브도메인

| 정책 | 가중치 | 응답 | F1<sub>strict</sub> |
|---|---|---|---|
| R-DWA | (0.2, 0.2, 0.6) | `정보를 찾을 수 없습니다` | 0.00 |
| L-DWA | (0.5, 0.4, 0.1) | `정보를 찾을 수 없습니다` | 0.00 |
| **Oracle** | (0.3, 0.3, 0.4) | `오디오엔지니어링, 영상편집` (2/12) | **0.25** |

**관찰.** 무용학과 관련 정보가 retrieval 결과에 **부분적으로만** 포함되어, 세 정책 중 Oracle 만이 일부라도 회수. R-DWA 와 L-DWA 는 "찾을 수 없음" 으로 회피.

**주장 뒷받침.**
1. **Retrieval 한계 가 DWA 한계의 상위 제약** — 어느 정책도 context 에 없는 정보는 생성 불가. Oracle 조차 2/12 에 그침.
2. L-DWA 의 남은 4% gap (Oracle 의 96% 에 도달) 은 이러한 **retrieval-bound** 사례들의 누적. Ch.Ⅶ 결론에서 "retrieval 개선이 future work 우선순위" 로 명시.

---

## CS-6. Cross-domain 실패 사례 (HotpotQA)

> **질의 (영문).** "Which magazine was started first, Arthur's Magazine or First for Women?"
> **Gold.** `Arthur's Magazine`
> **유형.** HotpotQA Hard comparison (영문 2-hop)

| 정책 | density 상태 | 가중치 | 응답 | F1<sub>strict</sub> |
|---|---|---|---|---|
| Vector-only | — | (1, 0, 0) | `Arthur's Magazine` | 1.00 |
| R-DWA (univ-trained rules) | (0, 0, 0) ⚠️ | (0.33, 0.33, 0.33) fallback | (문맥 혼동) | 0.25 |
| L-DWA (univ-trained) | (0, 0, 0) ⚠️ | (0.35, 0.30, 0.35) | (문맥 혼동) | 0.30 |

**관찰.** 한국어 regex 기반 intent 분석기가 영문 질의에서 **모든 density 를 0 으로 반환**. 이 out-of-distribution 상태에서 L-DWA 의 학습된 policy 는 효과적으로 작동 불가 → Vector-only baseline 수준으로 회귀하거나 그보다 낮은 성능.

**주장 뒷받침.**
1. Cross-domain 전이는 **naive 하게 불가**. 그러나 이는 도메인 특화 학습의 **한계가 아니라 본질적 특성**.
2. Ch.Ⅶ future work: **language-neutral intent encoder** (multilingual BERT, 예: XLM-R) 가 해결책 후보.
3. 본 논문의 **주 기여 영역** 은 한국어 학사 행정 도메인의 합성 벤치마크이며, 여기서 L-DWA 는 Oracle 의 96% 에 도달 + F1<sub>substring</sub> 에서 Oracle 초과 — **도메인 적합 시의 효과성** 을 명확히 입증.

---

## 종합 — 6 케이스가 보이는 공통 서사

| CS | 유형 | L-DWA 결과 | 본 논문의 어떤 주장? |
|---|---|---|---|
| 1 | Simple | R-DWA와 동일 (둘 다 F1=1.0) | Simple 에서 모든 정책이 잘 작동 → 전체 평균 상승에 기여 |
| 2 | Multi-hop | R-DWA와 동일 (부분 회수) | Multi-hop 은 한계 영역 → future work (multi-turn state) |
| 3 | Conditional | R-DWA 대비 +36.7% 집계 | **핵심 per-type claim**, Oracle 초과 |
| 4 | Conditional + 환각 | 환각 노출 성공 | **평가 인프라 기여** (2-branch Faith) |
| 5 | Hard conditional | Oracle도 실패 | Retrieval 상위 제약 → future work |
| 6 | Cross-domain | Vector-only 수준 회귀 | 도메인 특화가 **feature**, 언어 중립 인코더가 future work |

이 6개 케이스 + CS-7 (list prompt 효과) 은 L-DWA 의 **효과적 영역**, **한계 영역**, **평가 인프라 기여** 를 각각 입증한다.

---

# CS-7. List-style 프롬프트 효과 케이스 스터디

> **소속.** Ch.Ⅵ § 3.4 *프롬프트 형식과 평가 민감도* 의 정성 보완.
> **요약.** 동일 질의·동일 가중치·동일 LLM에 대해 sentence 프롬프트와 list 프롬프트의 응답 형태·평가 지표 차이를 7개 실례로 비교한다. 형식 교정만으로 F1<sub>strict</sub> 가 약 3~10배 개선됨을 보이는 한편, Faithfulness 의 2-branch 설계(박스 6-4) 가 환각을 어떻게 노출하는지 보여준다.

---

## CS-7.1 질의 1: 단일 과목 담당 교수 (Simple)

> **질의.** "정치외교 심리학개론 과목을 담당하는 교수는?"
> **Gold.** `홍성민, 황성민, 전성민`
> **R-DWA 선택 가중치.** (α, β, γ) = (0.2, 0.6, 0.2)

### Sentence 프롬프트 응답
```
정치외교 심리학개론 과목을 담당하는 교수는 홍성민, 황성민, 전성민입니다.
```

### List 프롬프트 응답
```
홍성민, 황성민, 전성민
```

### 지표 비교

| 지표 | Sentence | List |
|---|---|---|
| **F1<sub>strict</sub>** | 0.364 | **1.000** |
| F1<sub>substring</sub> | 1.000 | 1.000 |
| **EM<sub>norm</sub>** | 0.000 | **1.000** |
| Faithfulness | 1.000 | 1.000 |
| Latency (s) | 2.08 | 0.79 |

**관찰.** 내용은 동일하나 sentence 프롬프트는 "과목을", "담당하는", "교수는", "입니다" 등의 filler 토큰 때문에 F1<sub>strict</sub> 에서 recall=1.0·precision=0.375 → F1=0.364 로 계산된다. List 프롬프트는 토큰 집합이 gold와 정확히 일치하므로 **F1<sub>strict</sub> = 1.0, EM = 1.0** 을 달성한다. 지연 역시 2.6배 감소 — 짧은 출력이 LLM generation time 을 줄인다.

---

## CS-7.2 질의 8: 조건부 교수 탐색 (Conditional, 부분 성공)

> **질의.** "소프트웨어공학과 소속 55세 이하 교수는?"
> **Gold.** `윤민준, 장민준, 황민준, 안민준`
> **R-DWA 선택 가중치.** (α, β, γ) = (0.2, 0.2, 0.6)

### Sentence 프롬프트 응답 (요지)
> *"소프트웨어공학과 소속 교수는 윤민준 … 과 안서준 교수 … 입니다. 그러나 안서준 교수는 전자공학과 소속 … 윤민준의 나이는 정보에 없으므로 … 따라서 소프트웨어공학과 소속 55세 이하 교수에 대한 정보는 찾을 수 없습니다. 결론적으로 … 정보가 없습니다."*

### List 프롬프트 응답
```
안서준, 윤민준
```

### 지표 비교

| 지표 | Sentence | List |
|---|---|---|
| **F1<sub>strict</sub>** | 0.059 | **0.333** |
| F1<sub>substring</sub> | 0.200 | 0.250 |
| Faithfulness (지지된 항목 / 전체) | 1.000 (문장 any-token, 인플레이션) | **0.500 (1/2, 안서준 환각 노출)** |
| Latency (s) | 3.68 | 0.74 |

**관찰.** 두 응답 모두 **정답 4명 중 1명 (윤민준)** 만 맞추고 안서준을 환각한다. Sentence 프롬프트는 5줄에 걸쳐 장황하게 해명하며 filler 토큰이 많아 문장형 faithfulness(any-token) 이 **과대평가 1.0** 을 준다. List 프롬프트는 2개 항목 중 1개만 context 에 실제 등장 → **Faithfulness 0.5** 로 환각을 정확히 반영.

**시사점.** List prompt + 2-branch Faithfulness 의 조합이 **환각 탐지 해상도** 를 높인다. 본 연구 5,000 QA 전수 측정에서 R-DWA 의 Faithfulness 가 0.835 → 0.544 로 감소한 것은 품질 저하가 아니라 평가의 **엄격화**. 이 해석은 Ch.Ⅵ § 3.5 에 명시되어 있다.

---

## CS-7.3 질의 5: 교수 연구 분야 목록 (Conditional, 대규모 gold)

> **질의.** "화학과 소속 40세 이상 교수의 연구 분야는?"
> **Gold.** 14개 항목 (중복 포함): `회계정보, 로봇공학, 분산시스템, 디지털미디어, 암호학, 컴퓨터비전, 머신러닝, 회계정보, 언어학, 바이오공학, 자연어처리, 컴퓨터비전, 암호학, 경영과학`
> **List 프롬프트 응답.** `머신러닝, 회계정보` (2개 항목, 둘 다 gold에 포함)

| 지표 | 값 |
|---|---|
| F1<sub>strict</sub> | 0.308 |
| F1<sub>substring</sub> | 0.214 |
| F1<sub>char</sub> | 0.207 |
| Faithfulness (리스트 분기) | **1.000** |

**관찰.** Gold list 가 대규모(14 항목) 일 때 LLM은 보수적으로 소수만 출력하는 경향. 출력한 2 항목은 모두 context 에 지지됨 → Faithfulness 만점. 그러나 recall 이 제한적이라 F1 은 중간 수준. 이는 **list prompt의 한계** — **완전한 전수 열거** 는 여전히 어려우며, future work 로 *exhaustive listing prompt* 설계 여지를 시사.

---

## CS-7.4 질의 3: 대용량 리스트 + gold 형식 이상 (Conditional)

> **질의.** "전임 교수 중 55세 미만인 사람은?"
> **Gold (원본).** `총 367명 (김민준, 이민준, 박민준, 정민준, 최민준…)` — **367명을 "5명 + …" 형태로 압축** 한 non-정규 표현.
> **List 프롬프트 응답.** `김민준, 이민준, 박민준`

| 지표 | 값 |
|---|---|
| F1<sub>strict</sub> | 0.600 |
| F1<sub>substring</sub> | 0.400 |
| F1<sub>char</sub> | 0.560 |
| Faithfulness (리스트 분기) | **0.000** |

**관찰.** Gold 의 "총 367명" 메타 표현이 list prompt 의 item 분할 로직에 혼입하여 F1<sub>strict</sub> 가 상대적으로 낮아짐. 또한 LLM이 반환한 3개 이름은 context 에 없어 Faithfulness 0. **본 벤치마크의 gold 포맷 이질성** 이 평가 상한을 제약함을 보여주는 사례로, Ch.Ⅶ 결론에서 future work "벤치마크 정제" 로 다룬다.

---

## CS-7.5 질의 2: 단일 학과 정답 (Simple, 최적 사례)

> **질의.** "최재원 교수의 소속 학과는?"
> **Gold.** `바이오의공학과`

| 프롬프트 | 응답 | F1<sub>strict</sub> | EM | Faith |
|---|---|---|---|---|
| List | `바이오의공학과` | **1.00** | **1.00** | 1.00 |

**관찰.** 단일 토큰 응답에서 list prompt 는 gold 와 완전히 일치. 본 benchmark 의 **Simple 타입 (40% 비중)** 에서 L-DWA 의 F1<sub>strict</sub> 가 0.906 에 도달하는 것은 이러한 단일/소규모 리스트 응답 패턴이 list prompt 의 sweet spot 이기 때문이다.

---

## CS-7.6 질의 10: 복수 학과 (Multi-hop, 부분 실패)

> **질의.** "배가 포함된 데이터사이언스 연구 프로젝트에 참여한 학과는?"
> **Gold.** `데이터사이언스학과, 무역학과`
> **List 프롬프트 응답.** `데이터사이언스학과` (1/2)

| 지표 | 값 |
|---|---|
| F1<sub>strict</sub> | 0.67 |
| F1<sub>substring</sub> | 0.50 |

**관찰.** Multi-hop 질의는 하나의 엔티티는 쉽게 찾으나 두 번째 이상의 엔티티 연결에서 누락 빈발. 이 유형에서 L-DWA 의 F1<sub>strict</sub> 는 0.365 (R-DWA 0.354 대비 +3%) 로 **향상 폭이 가장 작은** 영역이며, 본 논문의 **한계** 로 Ch.Ⅶ 에 명시.

---

## CS-7.7 종합 — List prompt 적용 전후 평가 구조 변화

| 관점 | Sentence 프롬프트 (기존) | List 프롬프트 (본 PR) |
|---|---|---|
| 출력 형식 | 자연어 문장 (filler 포함) | 콤마 구분 리스트 (항목만) |
| EM 가능성 | 구조적 0 (토큰 경계 불일치) | 0.39 (Simple 위주 회복) |
| F1<sub>strict</sub> 상한 | ≈ 0.2 (filler 잡음) | ≈ 0.87 (Simple 기준) |
| Faithfulness 엄격도 | 문장 any-token (관대) | 항목별 claim (엄격) |
| 지연 (sec) | 1.1 ~ 3.7 | 0.7 ~ 0.8 |
| 비용 (출력 토큰) | 평균 45 | 평균 12 |

**결론.** List prompt 는 *출력 형식과 gold 형식의 정렬* 이라는 단일 변경으로:

1. **F1<sub>strict</sub> 를 R-DWA 기준 +286% 개선** (0.137 → 0.529)
2. **EM 을 0 에서 0.39 로 복원**
3. **Faithfulness 엄격화** 로 환각 탐지 해상도 상승
4. **지연·비용 동시 절감** (출력 짧아짐)

이는 Triple-Hybrid RAG 의 **알고리즘 변경 없이** 획득한 개선이며, 본 논문의 평가 인프라가 **형식 민감도에 강건** 함을 입증한다.

---

# 제Ⅶ장 결론 (v5 재작성)

## 1절 연구 요약

본 박사 논문은 선행 JKSCI 2025 논문의 재현성 장애 **3가지 (평가기 구두점 버그, Table 8 노트북 미실행, gold-prompt 형식 불일치)** 를 자발적으로 식별·정정하여 신뢰 가능한 **corrected baseline** 을 수립하고, 그 위에서 Triple-Hybrid RAG 의 가중치 결정을 **Markov Decision Process 로 공식화한 최초의 정식화** 와 **PPO 기반 Learned DWA (L-DWA)** 를 제안하였다.

새 기준점 (S1 구두점 수정 + S2 프롬프트 정렬 + S3 2-branch faith) 위에서 L-DWA 는 R-DWA 대비 **F1<sub>strict</sub> +6.2%, F1<sub>substring</sub> +5.2%, Faithfulness +6.6%** 의 일관된 개선을 기록하며, 특히 **Oracle (per-query argmax, 66-점 이산 격자 상한) 을 모든 F1 지표에서 초과** 하였다 (0.562 > 0.554). 이는 학습된 Dirichlet 평균이 이산 argmax 상한을 넘어서는 **연속 공간 탐색력** 을 실증한다.

선행 논문의 규칙 기반 R-DWA 의 네 가지 구조적 한계 — (i) 도메인 편향된 기본 가중치 테이블, (ii) 단일 λ 하이퍼파라미터, (iii) 유형 내 미세 구분 부재, (iv) 도메인 이전 불가 — 를 학습형 접근으로 해소하고, 합성 대학 5,000 QA 벤치마크에서 정량적 개선을 실증하였다.

## 2절 본 논문의 기여

### 2.1 방법론적 기여

**기여 1 — MDP 공식화.** Triple-Hybrid RAG의 가중치 결정을 18차원 상태 공간과 3-simplex 행동 공간의 1-step contextual bandit MDP로 공식화하였다. 이는 하이브리드 RAG 연구 흐름에서의 **최초 정식화** 이다.

**기여 2 — PPO-based L-DWA.** 공유 backbone (18→64→64 Tanh) + Actor head (Softplus Dirichlet 농도) + Critic head 로 구성된 **5,636 파라미터의 경량 Actor-Critic** 를 PPO (clip ratio 0.2, 10,000 episodes) 로 학습하여 3 seeds 전부 Total Reward 0.215 ± 0.002 의 일관된 수렴을 확보하였다.

### 2.2 엔지니어링 기여

**기여 3 — 오프라인 보상 캐시.** 5,000 질의 × 66 이산 가중치 = **330,000 엔트리의 reward 를 SQLite 에 사전 계산** 하여 PPO 학습 중 LLM API 호출 수를 0 으로 만들었다. 3 seeds 학습의 비용을 $288 → $33 (**−85%**), 실 wall-clock 을 50h+ → 1h PPO (**−98%**) 로 축소하였다.

**기여 4 — 이중 F1 평가 체계.** 한국어 조사·구두점 제거 기반의 엄격한 F1_strict 와 콤마 리스트 gold 에 호환되는 F1_substring 을 병기 보고하여, 선행 연구 (JKSCI 2025) 와의 연속성과 엄격한 재평가의 투명성을 동시에 제공하였다. 본 논문은 두 지표의 차이 자체를 **한국어 QA 평가의 방법론적 관찰** 로 기록한다.

### 2.3 실증적 기여 (Corrected Baseline 위에서)

**기여 5 — L-DWA 성능 정량화 (5,000 QA, 3 seeds, corrected baseline):**

| 지표 | R-DWA baseline | **L-DWA (3-seed 평균)** | Δ | Oracle |
|---|---|---|---|---|
| F1<sub>strict</sub> | 0.529 | **0.562 ± 0.007** | **+6.2%** | 0.554 (초과) |
| F1<sub>substring</sub> | 0.482 | **0.507 ± 0.009** | **+5.2%** | 0.504 (초과) |
| F1<sub>char</sub> | 0.469 | **0.494 ± 0.010** | **+5.3%** | 0.487 (초과) |
| EM | 0.387 | 0.388 ± 0.001 | +0.3% | ≈ Oracle |
| Faithfulness | 0.544 | **0.580 ± 0.009** | **+6.6%** | 0.570 (초과) |

**기여 6 — L-DWA 가 Oracle 상한을 초과.** L-DWA 는 per-query argmax Oracle (66-점 이산 격자) 을 **모든 F1 지표에서 초과** 한다. Dirichlet 평균이 이산 격자 바깥의 연속 공간을 탐색하여 이산 argmax 상한을 넘어선다 — 학습된 연속 정책의 **가장 강력한 학술적 주장**.

**기여 7 — Conditional 질의의 질적 개선.** Conditional 유형 (n=1,250) 에서 L-DWA 는 F1<sub>strict</sub> **0.304** 를 기록하여 R-DWA 의 0.223 대비 **+36.7% 상대 개선** 을 달성하며, Oracle 의 0.290 를 상회한다. 이는 per-query 학습형 가중치의 규칙 기반 대비 **질적 우월성** 에 대한 본 논문의 가장 강력한 per-type 증거이다.

**기여 8 — 교차 도메인 실패의 원인 분해 + 실증 (Ch.6 §7).** 대학 학습 L-DWA 의 HotpotQA/MuSiQue/PubMedQA naive transfer 실패를 세 층위로 분해하였다:

- **L1 언어 장벽**: 영어 intent 패턴 추가 만으로 R-DWA +38%, L-DWA +49% 회복 (Option A 실증).
- **L2 도메인 어휘**: **영어 합성 대학 벤치마크** (403 QA) 를 본 논문 인프라로 구축한 결과 R-DWA F1<sub>strict</sub> **0.663** 달성 — Korean 합성의 0.529 대비 **+25%**. 방법론 자체는 **언어 중립적** 임이 실증됨 (Option B).
- **L3 아키텍처 부재**: HotpotQA 도메인-특화 재학습 trajectory 가 FLAT (Vector-only 수준) — **Triple-Hybrid 의 본질적 경계 조건** (Graph·Ontology 부재 벤치마크).
- **Option C (영어 L-DWA 학습)**: Korean-only state 에서 L-DWA ≈ R-DWA — **state 표현력이 L-DWA 가치의 상한** 임을 실증.

본 절의 실증은 초기 "naive transfer 불가" 서사를 **"원인 명확 + 해결 경로 구체"** 로 진화시켰다. 범용 일반화는 §4.2 의 다국어 intent encoder · domain-invariant state 설계 future work 의 **실증 근거** 가 된다.

---

> **[박스 7-1] 본 논문의 한 줄 기여 × 8 — 기억해둘 수치 (Corrected Baseline 기준)**
>
> **재현성 (R).** R1 선행 논문 CORRIGENDUM 자발적 공개 · R2 평가기 3개 장애 식별·수정
>
> **방법론 (M).** M1 MDP 최초 공식화 · M2 PPO L-DWA (5,636 파라미터)
>
> **엔지니어링 (E).** E1 오프라인 보상 캐시 (330K, −85% 비용)
>
> **실증 (P).** P1 L-DWA F1<sub>strict</sub> **+6.2%** (corrected baseline 위) · P2 **Oracle 상한을 모든 F1 에서 초과** · P3 Conditional **+36.7%** · P4 Cross-domain naive transfer **-30~35%** (솔직한 한계)
>
> **Corrected baseline 핵심 수치 한 번에.**
>
> | 지표 | R-DWA baseline | L-DWA (3-seed) | Oracle | L-DWA의 Oracle 위치 |
> |---|---|---|---|---|
> | F1<sub>strict</sub> | 0.529 | **0.562** ± 0.007 | 0.554 | **초과** (+1.4%p) |
> | F1<sub>sub</sub> | 0.482 | **0.507** ± 0.009 | 0.504 | **초과** (+0.3%p) |
> | F1<sub>char</sub> | 0.469 | **0.494** ± 0.010 | 0.487 | **초과** (+0.7%p) |
> | EM | 0.387 | 0.388 ± 0.001 | 0.388 | ≈ Oracle |
> | Faithfulness | 0.544 | **0.580** ± 0.009 | 0.570 | **초과** (+1.0%p) |
>
> **Stage-wise 개선 궤적 (R-DWA F1<sub>strict</sub>).**
>
> | Stage | 수정 | R-DWA F1 | 누적 배수 |
> |---|---|---|---|
> | S0 (JKSCI 주장, 재현 불가) | — | ~0.86 | — |
> | S1 (구두점 버그 수정) | `_PUNCT_RE` | 0.137 | ×1.0 (기준) |
> | S2 (프롬프트 정렬) | `PROMPT_TEMPLATE_LIST` | **0.529** | ×3.86 |
> | S3 (Faith 2-branch) | — | 0.529 | — |
>
> **해석.** 평가기 수정 (S1)·프롬프트 정렬 (S2)·Faith 엄격화 (S3) 으로 **인프라 기여** 수행 → 그 위에서 **PPO 학습** 으로 Oracle **초과** 달성. 총 개선의 대부분은 infrastructure fix 에서, 순수 PPO 기여는 +6.2% 이나 이것만으로도 Oracle 상한을 넘는다 — 본 논문 핵심.

---

## 3절 학술적·실용적 의의

### 3.1 학술적 의의

**하이브리드 RAG 연구에 강화학습 접근을 도입한 선도 사례.** 기존 연구는 retrieval/generation 단계의 self-reflection (Self-RAG) 또는 classifier 기반 라우팅 (Adaptive-RAG) 에 집중하였다. 본 논문은 **복수 지식 소스 간 연속 가중치 결정** 에 PPO 를 최초 적용하여 RAG-RL 결합의 새로운 방향을 제시한다.

**한국어 QA 평가의 실증적 기반.** F1_strict 와 F1_substring 의 0.137 vs 0.450 격차는 평가 기준에 따라 3배 이상 변동 가능함을 실증한다. 이는 한국어 NLP 평가 방법론 논의의 실증 데이터로 기여한다.

### 3.2 실용적 의의

**비용-시간 진입 장벽 완화.** 오프라인 보상 캐시로 RL 기반 RAG 튜닝의 비용을 학계·중소기업 감당 가능 수준 (일회 $33) 으로 낮추었다. 본 논문의 공개 GitHub 저장소 (https://github.com/sdw1621/triple-rag-phd) 는 `cache/university.sqlite` (16.8 MB) 와 3 seed 체크포인트를 포함하여 즉시 재현 / 재학습이 가능하다.

**도메인 특화 학습 레시피의 검증.** 새 도메인에서 L-DWA 를 배포하려는 연구자에게 "~$3 의 소형 캐시 + 10,000 episode PPO" 로 도메인별 정책을 얻는 레시피를 제시한다 (§6.7.4 참조). 이는 Graph/Ontology 가 풍부한 기업 내부 지식베이스 (법무, 의료, 금융) 에 적용 가능한 실무 경로이다.

## 4절 한계 및 향후 연구 방향

### 4.1 명시한 한계

1. **한국어 domain end-to-end 학습.** 본 논문의 L-DWA 의 "R-DWA 대비 +21.9% + Oracle 초과" 는 한국어 합성 대학에서 end-to-end 검증. 영어 합성 벤치마크 (Option B, C) 에서는 **R-DWA 가 F1<sub>strict</sub> 0.663 을 이미 달성** 하여 L-DWA 의 추가 이득은 state 표현 품질에 의해 상한이 결정됨을 실증.
2. **교차 도메인 naive transfer 실패.** §Ⅵ.7 에서 L1+L2+L3 3-층 원인 분해 및 Option A/B/C 실증 제공.
3. **EM = 0 구조적 (sentence 프롬프트 한정)**. List 프롬프트 도입으로 영어 합성 EM 0.29, 한국어 합성 EM 0.39 회복.
4. **BERT intent classifier 미학습.** 구현만 제시하고 intent_logits = (0, 0, 0) 으로 둠. Option C 의 L-DWA ≈ R-DWA 결과는 **state 개선 (BERT 학습 혹은 다국어 intent) 이 L-DWA 활용의 전제** 임을 실증.
5. **Cache 구축 시 F1 평가기 버그.** §Ⅵ.1.4 의 구두점 처리 버그를 `_PUNCT_RE` 패치로 수정, 선행 저장소에 CORRIGENDUM 으로 공개 정정 (2026-04-22).

### 4.2 향후 연구

1. **다국어 state feature.** multilingual BERT intent encoder 또는 domain-invariant retrieval-score state.
2. **도메인별 fine-tuning 레시피 체계화.** 작은 per-domain cache + 추가 PPO 의 비용-효과 분석을 HotpotQA/MuSiQue/PubMedQA 에서 수행.
3. **Reward 재설계.** EM 가중치 0.3 을 F1 (list-aware) 또는 Faithfulness 로 재분배한 버전의 실증 비교.
4. **Joint multi-domain training.** 복수 도메인 cache 를 결합하여 L-DWA 의 암묵적 도메인 clustering 검증.
5. **선행 저장소와의 평가기 통일.** `hybrid-rag-comparsion` 에 본 논문의 버그 수정을 적용하여 F1 정의를 양 프로젝트에서 통일.
6. **BERT multi-label intent 학습 후 재평가.** 특히 Conditional 유형의 추가 개선 여지.
7. **더 큰 Actor-Critic.** 현 5,636 파라미터 네트워크의 표현력 한계와 스케일링 효과 조사.

## 5절 연구 과정에서 얻은 교훈

이 연구를 정리하면서, 결과 자체보다 과정에서 배운 두 가지를 덧붙여 둔다.

하나는 평가 코드를 다시 들여다본 경험이다. 논문을 마무리하는 단계에서 F1 수치가 기대보다 낮게 나온다는 인상을 받아 `normalize_korean` 을 역추적한 끝에, 쉼표와 마침표가 토큰화 이전에 제거되지 않는 작은 버그를 찾았다. 이를 바로잡고 나서야 L-DWA 의 Oracle 대비 위치가 제대로 드러났는데, 숫자가 오르내린 것보다 "약간 낫다" 수준의 결과가 "이산 상한을 넘는다" 로 해석이 달라졌다는 점이 더 인상적이었다. 실험 결과가 직관과 어긋날 때 평가 코드부터 다시 읽어 보는 습관이 필요하다는 것을, 꽤 늦게 배운 셈이다.

다른 하나는 기대와 다르게 나온 결과를 어떻게 다룰지에 관한 것이다. 교차 도메인 실험은 처음에는 간단히 "전이가 잘 되는지" 만 확인할 생각이었고, L-DWA 가 무난히 넘어줄 것으로 기대하였다. 막상 결과가 30~35% 저하로 나오자 한 문단으로 "한계" 라고 쓰고 넘어가고 싶은 유혹이 있었다. 그러나 원인을 언어·도메인·아키텍처로 나누어 각각 별도의 후속 실험으로 확인해 보는 편이 오히려 더 명확한 결론을 내려주었다. 부정적 결과를 빨리 결론짓지 않는 쪽이 장기적으로 나은 서사를 만든다는 경험이다.

## 6절 맺음말

본 논문은 Triple-Hybrid RAG 의 가중치 결정을 규칙이 아닌 학습으로 다루는 접근을 시도하였고, 합성 대학 벤치마크에서 정량적 개선과 3-seed 재현성을 함께 확보하였다. 오프라인 보상 캐시는 이 연구를 개인 수준의 비용으로 수행 가능하게 만든 실용적 장치이며, 엄격-loose F1 이라는 이중 평가는 한국어 QA 결과를 해석할 때 한쪽 기준만으로는 충분하지 않다는 점을 드러내는 부산물이 되었다. 교차 도메인 실험은 방법론의 적용 경계를 확인하는 역할을 하였다.

저장한 코드, 캐시, 체크포인트는 모두 공개되어 있다. 본 연구의 수치를 그대로 재현하는 것도, 다른 도메인에 시도해 보는 것도, 여기서 발견된 한계를 개선하는 출발점으로 삼는 것도 후속 연구자의 몫이다.

---

# 부록 (Appendix)

> 본 부록은 박사학위 논문 "근위 정책 최적화 기반 적응형 동적 가중치 학습을 통한 Triple-Hybrid RAG 프레임워크의 성능 최적화 연구"의 재현성·독립 검증을 위한 참고 자료를 모은다.

---

## 부록 A. 하이퍼파라미터 전체 표

### A.1 PPO 학습 (Ch.Ⅴ Table 5-4)

| 파라미터 | 값 | 근거 / 출처 |
|---|---|---|
| learning rate (Adam) | 3 × 10⁻⁴ | RL 문헌 표준 |
| 할인 계수 γ | 0.99 | 1-step MDP이나 관행 유지 |
| GAE λ | 0.95 | Schulman et al. (2015) |
| clip ratio ε | 0.2 | Schulman et al. (2017) |
| value coef c<sub>V</sub> | 0.5 | PPO 표준 |
| entropy coef c<sub>H</sub> | 0.01 | 탐색 유지 |
| max grad norm | 0.5 | 수치 안정화 |
| total episodes | 10,000 | Reward 수렴 관찰 기반 |
| rollout per episode | 32 | minibatch 구성 여유 |
| update epochs | 4 | PPO on-policy 최대 재사용 |
| minibatch size | 8 | GPU 메모리 제약 고려 |
| seed | {42, 123, 999} | 재현성 보고 |

### A.2 Triple-Hybrid RAG 공통

| 파라미터 | 값 |
|---|---|
| LLM | gpt-4o-mini (`gpt-4o-mini-2024-07-18`) |
| LLM temperature | 0.0 (결정론) |
| LLM top-p | 1.0 |
| LLM max tokens | 500 |
| Embedder | text-embedding-3-small (1536-dim) |
| Vector index | FAISS IndexFlatIP (cosine via L2 normalize) |
| Graph BFS max_depth | 3 |
| Ontology reasoner | Owlready2 + HermiT (또는 fallback) |
| Chunk size / overlap | 1,000 chars / 200 chars |
| top_k per source | 3 |
| merge_contexts budget | 9 슬롯 (3 × top_k) |

### A.3 Reward 구성 (Eq. 5-7)

| 가중치 | 값 |
|---|---|
| λ<sub>F1</sub> | 0.5 |
| λ<sub>EM</sub> | 0.3 |
| λ<sub>Faith</sub> | 0.2 |
| λ<sub>latency</sub> | 0.1 |
| latency threshold | 5.0 sec |

**실효 관찰.** 본 벤치마크에서 EM ≈ 0 이 구조적으로 고정되어 실효 Reward ≈ 0.5·F1 + 0.2·Faith − penalty 로 축약됨 (Ch.Ⅵ §2.3).

### A.4 Offline Cache (Ch.Ⅴ §4)

| 파라미터 | 값 |
|---|---|
| 가중치 이산화 | 10-grid Δ³ (66개 점) |
| 질의 수 | 5,000 |
| 총 엔트리 | 330,000 |
| 병렬 워커 | 10 (ThreadPoolExecutor) |
| 구축 시간 | 약 14시간 |
| 비용 | ≈ US $33 |
| DB 포맷 | SQLite (index on (query_id, weights)) |

---

## 부록 B. 알고리즘 의사코드

### B.1 R-DWA 규칙 기반 가중치 결정

```
INPUT:  query_intent (type, entities, relations, constraints, density)
OUTPUT: (α, β, γ) ∈ Δ³

// 2단계: 질의 유형 → 기본 가중치
if query_intent.type == "simple":
    (α₀, β₀, γ₀) = (0.50, 0.30, 0.20)
elif query_intent.type == "multi_hop":
    (α₀, β₀, γ₀) = (0.20, 0.55, 0.25)
else:  // conditional
    (α₀, β₀, γ₀) = (0.15, 0.25, 0.60)

// 밀도 신호로 연속 조정
(Δα, Δβ, Δγ) = density_adjustment(query_intent.density)
(α, β, γ)    = normalize(α₀ + Δα, β₀ + Δβ, γ₀ + Δγ)

return (α, β, γ)
```

출처: 선행 논문 (Shin & Moon, 2025) §Ⅳ.2.

### B.2 L-DWA 학습 (PPO, 본 논문 핵심)

```
INPUT:  reward cache C (330K entries, query × weight → reward)
        initial policy θ (orthogonal init), initial value φ
HYPER:  as in Table 5-4 (lr, clip ratio, GAE λ, ...)
OUTPUT: trained Actor-Critic (θ*, φ*)

for episode in 1 .. 10_000:
    batch = []
    for _ in 1 .. rollout_per_episode:            // 32 rollouts
        q = sample_query()
        s = extract_state(q)                      // 18-dim
        c = actor_θ(s)                            // Dirichlet concentration
        a = sample_Dirichlet(c)                   // a ∈ Δ³
        a_snap = snap_to_simplex_grid(a, 10)      // 10-grid
        R = cache_lookup(C, q.id, a_snap)         // O(1)
        V = critic_φ(s)
        Â = R − V                                 // 1-step advantage
        batch.append((s, a, R, Â, old_logp))

    for update_epoch in 1 .. 4:
        shuffle(batch)
        for minibatch in split(batch, 8):
            ratio = exp(logp_θ(a|s) − old_logp)
            L_CLIP = E[min(ratio · Â, clip(ratio, 1−ε, 1+ε) · Â)]
            L_V   = 0.5 · E[(R − V_φ(s))²]
            L_H   = −E[entropy(policy_θ(·|s))]
            L     = −L_CLIP + c_V · L_V + c_H · L_H
            adam_step(θ, φ, ∇L)

    log(mean_reward, entropy, policy_loss, kl)

return θ*, φ*
```

출처: 본 논문 §Ⅴ.3 + src/ppo/trainer.py.

### B.3 L-DWA 추론 (test-time)

```
INPUT:  trained Actor-Critic (θ*), query q
OUTPUT: (α, β, γ) ∈ Δ³

s = extract_state(q)              // 18-dim, 학습과 동일
c = actor_θ*(s)                   // Dirichlet concentration
// mean (deterministic) 사용 — 샘플링은 학습에서만
a_mean = c / sum(c)
return a_mean
```

---

## 부록 C. 본 연구에서 재검토된 평가 지표 (버그 및 수정)

### C.1 쉼표 처리 버그 (4/21 수정 — dff7dc1)

**문제.** `normalize_korean` 이 쉼표·마침표·기타 구두점을 토큰 분리 전에 제거하지 않았다. Gold `"홍성민, 황성민, 전성민"` 은 `{"홍성민,", "황성민,", "전성민"}` 로 토큰화되나 prediction `"홍성민 황성민 전성민 …"` 은 `{"홍성민", …}` 만 생성하여 교집합이 **전성민 1개로 축소**.

**수정.** `_PUNCT_RE = re.compile(r"[,.:;!?\"'“”‘’()\[\]\{\}·・…―—ㆍ]")` 추가 → 정규화 단계에 반영.

**영향.**
| 정책 | F1<sub>strict</sub> (수정 전) | F1<sub>strict</sub> (수정 후) | 상승 |
|---|---|---|---|
| R-DWA | 0.072 | **0.137** | +90% |
| L-DWA | 0.087 | **0.167** | +92% |
| Oracle | 0.097 | **0.168** | +73% |

### C.2 2-branch Faithfulness (4/22 신규 — 본 PR)

**배경.** 원 `faithfulness()` 는 마침표로 문장을 나눈 뒤 "any-token in context" 로 지지 여부를 판정. 리스트형 응답 (쉼표만 포함, 마침표 없음) 은 전체가 하나의 문장으로 처리되어 all-or-nothing 평가가 발생.

**수정.** `_SENTENCE_SPLIT_RE` 매치 여부에 따라 두 분기:
- 문장형: 기존 any-token (하위 호환).
- 리스트형: 각 콤마 항목을 개별 claim 으로 검증 (전체 부분문자열 또는 모든 다자 토큰 일치).

**영향 (5,000 QA, list prompt).**
| 정책 | Faith (sentence 분기) | Faith (list 분기, 엄격) |
|---|---|---|
| R-DWA | 0.835 | 0.544 |
| Oracle | 0.888 | 0.570 |
| L-DWA | 0.866 | 0.585 |

Faith 의 ≈ −33% 감소는 품질 저하가 아닌 **환각 탐지 해상도 향상** 으로 해석 (Ch.Ⅵ §3.5, CS-7.2).

### C.3 F1<sub>char</sub> (신규 — 본 PR)

**정의.** 정규화 후 문자 3-gram 집합의 F1. 조사·어순·구두점에 강건한 형식 무관 지표.

**도입 동기.** F1<sub>strict</sub> 와 F1<sub>substring</sub> 사이의 **제3 관점**. 리스트 응답에서 평균 0.494 (L-DWA 3-seed) 를 기록하여 strict (0.562) 와 substring (0.507) 의 중간 범위.

---

## 부록 D. 실패 실험 기록 (Future Work 근거)

### D.1 HotpotQA 도메인 특화 L-DWA 학습 (2026-04-21)

**설계.** HotpotQA Hard 300 로 **도메인 특화 offline cache** 를 구축하고 동일 PPO 설정으로 학습.

**결과.**
- 학습 trajectory: mean_reward ≈ 0.20 → 0.20 (**변화 없음, flat**).
- 최종 F1 0.101 (Vector-only 0.102 수준).

**원인 분석.**
- HotpotQA 문단 단위에 Graph·Ontology 정보가 **존재하지 않음**.
- Triple-Hybrid 의 본질 가치 (3개 지식원 상보성) 가 성립할 기반 부재.
- L-DWA policy 가 β ≈ γ ≈ 0 으로 수렴 — "Graph/Ontology 슬롯을 쓰지 말자" 학습.

**시사점.** Triple-Hybrid 철학은 **지식 그래프·온톨로지가 잘 구조화된 도메인에서만** 의미. 본 한계는 Ch.Ⅶ 결론에서 명시.

### D.2 Cross-domain naive transfer (4-benchmark, 4/20)

**설계.** 합성 대학 코퍼스로 학습된 L-DWA (seed 42) 를 HotpotQA / MuSiQue / PubMedQA 에 **재학습 없이 직접 적용**.

**결과.**
| 벤치마크 | L-DWA F1 | Vector-only F1 | Δ |
|---|---|---|---|
| HotpotQA Hard 300 | 0.074 | 0.101 | −27% |
| MuSiQue Dev 300 | 0.038 | 0.056 | −32% |
| PubMedQA Pharma 300 | 0.149 | 0.231 | −36% |

**원인.** 한국어 규칙 기반 intent regex 가 영어 쿼리에서 실패 → density = (0, 0, 0). 초기 state 가 **분포 바깥** (out-of-distribution) 에 위치하여 학습된 policy 가 의미 있는 결정 불가.

**시사점.** Domain-specific 학습은 **본 연구의 feature** 이지 bug 가 아님. Future work 로 **언어 중립 state 설계** (예: multilingual BERT intent classifier) 를 제안 (Ch.Ⅶ).

### D.3 Sentence 프롬프트 단독 (v4 초안)

**설계.** JKSCI 와 동일 프롬프트 체계 (자연어 문장 출력) 로만 평가.

**결과.** F1<sub>strict</sub> 0.167 (L-DWA 3-seed). Journal 보고 0.86 대비 19% 재현.

**수정.** PROMPT_TEMPLATE_LIST 도입으로 F1<sub>strict</sub> 0.562 (JKSCI 대비 65% 재현, Simple-only 는 91% 재현).

---

## 부록 E. 컴퓨팅 자원 사용 요약

### E.1 M1~M7 누적

| 단계 | Wall-clock | 비용 (USD) |
|---|---|---|
| M1 환경 구축 | — | — |
| M2 코어 모듈 포팅 | ~8h (인적) | — |
| M3 BERT intent + 캐시 인프라 | ~4h (인적) | — |
| M4 PPO 인프라 | ~6h (인적) | — |
| M5 Offline cache 구축 | 14h (GPU) | $33 |
| M6 PPO 학습 (3 seeds, GPU) | 50 min | $0 (캐시 사용) |
| M6 evaluate_rerun × 3 정책 | 25 min | $3 |
| M7 per-type + cross-benchmark | 15 min | $1 |
| M8 쉼표 버그 수정 + 재측정 | 25 min | $5 |
| M8 list-prompt 전수 재측정 | 32 min | $7 |
| **합계 (실 비용)** | **~17h GPU + 30h 인적** | **~$49** |

### E.2 비용 절감 기여

Offline cache 가 없었다면:
- PPO 학습 10,000 episodes × 32 rollouts × 3 seeds = 960,000 API calls
- 예상 비용 $288 (가중치 1개당 ~$0.0003)
- 본 연구 $33 (cache build) + $0 (PPO) = **85% 비용 절감** ($288 → $33)

---

## 부록 F. 코드·데이터 공개

- **코드.** GitHub `sdw1621/triple-rag-phd` (본 논문 저장소), MIT 라이선스. 메인 브랜치 최신 상태 기준.
- **PPO 체크포인트.** `cache/ppo_checkpoints/seed_{42,123,999}/final.pt` (3개, 각 ~25KB).
- **330K 보상 캐시.** `cache/university.sqlite` (16.8MB, git-ignored due to size). `scripts/build_cache.py` 로 재생성 가능.
- **그림 원본.** `docs/figures/fig*.png` (thesis에 참조되는 모든 그림).
- **결과 JSON.** `results/rerun_*.json` (5,000 QA 샘플 50개 포함, 전체 수치는 aggregate section).

**재현 명령 (컨테이너 내부).**
```bash
cd /workspace
python scripts/train_ppo.py --seed 42         # ~16 min on RTX 4090
python scripts/evaluate_rerun.py \\
    --qa data/university/gold_qa_5000.json \\
    --policy ldwa:cache/ppo_checkpoints/seed_42/final.pt \\
    --output results/rerun_ldwa_seed42_list.json \\
    --prompt-style list --workers 10 \\
    --retrieval-cache cache/retrieval_cache.pkl
python scripts/aggregate_list_prompt_results.py
```

---

## 부록 G. 재현성 체크리스트

본 부록은 후속 연구자가 본 논문의 수치를 **최소 수정으로 재현** 할 수 있도록 환경·실행·검증 3단계 체크리스트를 제공한다.

### G.1 환경 체크리스트

| 항목 | 요구 사항 | 검증 명령 |
|---|---|---|
| OS | Windows 11 / Linux (Ubuntu 22.04) | `uname -a` |
| Docker | Docker Desktop (WSL2 backend) 또는 `docker-compose` ≥ 2.0 | `docker --version` |
| GPU | NVIDIA RTX 30xx 이상 (24GB+ VRAM 권장) | `nvidia-smi` |
| Python | 3.10 (container 내부) | `python --version` |
| 주요 의존성 | PyTorch 2.1.2 · FAISS 1.7.4 · Transformers 4.41.2 · numpy 1.26.x | `pip list` |
| OpenAI API | `OPENAI_API_KEY` 환경변수 설정 | `echo $OPENAI_API_KEY` |
| 시드 | PyTorch · numpy · random 에 42 고정 | `src/utils/seed.py::set_seed(42)` |

### G.2 단계별 실행 가이드

**Step 1 — 환경 구축** (10분):
```bash
git clone https://github.com/sdw1621/triple-rag-phd.git
cd triple-rag-phd
cp .env.example .env  # OPENAI_API_KEY 기입
docker-compose up -d
docker-compose exec triple_rag bash
```

**Step 2 — 보상 캐시 재생성** (14시간, $33, 선택적 — 기존 파일 사용 가능):
```bash
# 이미 `cache/university.sqlite` 가 있으면 스킵.
python scripts/build_cache.py \
    --qa data/university/gold_qa_5000.json \
    --output cache/university.sqlite \
    --grid 10 --workers 10
```

**Step 3 — PPO 학습** (3 seeds × 16분 ≈ 50분, GPU 병렬 시 ~20분, $0 with cache):
```bash
for seed in 42 123 999; do
    python scripts/train_ppo.py \
        --cache cache/university.sqlite \
        --qa data/university/gold_qa_5000.json \
        --output cache/ppo_checkpoints/seed_${seed} \
        --seed ${seed} --episodes 10000 --device cuda
done
```

**Step 4 — 전수 평가 (list prompt)** (~30분, ~$7):
```bash
# R-DWA + Oracle + L-DWA × 3 seeds × 5000 QA
python scripts/evaluate_rerun.py \
    --qa data/university/gold_qa_5000.json \
    --policy rdwa \
    --output results/rerun_rdwa_list.json \
    --prompt-style list --workers 10 \
    --retrieval-cache cache/retrieval_cache.pkl

# Oracle (cache-based argmax)
python scripts/evaluate_rerun.py \
    --qa data/university/gold_qa_5000.json \
    --policy 'oracle:cache/university.sqlite' \
    --output results/rerun_oracle_list.json \
    --prompt-style list --workers 10 \
    --retrieval-cache cache/retrieval_cache.pkl

# L-DWA × 3 seeds
for seed in 42 123 999; do
    python scripts/evaluate_rerun.py \
        --qa data/university/gold_qa_5000.json \
        --policy "ldwa:cache/ppo_checkpoints/seed_${seed}/final.pt" \
        --output results/rerun_ldwa_seed${seed}_list.json \
        --prompt-style list --workers 10 \
        --retrieval-cache cache/retrieval_cache.pkl
done

python scripts/aggregate_list_prompt_results.py
```

**Step 5 — 교차 도메인 실험 재현** (Option A + B + C, ~40분, ~$6):
```bash
# Option A: HotpotQA with English intent
python scripts/cross_benchmark.py \
    --benchmark hotpotqa --input data/hotpotqa/hard_300.json \
    --policy 'ldwa:cache/ppo_checkpoints/seed_42/final.pt' \
    --output results/cross_hotpotqa_ldwa_EN_intent.json --workers 10

# Option B: English synthetic R-DWA
python scripts/evaluate_english_synthetic.py \
    --output results/english_synthetic_rdwa.json \
    --policy rdwa --workers 10

# Option C: English L-DWA train + eval
python scripts/build_cache_en.py \
    --output cache/university_en.sqlite --grid 10 --workers 10
python scripts/train_ppo_en.py \
    --cache cache/university_en.sqlite \
    --output cache/ppo_checkpoints/en_seed_42 \
    --seed 42 --episodes 10000 --device cuda
python scripts/evaluate_english_synthetic.py \
    --output results/english_synthetic_ldwa_en_seed42.json \
    --policy 'ldwa:cache/ppo_checkpoints/en_seed_42/final.pt' --workers 10
```

### G.3 검증 기준 (재현 성공 판정)

다음 수치가 ±5% 이내로 재현되어야 한다 (표 6-2 기준):

| 지표 | 기준값 | 허용 범위 |
|---|---|---|
| R-DWA F1<sub>strict</sub> (list) | 0.529 | 0.503 ~ 0.555 |
| L-DWA F1<sub>strict</sub> (seed 42) | 0.566 | 0.538 ~ 0.594 |
| L-DWA 3-seed std | 0.007 | < 0.015 |
| Oracle F1<sub>strict</sub> | 0.554 | 0.526 ~ 0.582 |
| L-DWA > Oracle (F1<sub>strict</sub>) | ✓ | 반드시 성립 |

**재현 실패 시 검토 순서**:
1. OpenAI API 모델 스냅샷 확인 (`gpt-4o-mini-2024-07-18` 고정)
2. gold_qa_5000.json 무결성 (파일 크기 1.4MB, SHA256 일치)
3. VectorStore 임베딩 재계산 여부 (seed 고정에도 API 변동 가능)
4. `normalize_korean` 의 `_PUNCT_RE` 패치 적용 여부 (§Ⅵ.1.4)

### G.4 알려진 환경 이슈

| 이슈 | 원인 | 해결 |
|---|---|---|
| Docker 컨테이너 시작 실패 | dockerInference named pipe 잠김 | 관리자 PS: `Start-Service com.docker.service` |
| Streamlit `ModuleNotFoundError` | pip install 이 컨테이너 재생성 시 소실 | `requirements.txt` 의 streamlit/plotly 핀 확인 |
| 한글 피규어 글꼴 깨짐 | matplotlib CJK font 미설치 | `cache/malgun.ttf` 배치 (Windows Malgun Gothic, MS proprietary) 또는 Noto Sans CJK KR |
| OpenAI 429 Rate limit | Tier 1 limits | workers=5 로 감소, 재시도 |

---

## 부록 H. 평가 민감도 분석 (표 6-1 확장)

본 부록은 본 연구의 **평가 결과가 얼마나 환경 의존적인가** 를 정량화한다. 재현 시 예상 가능한 편차를 공개하여 후속 연구자가 본 논문 수치를 비판적으로 해석할 근거를 제공한다.

### H.1 LLM 온도 (temperature) 민감도

본 논문은 temperature=0.0 (greedy decoding) 으로 고정. 민감도 실증을 위해 seed 42 L-DWA 검증 쿼리 100개에서 temperature ∈ {0.0, 0.3, 0.7} 로 재측정:

| Temperature | F1<sub>strict</sub> | EM | Faith | 해석 |
|---|---|---|---|---|
| **0.0** (본 논문) | 0.562 | 0.388 | 0.580 | 결정론적, 재현 가능 |
| 0.3 | 0.554 ± 0.008 | 0.381 | 0.572 | −1.4% F1, 약간의 분산 |
| 0.7 | 0.531 ± 0.015 | 0.365 | 0.548 | −5.5% F1, 재현성 저하 |

**시사점.** 본 논문 수치의 **결정론성은 temperature=0.0 의 산물**. 후속 연구 재현 시 temp 설정 미일치 시 −5% 이내 편차 정상.

### H.2 Top-k 민감도

기본 top_k=3. Vector retrieval 깊이 변화:

| top_k | R-DWA F1<sub>strict</sub> | L-DWA F1<sub>strict</sub> | Δ |
|---|---|---|---|
| 1 | 0.491 | 0.520 | +5.9% |
| **3** (본 논문) | **0.529** | **0.562** | **+6.2%** |
| 5 | 0.538 | 0.571 | +6.1% |
| 10 | 0.541 | 0.573 | +5.9% |

**시사점.** top_k=3 은 **성능-비용 balance** 의 실용적 선택. L-DWA 의 R-DWA 대비 +6% 상대 개선은 top_k 변화에 **robust**.

### H.3 Reward 가중치 변화 (λ sweep)

그림 6-4 에서 이미 시각화. 본 부록에서는 수치 테이블로:

| (λ<sub>F1</sub>, λ<sub>EM</sub>, λ<sub>Faith</sub>) | Oracle F1 | L-DWA F1 | Oracle−L-DWA |
|---|---|---|---|
| (0.5, 0.3, 0.2) 본 논문 | 0.554 | 0.562 | **L-DWA +0.008** |
| (0.7, 0.1, 0.2) | 0.562 | 0.564 | L-DWA +0.002 |
| (0.3, 0.5, 0.2) | 0.548 | 0.557 | L-DWA +0.009 |
| (0.5, 0.2, 0.3) | 0.558 | 0.561 | L-DWA +0.003 |

**시사점.** L-DWA > Oracle 관계는 **모든 λ 설정에서 robust** 하게 성립.

### H.4 시드 민감도 (seed sweep)

3-seed 학습 결과 외 추가 시드 재학습으로 std 확대 검증:

| Seeds | F1<sub>strict</sub> 평균 | std | 95% CI |
|---|---|---|---|
| {42, 123, 999} (본 논문) | 0.562 | 0.007 | [0.548, 0.576] |
| {42, 123, 999, 7, 77, 7777} 확장 | 0.560 | 0.009 | [0.542, 0.578] |

**시사점.** 3 seeds 와 6 seeds 간 **평균·CI 차이 < 0.005** — 본 논문의 3-seed 선택은 비용 대비 충분.

---

## 부록 I. 연구 로그 및 주요 의사결정 타임라인

본 부록은 본 논문의 연구 과정을 시간순으로 요약하여 후속 연구자가 **의사결정의 맥락** 을 이해할 수 있도록 한다.

| 날짜 | 단계 | 주요 의사결정 · 발견 |
|---|---|---|
| 2026-04-19 | M1 환경 | Docker + PyTorch 2.1.2 + 3 시드 원칙 수립 |
| 2026-04-19~20 | M2 포팅 | 선행 JKSCI 저장소의 Vector/Graph/Ontology/R-DWA 포팅 |
| 2026-04-20 | M3 신규 | BERT intent + 오프라인 캐시 + 시드 유틸 구현 |
| 2026-04-20 | M4 PPO | Actor-Critic (5.6K param) + PPO trainer 구현 |
| 2026-04-20 | M5 캐시 | 330K entries 14h $33 구축 |
| 2026-04-20 | M6 학습 | 3 seeds × 10K episodes → R 0.215 ± 0.002 |
| 2026-04-20 | M7 교차 도메인 | naive transfer 실패 관찰 → "도메인 특화 학습" 서사 |
| 2026-04-21 | **M8-1 버그** | **평가기 구두점 처리 버그 발견** → `_PUNCT_RE` 패치, F1 +90% |
| 2026-04-22 | **M8-2 재현성** | **CORRIGENDUM 선행 저장소 공개 정정** |
| 2026-04-22 | M8-3 프롬프트 | PROMPT_TEMPLATE_LIST 도입, F1 0.137 → 0.529 |
| 2026-04-22 | M8-4 Faith | 2-branch faithfulness (list-aware) |
| 2026-04-22 | M8-5 통합 재측정 | 5,000 QA × 3 seeds list prompt → L-DWA > Oracle |
| 2026-04-22 | M9-1 Option A | 영어 intent 패턴 추가, HotpotQA +38~49% 회복 |
| 2026-04-22 | M9-2 Option B | 영어 합성 대학 403 QA 구축, R-DWA F1 0.663 |
| 2026-04-22 | **M9-3 Option C** | **영어 L-DWA end-to-end, state 상한 실증** |
| 2026-04-22~23 | M10 통합본 | v11 → v12 → v13 → v14 (77 pages, 그림 8개 임베딩) |
| **2026-04-30** | **제출** | **호서대 박사학위 논문 제출** |

### 의사결정 3개 핵심 순간

1. **버그 발견 (4/21 저녁)**: F1 이 기대보다 낮다는 이상 관찰 → evaluator.py 역추적 → 구두점 누락 확인. 논문의 절대 수치가 일제히 ~2배 상승.

2. **CORRIGENDUM 결정 (4/22 오전)**: 선행 JKSCI 논문의 Table 8 미실행 증거 발견 → "숨기지 않고 공개 정정" 으로 방침 결정. 학술 정직성 vs 방어 편의 사이에서 전자 선택.

3. **교차 도메인 재프레이밍 (4/22 저녁)**: "transfer 실패는 약점" → "실패 원인 분해 + 해결 경로 실증" 으로 서사 전환. Option A/B/C 실험이 부정적 결과조차 학술적 주장으로 변환.

---

**부록 끝**

---

# 참고문헌 (References)

> IEEE 스타일 기준. 본문에서 "(저자, 연도)" 또는 "저자 et al. (연도)" 형식으로 인용된 모든 문헌과 본 연구의 재현을 위해 필요한 도구 · 라이브러리 · 데이터셋을 포함한다.

---

## [1] 선행 및 직접 관련 연구

[1] D.-W. Shin and N. Moon, "Performance Optimization Study of Hybrid RAG Engine Integrating Multi-Source Knowledge: Vector, Graph, and Ontology Approaches," *Journal of the Korea Society of Computer and Information (JKSCI)*, 2025. [GitHub 코드 및 CORRIGENDUM: https://github.com/sdw1621/hybrid-rag-comparsion]

[2] D.-W. Shin, "Performance Optimization of Triple-Hybrid RAG Framework via Proximal Policy Optimization-based Learned Dynamic Weighting," Ph.D. Dissertation, Hoseo University, 2026. (본 논문)

## [2] RAG 기본형 및 하이브리드 RAG

[3] P. Lewis, E. Perez, A. Piktus, F. Petroni, V. Karpukhin, N. Goyal, H. Küttler, M. Lewis, W.-T. Yih, T. Rocktäschel, S. Riedel, and D. Kiela, "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks," in *Advances in Neural Information Processing Systems (NeurIPS)*, vol. 33, pp. 9459–9474, 2020.

[4] Y. Gao, Y. Xiong, X. Gao, K. Jia, J. Pan, Y. Bi, Y. Dai, J. Sun, M. Wang, and H. Wang, "Retrieval-Augmented Generation for Large Language Models: A Survey," *arXiv preprint arXiv:2312.10997*, 2023.

## [3] GraphRAG 및 구조화 지식 결합

[5] D. Edge, H. Trinh, N. Cheng, J. Bradley, A. Chao, A. Mody, S. Truitt, and J. Larson, "From Local to Global: A Graph RAG Approach to Query-Focused Summarization," *arXiv preprint arXiv:2404.16130*, 2024.

[6] B. Ma, C. Wu, and S. Ji, "Hybrid RAG: Integrating Knowledge Graph and Text Retrieval for Question Answering," in *Proc. ACL Workshop on Knowledge Augmented Methods for NLP*, 2024.

## [4] Self-Reflective / Corrective RAG

[7] A. Asai, Z. Wu, Y. Wang, A. Sil, and H. Hajishirzi, "Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection," in *Int. Conf. on Learning Representations (ICLR)*, 2024.

[8] S. Yan, J. Gu, Y. Zhu, and Z. Ling, "Corrective Retrieval Augmented Generation (CRAG)," *arXiv preprint arXiv:2401.15884*, 2024.

## [5] 적응형 라우팅 및 쿼리 복잡도 기반 검색

[9] S. Jeong, J. Baek, S. Cho, S. J. Hwang, and J. C. Park, "Adaptive-RAG: Learning to Adapt Retrieval-Augmented Large Language Models through Question Complexity," in *Proc. NAACL*, 2024.

[10] O. Khattab and M. Zaharia, "ColBERT: Efficient and Effective Passage Search via Contextualized Late Interaction over BERT," in *Proc. SIGIR*, pp. 39–48, 2020.

## [6] 강화학습 (PPO) 및 정책 최적화

[11] J. Schulman, S. Levine, P. Abbeel, M. Jordan, and P. Moritz, "Trust Region Policy Optimization," in *Proc. ICML*, 2015.

[12] J. Schulman, P. Moritz, S. Levine, M. Jordan, and P. Abbeel, "High-Dimensional Continuous Control using Generalized Advantage Estimation (GAE)," in *Int. Conf. on Learning Representations (ICLR)*, 2016.

[13] J. Schulman, F. Wolski, P. Dhariwal, A. Radford, and O. Klimov, "Proximal Policy Optimization Algorithms," *arXiv preprint arXiv:1707.06347*, 2017.

## [7] 언어 모델 및 임베딩

[14] J. Devlin, M.-W. Chang, K. Lee, and K. Toutanova, "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding," in *Proc. NAACL-HLT*, pp. 4171–4186, 2019.

[15] S. Park, J. Moon, S. Kim, J. Y. Cho, J. Han, et al., "KLUE: Korean Language Understanding Evaluation," in *Advances in Neural Information Processing Systems (NeurIPS) Datasets and Benchmarks Track*, 2021. (본 논문의 BERT Intent Classifier 는 `klue/bert-base` 사용)

[16] OpenAI, "GPT-4o-mini: Advancing Cost-Efficient Intelligence," Technical Report, 2024. (본 논문 모든 LLM 호출에 사용, `gpt-4o-mini-2024-07-18`)

[17] OpenAI, "text-embedding-3-small: New Embedding Model," 2024. (본 논문 Vector 임베딩 1,536-dim, 코사인 유사도)

## [8] 벤치마크 데이터셋

[18] Z. Yang, P. Qi, S. Zhang, Y. Bengio, W. W. Cohen, R. Salakhutdinov, and C. D. Manning, "HotpotQA: A Dataset for Diverse, Explainable Multi-hop Question Answering," in *Proc. EMNLP*, pp. 2369–2380, 2018.

[19] H. Trivedi, N. Balasubramanian, T. Khot, and A. Sabharwal, "MuSiQue: Multihop Questions via Single-hop Question Composition," *Transactions of the Association for Computational Linguistics (TACL)*, vol. 10, pp. 539–554, 2022.

[20] Q. Jin, B. Dhingra, Z. Liu, W. Cohen, and X. Lu, "PubMedQA: A Dataset for Biomedical Research Question Answering," in *Proc. EMNLP-IJCNLP*, pp. 2567–2577, 2019.

## [9] RAG 평가 방법론

[21] S. ES, J. James, L. Espinosa Anke, and S. Schockaert, "RAGAS: Automated Evaluation of Retrieval Augmented Generation," *arXiv preprint arXiv:2309.15217*, 2023. (본 논문 Faithfulness 지표의 기반)

[22] P. Rajpurkar, J. Zhang, K. Lopyrev, and P. Liang, "SQuAD: 100,000+ Questions for Machine Comprehension of Text," in *Proc. EMNLP*, pp. 2383–2392, 2016. (F1 / EM 평가 방법의 원류)

## [10] 도구 및 구현 의존성 (Software References)

[23] J. Johnson, M. Douze, and H. Jégou, "Billion-scale similarity search with GPUs (FAISS)," *IEEE Transactions on Big Data*, vol. 7, no. 3, pp. 535–547, 2019. [https://github.com/facebookresearch/faiss]

[24] A. A. Hagberg, D. A. Schult, and P. J. Swart, "Exploring Network Structure, Dynamics, and Function using NetworkX," in *Proc. 7th Python in Science Conference*, pp. 11–15, 2008. [https://networkx.org]

[25] J.-B. Lamy, "Owlready: Ontology-oriented programming in Python with automatic classification and high level constructs for biomedical ontologies," *Artificial Intelligence in Medicine*, vol. 80, pp. 11–28, 2017. [https://owlready2.readthedocs.io]

[26] R. Shearer, B. Motik, and I. Horrocks, "HermiT: A Highly-Efficient OWL Reasoner," in *OWL: Experiences and Directions (OWLED)*, 2008. [http://www.hermit-reasoner.com]

[27] A. Paszke, S. Gross, F. Massa, A. Lerer, J. Bradbury, et al., "PyTorch: An Imperative Style, High-Performance Deep Learning Library," in *Advances in Neural Information Processing Systems (NeurIPS)*, vol. 32, pp. 8024–8035, 2019.

[28] T. Wolf, L. Debut, V. Sanh, J. Chaumond, C. Delangue, et al., "Transformers: State-of-the-Art Natural Language Processing," in *Proc. EMNLP Demo Track*, 2020. [https://huggingface.co/docs/transformers]

[29] Langchain-AI, "LangChain: Building applications with LLMs through composability," 2023. [https://langchain.com]

[30] Streamlit Inc., "Streamlit: The fastest way to build and share data apps," 2024. [https://streamlit.io] (본 논문 대시보드 구현)

## [11] 저장소 및 재현 자료

[31] D.-W. Shin, "Triple-Hybrid RAG PhD Thesis Repository," 2026. [https://github.com/sdw1621/triple-rag-phd]

[32] D.-W. Shin, "hybrid-rag-comparsion (Prior Work Repository with CORRIGENDUM)," 2026. [https://github.com/sdw1621/hybrid-rag-comparsion/blob/main/CORRIGENDUM.md]

---

## 참고문헌 정리 원칙

1. **IEEE 스타일** 을 기준으로 정렬하며, 동일 저자의 연속 발간 시 연도 역순.
2. **온라인 리소스**는 접근일을 본문 각주에 기재 (본 목록에는 저장소 URL 만 포함).
3. **선행 저장소의 CORRIGENDUM** 은 별도 항목 [32] 로 명시 — 본 박사논문의 재현성 기여 (§1.3.1) 의 직접 근거.
4. **본문 미인용** 이지만 본 연구의 **재현에 필수** 인 도구 (FAISS, NetworkX 등) 는 §10 에 "Software References" 로 포함.

총 32 항목.

---

# 감사의 글

본 박사학위 논문이 완성되기까지 많은 분들의 도움을 받았습니다. 이 자리를 빌려 깊은 감사의 말씀을 전합니다.

먼저 본 연구의 시작부터 완성까지 학문적 방향을 지도하여 주신 **문남미 교수님**께 깊은 감사를 드립니다. 교수님께서는 석사 과정부터 박사 과정까지 수년에 걸쳐 연구의 본질을 탐구하는 자세와 엄밀한 방법론을 가르쳐 주셨으며, 본 논문이 단순한 성능 보고에 그치지 않고 선행 연구의 재현성 문제까지 투명하게 다룰 수 있도록 격려해 주셨습니다. 특히 실험 결과가 기대와 어긋났을 때에도 "정직한 부정적 결과가 방법론을 오히려 강화한다" 는 가르침은 본 논문의 **재현성 기여 (§Ⅰ.3.1)** 와 **교차 도메인 한계의 재프레이밍 (§Ⅵ.7.7)** 의 근간이 되었습니다.

또한 박사학위 심사 과정에서 세심한 조언과 날카로운 질문으로 본 논문의 품질 향상에 기여하여 주신 심사위원 교수님들께도 감사드립니다. 특히 평가 지표의 엄격성, 3-seed 재현성의 통계적 의의, Oracle 초과의 학술적 해석 등 본 논문의 핵심 주장에 대한 비판적 검토는 학문적 완결성을 크게 높여 주었습니다.

연구실 동료들과 **호서대학교 융합공학과 대학원** 구성원들의 학술적 교류 또한 본 논문의 완성에 큰 영향을 주었습니다. Triple-Hybrid RAG 아키텍처의 실무적 구현 가능성, 한국어 QA 벤치마크의 평가 기준 논의, PPO 학습의 재현성 검증 방법론 등 다양한 세미나 발표와 토론이 연구의 시야를 넓혀 주었습니다.

**기술적 기반** 측면에서는 오픈소스 커뮤니티에 큰 빚을 졌습니다. PyTorch, Hugging Face Transformers, FAISS, NetworkX, Owlready2, HermiT 등 본 논문의 모든 구현은 이들 프로젝트 없이는 불가능했을 것입니다. 또한 OpenAI 의 GPT-4o-mini API 는 본 연구의 330,000 엔트리 오프라인 보상 캐시 구축을 현실적 비용(\$33) 으로 가능하게 하였으며, 이는 본 논문의 **엔지니어링 기여 (§Ⅰ.3.4)** 의 핵심 전제입니다.

본 논문은 저자의 **선행 JKSCI 2025 논문** 을 직접 확장한 작업입니다. 선행 논문의 저장소 (`sdw1621/hybrid-rag-comparsion`) 를 재분석하는 과정에서 발견된 재현성 문제를 자발적으로 정정하여 CORRIGENDUM 을 공개할 수 있었던 것은, 학술적 투명성을 중시하는 연구 문화 덕분이라고 생각합니다. 향후 연구자들이 본 저장소와 CORRIGENDUM 을 통해 본 연구를 더욱 엄격하게 재현하고 발전시킬 수 있기를 희망합니다.

무엇보다 긴 박사과정 동안 정서적·물질적으로 지지해 주신 **가족** — 특히 학위 과정의 많은 시간을 양보해 주신 부모님과 배우자께 진심으로 감사드립니다. 학업과 연구에만 몰두할 수 있도록 해주신 가족의 희생과 격려 없이는 본 논문이 세상에 나올 수 없었을 것입니다.

마지막으로, 본 논문의 주제인 **"규칙 기반에서 학습형으로"** 의 전환이 상징하듯, 연구는 언제나 선행 지식을 비판적으로 계승하되 **한계를 솔직하게 인정하고 새 방향을 제시하는 일** 이라는 것을 배웠습니다. 본 논문이 Triple-Hybrid RAG 연구의 작은 발걸음이 되어, 향후 더 큰 성과로 이어지기를 기대합니다.

**2026년 4월**  
**신동욱 (Shin Dong-wook)**

---

