"""
Build the offline reward cache for English synthetic university benchmark.

Adapted from scripts/build_cache.py for the English corpus generated by
data/university_en/dataset_generator_en.py. Key differences from Korean
cache:
  - Loads English corpus_en.json instead of Korean university data
  - Graph / Ontology empty (English graph/ontology not built) — Vector-only
    effective retrieval
  - Uses PROMPT_TEMPLATE_LIST (list prompt) to match gold format
  - Smaller scale: 403 QA × 66 weight grid = 26,598 entries (~ 45 min, ~$5)

Usage (in-container):
    python scripts/build_cache_en.py \\
        --output cache/university_en.sqlite \\
        --grid 10 --workers 10
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.dwa.base import DWAWeights  # noqa: E402
from src.eval.metrics import evaluate_single  # noqa: E402
from src.rag.triple_hybrid_rag import PROMPT_TEMPLATE_LIST, merge_contexts  # noqa: E402
from src.rag.vector_store import VectorStore  # noqa: E402
from src.utils.offline_cache import (  # noqa: E402
    OfflineCache,
    RewardComponents,
    enumerate_simplex,
    simplex_size,
)
from src.utils.seed import set_seed  # noqa: E402

logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger("build_cache_en")

CORPUS_PATH = ROOT / "data" / "university_en" / "corpus_en.json"
QA_PATH = ROOT / "data" / "university_en" / "gold_qa_500_en.json"
TOP_K = 3


class _OpenAILLM:
    def __init__(self) -> None:
        from langchain_openai import ChatOpenAI
        self._c = ChatOpenAI(model="gpt-4o-mini", temperature=0.0, max_tokens=500)

    def generate(self, prompt: str) -> str:
        r = self._c.invoke(prompt)
        return r.content if hasattr(r, "content") else str(r)


def build_one(
    item: dict,
    v_contexts: list[str],
    grid_int: int,
    llm: _OpenAILLM,
) -> list[tuple[str, DWAWeights, RewardComponents]]:
    """For one QA item, enumerate weight grid, measure reward for each.

    Returns list of (query_id, DWAWeights, RewardComponents) triples suitable
    for OfflineCache.put_many().
    """
    rows: list[tuple[str, DWAWeights, RewardComponents]] = []
    qid = str(item["id"])
    gold = item["answer"]
    for a, b, g in enumerate_simplex(grid_int):
        w = DWAWeights(a / grid_int, b / grid_int, g / grid_int)
        t0 = time.time()
        # Graph / Ontology empty lists for English benchmark
        context = merge_contexts(v_contexts, [], [], w, TOP_K)
        prompt = PROMPT_TEMPLATE_LIST.format(context=context, query=item["query"])
        answer = llm.generate(prompt)
        latency = time.time() - t0
        ev = evaluate_single(
            pred=answer, gold=gold,
            retrieved_docs=v_contexts, contexts=v_contexts,
        )
        rc = RewardComponents(
            f1=float(ev.f1),
            em=float(ev.em_norm),
            faithfulness=float(ev.faithfulness),
            latency=latency,
        )
        rows.append((qid, w, rc))
    return rows


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--output", required=True, type=Path)
    p.add_argument("--grid", type=int, default=10)
    p.add_argument("--workers", type=int, default=10)
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()

    set_seed(args.seed)

    if not os.environ.get("OPENAI_API_KEY"):
        raise SystemExit("OPENAI_API_KEY not set")

    with CORPUS_PATH.open(encoding="utf-8") as f:
        corpus = json.load(f)
    with QA_PATH.open(encoding="utf-8") as f:
        qa = json.load(f)
    if args.limit:
        qa = qa[: args.limit]

    n_simplex = simplex_size(args.grid)
    logger.info("English benchmark: %d QA × %d weight combos = %d entries",
                len(qa), n_simplex, len(qa) * n_simplex)

    # Resume: skip queries that already have full weight-grid coverage in cache.
    done_qids: set[str] = set()
    if args.output.exists():
        import sqlite3
        try:
            with sqlite3.connect(str(args.output)) as _c:
                cur = _c.execute(
                    "SELECT query_id, COUNT(*) FROM rewards GROUP BY query_id"
                )
                for qid, n in cur:
                    if n >= n_simplex:
                        done_qids.add(str(qid))
        except Exception as e:
            logger.warning("could not inspect existing cache for resume: %s", e)
    if done_qids:
        before = len(qa)
        qa = [q for q in qa if str(q["id"]) not in done_qids]
        logger.info("Resume: skipping %d already-done queries (remaining %d)",
                    before - len(qa), len(qa))

    # Build VectorStore
    vector = VectorStore()
    vector.add_documents(corpus["documents"])
    logger.info("VectorStore: %d docs indexed", len(corpus["documents"]))

    # Pre-compute per-query retrievals (Vector only for English)
    logger.info("Pre-computing Vector retrievals (top_k=%d)...", TOP_K)
    retrievals: dict[str, list[str]] = {}
    t0 = time.time()
    for item in qa:
        qid = str(item["id"])
        hits = vector.search(item["query"], top_k=TOP_K)
        retrievals[qid] = [d for d, _ in hits]
    logger.info("Retrievals done in %.1fs", time.time() - t0)

    llm = _OpenAILLM()
    cache = OfflineCache(args.output)

    logger.info("Starting cache build (%d workers)...", args.workers)
    total_rows = 0
    start = time.time()

    def _work(item: dict) -> list[tuple[str, DWAWeights, RewardComponents]]:
        qid = str(item["id"])
        return build_one(item, retrievals[qid], args.grid, llm)

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = {pool.submit(_work, item): item for item in qa}
        for i, fut in enumerate(as_completed(futures)):
            try:
                rows = fut.result()
                cache.put_many(rows)
                total_rows += len(rows)
            except Exception as e:
                logger.exception("query %s failed: %s",
                                 futures[fut]["id"], e)
            if (i + 1) % 20 == 0 or (i + 1) == len(qa):
                elapsed = time.time() - start
                rate = total_rows / max(elapsed, 0.1)
                eta = (len(qa) * n_simplex - total_rows) / max(rate, 0.1)
                logger.info(
                    "  [%d/%d queries, %d rows written, %.1f row/s, ETA %.1f min]",
                    i + 1, len(qa), total_rows, rate, eta / 60
                )

    cache.close()
    logger.info("Cache build complete: %d rows in %.1f min",
                total_rows, (time.time() - start) / 60)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
