"""
Evaluate R-DWA on the English synthetic university benchmark.

Part of Ch.6 §7 cross-lingual Option B experiment. Loads the English
corpus/QA generated by data/university_en/dataset_generator_en.py,
runs retrieval (Vector-only since Graph/Ontology are language-
specific), and measures F1/Faith on the 403 gold QA.

Purpose: show that R-DWA works when the whole pipeline (corpus +
queries + evaluation) is native English — demonstrating that the
cross-domain failure observed earlier is not a fundamental L-DWA
limitation but a language/domain alignment issue.

Usage (in-container):
    python scripts/evaluate_english_synthetic.py \\
        --output results/english_synthetic_rdwa.json
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.eval.metrics import (  # noqa: E402
    exact_match,
    f1_char,
    f1_score,
    f1_substring,
    faithfulness,
)
from src.intent.rule_based import RuleBasedIntent  # noqa: E402
from src.rag.triple_hybrid_rag import PROMPT_TEMPLATE_LIST  # noqa: E402
from src.rag.vector_store import VectorStore  # noqa: E402
from src.utils.seed import set_seed  # noqa: E402

logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger("evaluate_english_synthetic")


CORPUS_PATH = ROOT / "data" / "university_en" / "corpus_en.json"
QA_PATH = ROOT / "data" / "university_en" / "gold_qa_500_en.json"


class _OpenAILLM:
    def __init__(self) -> None:
        from langchain_openai import ChatOpenAI
        self._c = ChatOpenAI(model="gpt-4o-mini", temperature=0.0, max_tokens=500)

    def generate(self, prompt: str) -> str:
        r = self._c.invoke(prompt)
        return r.content if hasattr(r, "content") else str(r)


def eval_one(item: dict, vector: VectorStore, llm: _OpenAILLM) -> dict:
    q = item["query"]
    gold = item["answer"]
    hits = vector.search(q, top_k=3)
    contexts = [d for d, _ in hits]
    context_str = "\n".join(contexts) if contexts else ""
    start = time.time()
    prompt = PROMPT_TEMPLATE_LIST.format(context=context_str, query=q)
    answer = llm.generate(prompt)
    lat = time.time() - start
    return {
        "qid": str(item["id"]),
        "type": item.get("type", "unknown"),
        "gold": gold,
        "answer": answer,
        "metrics": {
            "f1_strict": f1_score(answer, gold),
            "f1_substring": f1_substring(answer, gold),
            "f1_char": f1_char(answer, gold),
            "em_norm": exact_match(answer, gold, normalize=True),
            "faithfulness": faithfulness(answer, contexts),
            "latency": lat,
        },
    }


def aggregate(results: list[dict]) -> dict:
    def stat(arr):
        return {"mean": float(np.mean(arr)), "std": float(np.std(arr)), "n": len(arr)}

    f1s = [r["metrics"]["f1_strict"] for r in results]
    f1sub = [r["metrics"]["f1_substring"] for r in results]
    f1c = [r["metrics"]["f1_char"] for r in results]
    ems = [r["metrics"]["em_norm"] for r in results]
    faith = [r["metrics"]["faithfulness"] for r in results]
    lat = [r["metrics"]["latency"] for r in results]

    by_type: dict[str, dict] = {}
    for r in results:
        t = r["type"]
        b = by_type.setdefault(
            t, {"f1s": [], "f1sub": [], "f1c": [], "em": [], "faith": []}
        )
        b["f1s"].append(r["metrics"]["f1_strict"])
        b["f1sub"].append(r["metrics"]["f1_substring"])
        b["f1c"].append(r["metrics"]["f1_char"])
        b["em"].append(r["metrics"]["em_norm"])
        b["faith"].append(r["metrics"]["faithfulness"])

    return {
        "overall": {
            "F1_strict": stat(f1s),
            "F1_substring": stat(f1sub),
            "F1_char": stat(f1c),
            "EM_norm": stat(ems),
            "Faithfulness": stat(faith),
            "Latency": stat(lat),
        },
        "by_type": {
            t: {
                "F1_strict": stat(b["f1s"]),
                "F1_substring": stat(b["f1sub"]),
                "F1_char": stat(b["f1c"]),
                "EM_norm": stat(b["em"]),
                "Faithfulness": stat(b["faith"]),
            }
            for t, b in by_type.items()
        },
    }


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--output", required=True, type=Path)
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--workers", type=int, default=10)
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()

    set_seed(args.seed)

    if not os.environ.get("OPENAI_API_KEY"):
        raise SystemExit("OPENAI_API_KEY not set")

    with CORPUS_PATH.open(encoding="utf-8") as f:
        corpus = json.load(f)
    with QA_PATH.open(encoding="utf-8") as f:
        qa = json.load(f)
    if args.limit:
        qa = qa[: args.limit]

    logger.info("Corpus: %d docs | QA: %d queries", len(corpus["documents"]), len(qa))

    vector = VectorStore()
    vector.add_documents(corpus["documents"])
    logger.info("VectorStore ready (%d docs indexed)", len(corpus["documents"]))

    llm = _OpenAILLM()

    results: list[dict] = []
    t0 = time.time()
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = [pool.submit(eval_one, item, vector, llm) for item in qa]
        for i, fut in enumerate(as_completed(futures)):
            try:
                results.append(fut.result())
            except Exception as e:
                logger.exception("failed: %s", e)
            if (i + 1) % 50 == 0 or (i + 1) == len(qa):
                logger.info("  %d/%d (%.1fs)", i + 1, len(qa), time.time() - t0)

    agg = aggregate(results)
    o = agg["overall"]
    logger.info(
        "Overall: F1s=%.4f F1sub=%.4f F1c=%.4f EM=%.4f Faith=%.4f Lat=%.2fs",
        o["F1_strict"]["mean"], o["F1_substring"]["mean"], o["F1_char"]["mean"],
        o["EM_norm"]["mean"], o["Faithfulness"]["mean"], o["Latency"]["mean"],
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "benchmark": "english_synthetic_university",
        "policy": "rdwa (list prompt, Vector-only — Graph/Ontology empty for EN)",
        "n_queries": len(results),
        "aggregate": agg,
        "samples": results[:30],
    }
    args.output.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    logger.info("Wrote %s", args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
